// Static wireframe data for Governance (ZST-WF-SA-GOV-001 · screen S14).
//
// §35 lists the Governance/Obligations Registry, Identity & Access, Audit, the data inventory,
// residency telemetry, the retention evaluator, the legal-hold service and the evidence store as
// build blockers. So this module is the demonstration payload for the interface and the page says
// so on its face.
//
// Four rules from the spec shape every record below:
//   · NO UNIVERSAL COMPLIANCE SCORE — there is no `score`, `percent_compliant` or `health` field
//     anywhere in this file. Scoped coverage counts exist; one authoritative number does not.
//   · STD-04 — obligation, policy, control, evidence, risk, exception, hold, privacy request,
//     DPIA, residency, assurance and timing are SEPARATE axes. Timing is never workflow state.
//   · FAIL-CLOSED DISPLAY — residency UNKNOWN is a real value that is never rendered as
//     compliant, and "no conflict detected" is not "placement verified compliant".
//   · EXCEPTIONS NEVER CHANGE THE BASELINE — an excepted requirement stays visible as
//     unsatisfied, so compliant-by-design and operating-under-exception never look alike.

export const OBLIGATION_STATES = ["DRAFT", "UNDER_REVIEW", "ACTIVE", "FUTURE_EFFECTIVE", "CHANGED", "WITHDRAWN", "SUPERSEDED"];
export const POLICY_STATES = ["DRAFT", "IN_REVIEW", "APPROVED", "EFFECTIVE", "SUPERSEDED", "RETIRED"];
export const ASSURANCE_STATES = [
  "NOT_TESTED",
  "EFFECTIVE",
  "EFFECTIVE_WITH_OBSERVATIONS",
  "PARTIALLY_EFFECTIVE",
  "INEFFECTIVE",
  "NOT_APPLICABLE",
];
export const EVIDENCE_STATES = ["CURRENT", "EXPIRING", "EXPIRED", "MISSING", "WITHDRAWN", "SUPERSEDED", "CHALLENGED"];
export const EXCEPTION_STATES = ["DRAFT", "SUBMITTED", "UNDER_REVIEW", "APPROVED", "REJECTED", "ACTIVE", "EXPIRED", "REVOKED", "CLOSED"];
export const HOLD_STATES = ["PROPOSED", "ACTIVE", "MODIFIED", "RELEASE_PENDING", "RELEASED"];
export const PRIVACY_STATES = [
  "RECEIVED",
  "IDENTITY_VERIFICATION",
  "SCOPING",
  "IN_PROGRESS",
  "REVIEW",
  "FULFILLED",
  "PARTIALLY_FULFILLED",
  "DENIED",
  "WITHDRAWN",
];
export const DPIA_STATES = ["SCREENING", "REQUIRED", "IN_PROGRESS", "CONSULTATION", "APPROVED", "APPROVED_WITH_CONDITIONS", "BLOCKED", "RETIRED"];
export const RESIDENCY_POSTURES = ["COMPLIANT", "AT_RISK", "CONFLICT", "UNKNOWN", "EXCEPTION_ACTIVE"];
export const SUBPROCESSOR_STATES = ["PROPOSED", "DUE_DILIGENCE", "APPROVED", "RESTRICTED", "SUSPENDED", "EXITING", "RETIRED"];
export const TIMING_STATES = ["ON_TRACK", "WARNING", "OVERDUE"];

export const RECORD_TYPES = ["Obligation", "Policy", "Privacy", "Hold", "DPIA", "Exception", "Assurance", "Residency", "Retention"];
export const PRIORITIES = ["CRITICAL", "HIGH", "MEDIUM", "LOW"];

export const JURISDICTIONS = ["EU", "UK", "US", "Netherlands", "Global / contractual", "Platform internal"];

export const REGIONS = [
  { id: "europe-west2", label: "Europe · London" },
  { id: "europe-west4", label: "Europe · Netherlands" },
  { id: "us-east4", label: "US · N. Virginia" },
  { id: "us-west2", label: "US · Los Angeles" },
];

export const OWNERS = [
  "Data Governance",
  "Privacy Operations",
  "GRC",
  "Legal / Compliance",
  "Security Engineering",
  "Platform Operations",
  "Governance Board",
];

export const ORGANIZATIONS = [
  "All Organizations",
  "Northstar Services",
  "Apex Systems",
  "Grace Network",
  "Eastbridge University",
  "City of Northfield",
  "Meridian Holdings",
  "Beacon Retail Group",
  "Helix Manufacturing",
];

const LABEL = {
  NOT_TESTED: "Not tested",
  EFFECTIVE_WITH_OBSERVATIONS: "Effective with observations",
  PARTIALLY_EFFECTIVE: "Partially effective",
  NOT_APPLICABLE: "Not applicable",
  FUTURE_EFFECTIVE: "Future effective",
  IN_REVIEW: "In review",
  UNDER_REVIEW: "Under review",
  IDENTITY_VERIFICATION: "Identity verification",
  IN_PROGRESS: "In progress",
  PARTIALLY_FULFILLED: "Partially fulfilled",
  APPROVED_WITH_CONDITIONS: "Approved with conditions",
  DUE_DILIGENCE: "Due diligence",
  RELEASE_PENDING: "Release pending",
  EXCEPTION_ACTIVE: "Exception active",
  AT_RISK: "At risk",
  ON_TRACK: "On track",
};
// SCREAMING_SNAKE identifier -> display label, with an override map for the cases where
// sentence-casing is wrong. An unmapped value renders converted rather than as "Unknown":
// coercing a state the registry gave us into Unknown is the exact lie the state-separation
// rules exist to prevent.
//
// Kept local so this module stays a dependency-free payload — it is data, and data importing UI
// formatting helpers is the wrong direction (it also lets `node --test` load it directly).
const toLabel = (v, overrides) =>
  overrides[v] || (v ? v.charAt(0) + v.slice(1).toLowerCase().replace(/_/g, " ") : "—");
export const label = (v) => toLabel(v, LABEL);

export const PRIORITY_TONE = { CRITICAL: "danger", HIGH: "warning", MEDIUM: "info", LOW: "neutral" };
export const TIMING_TONE = { ON_TRACK: "success", WARNING: "warning", OVERDUE: "danger" };
export const OBLIGATION_TONE = {
  DRAFT: "neutral",
  UNDER_REVIEW: "info",
  ACTIVE: "success",
  FUTURE_EFFECTIVE: "info",
  CHANGED: "warning",
  WITHDRAWN: "neutral",
  SUPERSEDED: "neutral",
};
export const POLICY_TONE = {
  DRAFT: "neutral",
  IN_REVIEW: "info",
  APPROVED: "info",
  EFFECTIVE: "success",
  SUPERSEDED: "neutral",
  RETIRED: "neutral",
};
// NOT_APPLICABLE is deliberately neutral, never green: §33.15 requires it to carry a documented
// rationale and approval, and it is explicitly not Effective.
export const ASSURANCE_TONE = {
  NOT_TESTED: "warning",
  EFFECTIVE: "success",
  EFFECTIVE_WITH_OBSERVATIONS: "info",
  PARTIALLY_EFFECTIVE: "warning",
  INEFFECTIVE: "danger",
  NOT_APPLICABLE: "neutral",
};
export const EVIDENCE_TONE = {
  CURRENT: "success",
  EXPIRING: "warning",
  EXPIRED: "danger",
  MISSING: "danger",
  WITHDRAWN: "neutral",
  SUPERSEDED: "neutral",
  CHALLENGED: "warning",
};
export const EXCEPTION_TONE = {
  DRAFT: "neutral",
  SUBMITTED: "info",
  UNDER_REVIEW: "info",
  APPROVED: "info",
  REJECTED: "neutral",
  ACTIVE: "warning",
  EXPIRED: "neutral",
  REVOKED: "neutral",
  CLOSED: "neutral",
};
export const HOLD_TONE = { PROPOSED: "info", ACTIVE: "danger", MODIFIED: "warning", RELEASE_PENDING: "warning", RELEASED: "neutral" };
export const PRIVACY_TONE = {
  RECEIVED: "info",
  IDENTITY_VERIFICATION: "info",
  SCOPING: "info",
  IN_PROGRESS: "info",
  REVIEW: "warning",
  FULFILLED: "success",
  PARTIALLY_FULFILLED: "warning",
  DENIED: "neutral",
  WITHDRAWN: "neutral",
};
export const DPIA_TONE = {
  SCREENING: "info",
  REQUIRED: "warning",
  IN_PROGRESS: "info",
  CONSULTATION: "info",
  APPROVED: "success",
  APPROVED_WITH_CONDITIONS: "warning",
  BLOCKED: "danger",
  RETIRED: "neutral",
};
// UNKNOWN is warning, never success. Telemetry that cannot prove a location is not evidence of a
// permitted one.
export const RESIDENCY_TONE = {
  COMPLIANT: "success",
  AT_RISK: "warning",
  CONFLICT: "danger",
  UNKNOWN: "warning",
  EXCEPTION_ACTIVE: "info",
};
export const SUBPROCESSOR_TONE = {
  PROPOSED: "info",
  DUE_DILIGENCE: "info",
  APPROVED: "success",
  RESTRICTED: "warning",
  SUSPENDED: "danger",
  EXITING: "warning",
  RETIRED: "neutral",
};
export const APPLICABILITY_TONE = { CONFIRMED: "success", PROPOSED: "warning", UNDER_REVIEW: "info", NOT_APPLICABLE: "neutral" };

// §13 retention precedence. Rendered so the UI can always say which rule won and why.
export const RETENTION_PRECEDENCE = [
  "Active legal hold or preservation order",
  "Binding legal or regulatory requirement",
  "Contractual Organization requirement",
  "Approved Organization-specific policy",
  "Product/service entitlement or configured retention",
  "Platform default",
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V01 Governance Command & Action Queue
// §8.1 prioritization: hold conflicts, then residency conflicts on live data, then overdue
// privacy requests, then blocked DPIAs, then expired evidence, then expiring high-impact
// exceptions, then ineffective controls, then policy changes inside the implementation window.
// ─────────────────────────────────────────────────────────────────────────────
export const ACTIONS = [
  {
    id: "GA-4801",
    item: "Residency mismatch — approved EU/EEA footprint, observed non-approved replica",
    record_type: "Residency",
    source_record_id: "RES-ORG-184",
    scope: "Northstar Services · media storage · europe-west2",
    org: "Northstar Services",
    state: "CONFLICT",
    state_axis: "residency",
    evidence_state: "CURRENT",
    due_local: "Aug 7, 2026 · 12:00 BST",
    due_utc: "11:00 UTC",
    timing: "OVERDUE",
    priority: "CRITICAL",
    owner: "Data Governance",
    dependency: "Infrastructure & Delivery · storage replication owner",
    jurisdiction: "EU",
    obligations: ["OBL-1002"],
    controls: ["CTL-340"],
    risks: ["RSK-118"],
  },
  {
    id: "GA-4788",
    item: "Deletion attempt blocked by an active legal hold",
    record_type: "Hold",
    source_record_id: "GOV-HOLD-0231",
    scope: "Apex Systems · asset AST-2E540",
    org: "Apex Systems",
    state: "ACTIVE",
    state_axis: "hold",
    evidence_state: "CURRENT",
    due_local: "Aug 7, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    timing: "WARNING",
    priority: "CRITICAL",
    owner: "Legal / Compliance",
    dependency: "Media · preservation execution",
    jurisdiction: "US",
    obligations: ["OBL-1010"],
    controls: ["CTL-402"],
    risks: ["RSK-204"],
  },
  {
    id: "GA-4795",
    item: "Privacy request PR-921 — erasure, deadline inside the warning window",
    record_type: "Privacy",
    source_record_id: "PR-921",
    scope: "Apex Systems · one data subject",
    org: "Apex Systems",
    state: "IN_PROGRESS",
    state_axis: "privacy",
    evidence_state: "MISSING",
    due_local: "Aug 13, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    timing: "WARNING",
    priority: "HIGH",
    owner: "Privacy Operations",
    dependency: "Media · deletion execution; legal-hold conflict check",
    jurisdiction: "UK",
    obligations: ["OBL-1004"],
    controls: ["CTL-511"],
    risks: ["RSK-131"],
  },
  {
    id: "GA-4770",
    item: "DPIA-204 blocked — high residual privacy risk on planned viewer analytics",
    record_type: "DPIA",
    source_record_id: "DPIA-204",
    scope: "Platform · viewer engagement analytics",
    org: "All Organizations",
    state: "BLOCKED",
    state_axis: "dpia",
    evidence_state: "CURRENT",
    due_local: "Aug 21, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    timing: "WARNING",
    priority: "HIGH",
    owner: "Privacy Operations",
    dependency: "Product · Analytics engineering",
    jurisdiction: "EU",
    obligations: ["OBL-1004"],
    controls: ["CTL-520"],
    risks: ["RSK-140"],
  },
  {
    id: "GA-4762",
    item: "Evidence set for CTL-340 has expired — assurance requires reevaluation",
    record_type: "Assurance",
    source_record_id: "CTL-340",
    scope: "Platform · storage residency control",
    org: "All Organizations",
    state: "PARTIALLY_EFFECTIVE",
    state_axis: "assurance",
    evidence_state: "EXPIRED",
    due_local: "Aug 9, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    timing: "WARNING",
    priority: "HIGH",
    owner: "GRC",
    dependency: "Security Engineering · control tester",
    jurisdiction: "Global / contractual",
    obligations: ["OBL-1002"],
    controls: ["CTL-340"],
    risks: ["RSK-118"],
  },
  {
    id: "GA-4744",
    item: "Exception EX-117 approaching expiry — high impact, no silent renewal",
    record_type: "Exception",
    source_record_id: "EX-117",
    scope: "Grace Network · caption provisioning commitment",
    org: "Grace Network",
    state: "ACTIVE",
    state_axis: "exception",
    evidence_state: "CURRENT",
    due_local: "Aug 12, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    timing: "WARNING",
    priority: "MEDIUM",
    owner: "Governance Board",
    dependency: "Media Engineering · caption provider",
    jurisdiction: "Global / contractual",
    obligations: ["OBL-1021"],
    controls: ["CTL-608"],
    risks: ["RSK-155"],
  },
  {
    id: "GA-4731",
    item: "CTL-402 assessed Ineffective against an active material obligation",
    record_type: "Assurance",
    source_record_id: "CTL-402",
    scope: "Platform · deletion verification control",
    org: "All Organizations",
    state: "INEFFECTIVE",
    state_axis: "assurance",
    evidence_state: "CURRENT",
    due_local: "Aug 18, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    timing: "ON_TRACK",
    priority: "HIGH",
    owner: "GRC",
    dependency: "Media · deletion service owner",
    jurisdiction: "EU",
    obligations: ["OBL-1010"],
    controls: ["CTL-402"],
    risks: ["RSK-204"],
  },
  {
    id: "GA-4719",
    item: "Retention policy RP-22 change effective inside the implementation window",
    record_type: "Retention",
    source_record_id: "RP-22",
    scope: "Platform · recording retention defaults",
    org: "All Organizations",
    state: "FUTURE_EFFECTIVE",
    state_axis: "obligation",
    evidence_state: "CURRENT",
    due_local: "Aug 24, 2026 · 00:00 BST",
    due_utc: "Aug 23, 2026 · 23:00 UTC",
    timing: "ON_TRACK",
    priority: "MEDIUM",
    owner: "Data Governance",
    dependency: "Media · retention evaluator",
    jurisdiction: "Global / contractual",
    obligations: ["OBL-1010"],
    controls: ["CTL-402"],
    risks: [],
  },
  {
    id: "GA-4702",
    item: "Subprocessor evidence expiring — Verbit SOC 2 report period ends",
    record_type: "Obligation",
    source_record_id: "SUB-014",
    scope: "Platform · caption and translation processing",
    org: "All Organizations",
    state: "ACTIVE",
    state_axis: "obligation",
    evidence_state: "EXPIRING",
    due_local: "Aug 31, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    timing: "ON_TRACK",
    priority: "MEDIUM",
    owner: "GRC",
    dependency: "Vendor · Verbit assurance contact",
    jurisdiction: "Global / contractual",
    obligations: ["OBL-1031"],
    controls: ["CTL-712"],
    risks: ["RSK-160"],
  },
  {
    id: "GA-4690",
    item: "Access review campaign AR-2026-Q3 overdue for privileged production roles",
    record_type: "Assurance",
    source_record_id: "AR-2026-Q3",
    scope: "Platform · privileged production roles",
    org: "All Organizations",
    state: "NOT_TESTED",
    state_axis: "assurance",
    evidence_state: "MISSING",
    due_local: "Aug 5, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    timing: "OVERDUE",
    priority: "HIGH",
    owner: "GRC",
    dependency: "Identity & Access · review execution",
    jurisdiction: "Global / contractual",
    obligations: ["OBL-1015"],
    controls: ["CTL-801"],
    risks: ["RSK-170"],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V02 Obligations Register
// ─────────────────────────────────────────────────────────────────────────────
export const OBLIGATIONS = [
  {
    obligation_id: "OBL-1002",
    title: "EU/EEA data residency for customer media at rest",
    source_type: "Contract",
    source_reference: "MSA schedule 3 §4.2 (Northstar Services, Eastbridge University)",
    jurisdiction: "EU",
    applicability_status: "CONFIRMED",
    applicability_owner: "Legal / Compliance · confirmed by R. Duarte",
    lifecycle: "ACTIVE",
    effective_from: "Jan 1, 2026",
    review_by: "Jan 1, 2027",
    scope: "Customer media essence and derivatives · Organizations with an EU residency commitment",
    requirement:
      "Customer media essence, derivatives and backups must remain within approved EU/EEA regions unless an approved transfer record and a time-bound exception exist.",
    owner: "Data Governance",
    controls: ["CTL-340", "CTL-345"],
    evidence_requirements: ["Placement telemetry attestation", "Storage configuration test result", "Transfer register extract"],
    risk_ids: ["RSK-118"],
    exceptions: ["EX-104"],
    status_summary: "1 residency conflict open · control CTL-340 partially effective on expired evidence",
    coverage: "2 of 2 mapped controls; 1 has expired evidence",
  },
  {
    obligation_id: "OBL-1004",
    title: "Data protection by design and by default for new processing",
    source_type: "Law / regulation",
    source_reference: "Recorded statutory reference · applicability confirmed by Legal",
    jurisdiction: "EU",
    applicability_status: "CONFIRMED",
    applicability_owner: "Legal / Compliance · confirmed by R. Duarte",
    lifecycle: "ACTIVE",
    effective_from: "Platform inception",
    review_by: "Feb 1, 2027",
    scope: "Platform · all new or materially changed processing activities",
    requirement:
      "New or materially changed processing must be screened for privacy risk early enough to influence design, with minimization and purpose limitation considered at design time.",
    owner: "Privacy Operations",
    controls: ["CTL-511", "CTL-520"],
    evidence_requirements: ["DPIA screening record", "Design review artifact", "Consultation record where required"],
    risk_ids: ["RSK-131", "RSK-140"],
    exceptions: [],
    status_summary: "1 DPIA blocked · 1 privacy request inside the warning window",
    coverage: "2 of 2 mapped controls; both current",
  },
  {
    obligation_id: "OBL-1010",
    title: "Verified deletion and preservation execution",
    source_type: "Law / regulation",
    source_reference: "Recorded statutory and contractual references · applicability confirmed",
    jurisdiction: "EU",
    applicability_status: "CONFIRMED",
    applicability_owner: "Legal / Compliance · confirmed by R. Duarte",
    lifecycle: "ACTIVE",
    effective_from: "Mar 1, 2026",
    review_by: "Mar 1, 2027",
    scope: "Platform · all customer data classes subject to retention or erasure",
    requirement:
      "Deletion is complete only on verified downstream execution. Active legal holds override conflicting deletion, and partial failures remain open with residual locations named.",
    owner: "Data Governance",
    controls: ["CTL-402"],
    evidence_requirements: ["Deletion job completion evidence", "Post-deletion verification", "Hold conflict report"],
    risk_ids: ["RSK-204"],
    exceptions: [],
    status_summary: "Control CTL-402 assessed Ineffective — Governance action open",
    coverage: "1 of 1 mapped control; assessed Ineffective",
  },
  {
    obligation_id: "OBL-1015",
    title: "Periodic access review for privileged production roles",
    source_type: "Certification framework",
    source_reference: "Control framework mapping · access review requirement",
    jurisdiction: "Global / contractual",
    applicability_status: "CONFIRMED",
    applicability_owner: "GRC · confirmed by S. Adeyinka",
    lifecycle: "ACTIVE",
    effective_from: "Apr 1, 2026",
    review_by: "Apr 1, 2027",
    scope: "Platform · privileged production roles and standing elevations",
    requirement:
      "Privileged access is reviewed each quarter. Completion requires verified execution from Identity & Access, not a reviewer's click.",
    owner: "GRC",
    controls: ["CTL-801"],
    evidence_requirements: ["Entitlement snapshot", "Reviewer decisions with rationale", "IAM execution evidence"],
    risk_ids: ["RSK-170"],
    exceptions: [],
    status_summary: "Q3 campaign overdue · execution evidence missing",
    coverage: "1 of 1 mapped control; not tested this period",
  },
  {
    obligation_id: "OBL-1021",
    title: "Committed accessibility features for contracted events",
    source_type: "Customer commitment",
    source_reference: "Order form accessibility addendum (Grace Network, City of Northfield)",
    jurisdiction: "Global / contractual",
    applicability_status: "CONFIRMED",
    applicability_owner: "Legal / Compliance · confirmed by R. Duarte",
    lifecycle: "ACTIVE",
    effective_from: "Feb 1, 2026",
    review_by: "Feb 1, 2027",
    scope: "Organizations with an accessibility commitment · live and replay surfaces",
    requirement:
      "Where captions or translation are contractually committed, provisioning must be validated before the event and evidenced afterwards.",
    owner: "Data Governance",
    controls: ["CTL-608"],
    evidence_requirements: ["Provider connection test", "Language mapping record", "Post-event validation artifact"],
    risk_ids: ["RSK-155"],
    exceptions: ["EX-117"],
    status_summary: "Operating under approved exception EX-117 — the baseline remains unsatisfied",
    coverage: "1 of 1 mapped control; effective with observations",
  },
  {
    obligation_id: "OBL-1031",
    title: "Subprocessor assurance currency and transfer records",
    source_type: "Contract",
    source_reference: "Data processing terms §7 (all Organizations)",
    jurisdiction: "EU",
    applicability_status: "CONFIRMED",
    applicability_owner: "Legal / Compliance · confirmed by R. Duarte",
    lifecycle: "ACTIVE",
    effective_from: "Jan 1, 2026",
    review_by: "Jan 1, 2027",
    scope: "Platform · every approved subprocessor processing customer data",
    requirement:
      "Each approved subprocessor holds current assurance evidence with an exact scope, period and issuer, plus a transfer record where a cross-border transfer applies.",
    owner: "GRC",
    controls: ["CTL-712"],
    evidence_requirements: ["Assurance report with scope and period", "Contract with required terms", "Transfer assessment"],
    risk_ids: ["RSK-160"],
    exceptions: [],
    status_summary: "1 subprocessor evidence set expiring · 1 restricted pending diligence",
    coverage: "1 of 1 mapped control; effective",
  },
  {
    obligation_id: "OBL-1044",
    title: "Regulatory intelligence suggestion — proposed broadcast accessibility duty",
    source_type: "Law / regulation",
    source_reference: "Automated regulatory feed item RIF-2026-0881",
    jurisdiction: "UK",
    applicability_status: "PROPOSED",
    applicability_owner: "Unassigned — awaiting authorized Legal owner",
    lifecycle: "UNDER_REVIEW",
    effective_from: "Not established",
    review_by: "Aug 21, 2026",
    scope: "Proposed · UK live broadcast surfaces",
    requirement:
      "Suggested by an automated regulatory feed. The requirement statement is not settled and no control mapping has been made.",
    owner: "Legal / Compliance",
    controls: [],
    evidence_requirements: ["Legal applicability determination"],
    risk_ids: [],
    exceptions: [],
    status_summary: "SUGGESTED — not active. Only an authorized Legal/Governance owner may confirm applicability.",
    coverage: "No control mapping until applicability is confirmed",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V03 Policy Library
// ─────────────────────────────────────────────────────────────────────────────
export const POLICIES = [
  {
    policy_id: "POL-RET-004",
    title: "Recording retention and deletion policy",
    version: "v6",
    status: "EFFECTIVE",
    owner: "Data Governance · M. Ferreira",
    approvers: "Governance Board · Legal / Compliance",
    effective: "Jun 1, 2026 · 00:00 BST · May 31, 2026 · 23:00 UTC",
    scope: "Platform · all Organizations · recording and replay assets · all regions",
    requirements:
      "Retention is resolved through the governed precedence hierarchy. Deletion executes only through authoritative storage and media services, and completion requires verification.",
    exceptions: "Time-bound retention override, approved by Data Governance plus a required approver.",
    controls: ["CTL-402"],
    evidence: "Deletion job evidence, post-deletion verification, hold conflict reports",
    change_summary: "v6 added mandatory post-deletion verification and residual-location reporting for partial failures.",
    acknowledgment: "Platform Operations and Media Engineering · 100% complete",
    next_review: "Jun 1, 2027",
    obligations: ["OBL-1010"],
    versions: [
      { version: "v6", status: "EFFECTIVE", effective: "Jun 1, 2026", note: "Added verified-completion requirement." },
      { version: "v5", status: "SUPERSEDED", effective: "Nov 1, 2025", note: "Introduced the precedence hierarchy." },
      { version: "v4", status: "SUPERSEDED", effective: "Apr 1, 2025", note: "Original platform default durations." },
    ],
    history: [
      { at: "Jun 1, 2026 · 00:00 BST · May 31, 23:00 UTC", kind: "policy", text: "v6 became effective; v5 marked Superseded. History was not overwritten." },
      { at: "May 12, 2026 · 14:02 BST · 13:02 UTC", kind: "approval", text: "Approved by the Governance Board with a future effective date." },
      { at: "Apr 28, 2026 · 09:40 BST · 08:40 UTC", kind: "review", text: "Impact assessment completed across data, security, operations, contracts and accessibility." },
    ],
  },
  {
    policy_id: "POL-RES-002",
    title: "Data residency and cross-border transfer policy",
    version: "v3",
    status: "EFFECTIVE",
    owner: "Data Governance · M. Ferreira",
    approvers: "Legal / Compliance · Security Engineering",
    effective: "Feb 1, 2026 · 00:00 GMT · 00:00 UTC",
    scope: "Platform · Organizations with a residency commitment · storage, processing and backup",
    requirements:
      "Observed placement must be reconciled to authoritative telemetry. Unknown or stale placement evidence is never treated as compliant.",
    exceptions: "Time-bound residency exception with conditions, expiry and Governance Board approval.",
    controls: ["CTL-340", "CTL-345"],
    evidence: "Placement telemetry attestation, storage configuration tests, transfer register",
    change_summary: "v3 separated 'no conflict detected' from 'placement verified compliant'.",
    acknowledgment: "Infrastructure & Delivery · 100% complete",
    next_review: "Feb 1, 2027",
    obligations: ["OBL-1002"],
    versions: [
      { version: "v3", status: "EFFECTIVE", effective: "Feb 1, 2026", note: "Fail-closed display requirement added." },
      { version: "v2", status: "SUPERSEDED", effective: "Aug 1, 2025", note: "Added the transfer register." },
    ],
    history: [
      { at: "Feb 1, 2026 · 00:00 GMT · 00:00 UTC", kind: "policy", text: "v3 became effective; v2 marked Superseded." },
      { at: "Jan 14, 2026 · 11:20 GMT · 11:20 UTC", kind: "approval", text: "Approved by Legal / Compliance and Security Engineering." },
    ],
  },
  {
    policy_id: "POL-PRV-007",
    title: "Privacy rights request handling policy",
    version: "v4-draft",
    status: "IN_REVIEW",
    owner: "Privacy Operations · L. Haruna",
    approvers: "Legal / Compliance · DPO",
    effective: "Proposed Sep 1, 2026 · future effective",
    scope: "Platform · all supported privacy-rights request types · all jurisdictions",
    requirements:
      "Request workflow state stays separate from deadline state. A request cannot close while authoritative source actions remain incomplete, unless explicitly recorded as partially fulfilled or denied with a basis.",
    exceptions: "None permitted — deadline extensions follow the jurisdiction's own rules.",
    controls: ["CTL-511"],
    evidence: "Identity verification record, scoping record, per-source fulfillment evidence",
    change_summary: "v4 draft adds explicit partial-failure handling and separates timing from workflow state.",
    acknowledgment: "Pending — required on effective date",
    next_review: "On approval",
    obligations: ["OBL-1004"],
    versions: [
      { version: "v4-draft", status: "IN_REVIEW", effective: "Proposed Sep 1, 2026", note: "Partial-failure handling." },
      { version: "v3", status: "EFFECTIVE", effective: "Mar 1, 2026", note: "Currently in force." },
      { version: "v2", status: "SUPERSEDED", effective: "Jul 1, 2025", note: "Superseded by v3." },
    ],
    history: [
      { at: "Aug 4, 2026 · 10:12 BST · 09:12 UTC", kind: "review", text: "v4 draft entered review. v3 remains the effective version." },
      { at: "Mar 1, 2026 · 00:00 GMT · 00:00 UTC", kind: "policy", text: "v3 became effective." },
    ],
  },
  {
    policy_id: "POL-EXC-001",
    title: "Exception and risk-acceptance policy",
    version: "v2",
    status: "EFFECTIVE",
    owner: "GRC · S. Adeyinka",
    approvers: "Governance Board",
    effective: "May 1, 2026 · 00:00 BST · Apr 30, 2026 · 23:00 UTC",
    scope: "Platform · every governed requirement that permits an exception",
    requirements:
      "Exceptions are scoped no broader than necessary, time-bound, risk-linked, conditioned, and never silently auto-renewed. The base requirement stays visible as unsatisfied.",
    exceptions: "Not applicable — this policy governs exceptions.",
    controls: ["CTL-608"],
    evidence: "Exception record, residual risk assessment, approver decisions, post-review",
    change_summary: "v2 removed the renewal-on-expiry default and required a fresh approval.",
    acknowledgment: "All governance owners · 100% complete",
    next_review: "May 1, 2027",
    obligations: ["OBL-1021"],
    versions: [
      { version: "v2", status: "EFFECTIVE", effective: "May 1, 2026", note: "No silent auto-renewal." },
      { version: "v1", status: "SUPERSEDED", effective: "Jan 1, 2025", note: "Original policy." },
    ],
    history: [
      { at: "May 1, 2026 · 00:00 BST · Apr 30, 23:00 UTC", kind: "policy", text: "v2 became effective; v1 marked Superseded." },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V04 Data Map / Record of Processing Activities
// ─────────────────────────────────────────────────────────────────────────────
export const PROCESSING_ACTIVITIES = [
  {
    id: "PA-101",
    name: "Live broadcast contribution and delivery",
    purpose: "Ingest an Organization's contribution feed and deliver it to its authorized audience.",
    org_role: "Processor",
    data_subjects: "Organization staff, speakers, registered viewers",
    data_categories: "Audio-visual content, viewer registration identifiers, connection telemetry",
    sensitive: "May incidentally contain special-category content within broadcasts",
    collection: "Encoder contribution over SRT/RTMP; viewer registration at join",
    systems: "Ingest service, transcode pipeline, delivery service",
    lifecycle_stage: "Contribute / Ingest / Deliver",
    regions: ["europe-west2", "europe-west4", "us-east4", "us-west2"],
    subprocessors: ["SUB-002"],
    transfer_mechanism: "Approved intra-group and transfer record TR-0041 for US delivery",
    retention_policy: "RP-11 · session telemetry 90 days",
    security_controls: ["CTL-340", "CTL-345"],
    legal_basis: "Recorded per Organization; controller determination is Legal/Privacy-owned",
    dpia: "DPIA-188 · Approved",
    evidence_freshness: "Reconciled Aug 6, 2026 · 22:00 UTC · service catalog source current",
  },
  {
    id: "PA-104",
    name: "Recording, replay and preservation",
    purpose: "Capture, finalize, preserve and serve authorized replays of Organization events.",
    org_role: "Processor",
    data_subjects: "Organization staff, speakers, registered viewers",
    data_categories: "Audio-visual essence and derivatives, captions, transcripts, replay access records",
    sensitive: "May contain special-category content within broadcasts",
    collection: "Derived from live sessions; no separate collection",
    systems: "Preserve service, media asset service, storage",
    lifecycle_stage: "Produce / Secure / Preserve",
    regions: ["europe-west2", "europe-west4", "us-east4", "us-west2"],
    subprocessors: [],
    transfer_mechanism: "Not applicable — storage remains in the Organization's approved footprint",
    retention_policy: "RP-22 · per Organization, precedence-resolved",
    security_controls: ["CTL-340", "CTL-402"],
    legal_basis: "Recorded per Organization",
    dpia: "DPIA-188 · Approved",
    evidence_freshness: "Reconciled Aug 6, 2026 · 22:00 UTC",
  },
  {
    id: "PA-110",
    name: "Caption and translation generation",
    purpose: "Generate captions, transcripts and translations for committed accessibility features.",
    org_role: "Processor",
    data_subjects: "Speakers and anyone named within broadcast audio",
    data_categories: "Broadcast audio derivatives, text transcripts",
    sensitive: "Transcripts may contain special-category content",
    collection: "Derived from broadcast audio",
    systems: "Caption pipeline, third-party provider",
    lifecycle_stage: "Produce",
    regions: ["europe-west2", "us-east4"],
    subprocessors: ["SUB-014"],
    transfer_mechanism: "Transfer record TR-0058 · provider processing in US",
    retention_policy: "Follows the parent asset's retention",
    security_controls: ["CTL-712"],
    legal_basis: "Recorded per Organization",
    dpia: "DPIA-192 · Approved with conditions",
    evidence_freshness: "Reconciled Aug 6, 2026 · 22:00 UTC · subprocessor evidence expiring",
  },
  {
    id: "PA-118",
    name: "Viewer engagement analytics",
    purpose: "Produce aggregate engagement measurement for Organizations.",
    org_role: "Processor",
    data_subjects: "Registered viewers",
    data_categories: "Playback events, device class, coarse location, registration identifier",
    sensitive: "None identified in the current design",
    collection: "Client playback telemetry",
    systems: "Analytics pipeline",
    lifecycle_stage: "Understand",
    regions: ["us-east4"],
    subprocessors: [],
    transfer_mechanism: "Transfer record required — not yet established",
    retention_policy: "Proposed 13 months · not approved",
    security_controls: ["CTL-520"],
    legal_basis: "Not established — DPIA blocked",
    dpia: "DPIA-204 · BLOCKED",
    evidence_freshness: "Not reconciled — activity is planned, not live",
  },
  {
    id: "PA-124",
    name: "Trust & Safety case management",
    purpose: "Receive, evaluate, decide and evidence policy cases about tenant-originated content.",
    org_role: "Controller",
    data_subjects: "Reporters, speakers, named individuals, ZoikoStream reviewers",
    data_categories: "Case records, evidence references, content derivatives, reviewer identities",
    sensitive: "Case evidence may contain special-category content",
    collection: "Organization reports, internal referrals, automated signals, lawful requests",
    systems: "Trust & Safety case service, evidence store",
    lifecycle_stage: "Platform",
    regions: ["europe-west2"],
    subprocessors: [],
    transfer_mechanism: "Not applicable",
    retention_policy: "Case retention classes C1–C4; legal hold overrides",
    security_controls: ["CTL-511", "CTL-801"],
    legal_basis: "Recorded; controller determination is Legal/Privacy-owned",
    dpia: "DPIA-196 · Approved",
    evidence_freshness: "Reconciled Aug 6, 2026 · 22:00 UTC",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V05 Residency & Transfer Posture
// ─────────────────────────────────────────────────────────────────────────────
export const RESIDENCY = [
  {
    id: "RES-ORG-184",
    org: "Northstar Services",
    activity: "PA-104 · Recording and preservation",
    posture: "CONFLICT",
    required: "EU/EEA only · europe-west2, europe-west4",
    observed_processing: "europe-west2",
    observed_storage: "europe-west2 primary · us-east4 replica (non-approved)",
    subprocessor_locations: "None for this activity",
    transfer_record: "None — no approved mechanism covers this replica",
    telemetry_freshness: "Aug 7, 2026 · 06:40 UTC · current",
    exception: "None active",
    remediation: "Replica removal executed by Infrastructure & Delivery, not from this console",
    note: "Observed storage sits outside the permitted scope with no active approved exception.",
  },
  {
    id: "RES-ORG-092",
    org: "Eastbridge University",
    activity: "PA-104 · Recording and preservation",
    posture: "COMPLIANT",
    required: "EU/EEA only · europe-west2",
    observed_processing: "europe-west2",
    observed_storage: "europe-west2 primary, replica, backup",
    subprocessor_locations: "None for this activity",
    transfer_record: "Not required",
    telemetry_freshness: "Aug 7, 2026 · 06:40 UTC · current",
    exception: "None",
    remediation: "Not required",
    note: "Placement verified compliant against current telemetry — not merely 'no conflict detected'.",
  },
  {
    id: "RES-ORG-110",
    org: "Grace Network",
    activity: "PA-110 · Caption and translation generation",
    posture: "EXCEPTION_ACTIVE",
    required: "US only · us-east4",
    observed_processing: "us-east4 · provider processing in us-west2",
    observed_storage: "us-east4",
    subprocessor_locations: "SUB-014 · us-west2",
    transfer_record: "TR-0058 · approved mechanism recorded",
    telemetry_freshness: "Aug 7, 2026 · 06:40 UTC · current",
    exception: "EX-104 · expires Oct 31, 2026 · conditions recorded",
    remediation: "Provider region migration tracked as an exception condition",
    note: "Operating under an approved, time-bound exception. The underlying requirement remains unsatisfied.",
  },
  {
    id: "RES-ORG-201",
    org: "Meridian Holdings",
    activity: "PA-104 · Recording and preservation",
    posture: "UNKNOWN",
    required: "EU/EEA only · europe-west4",
    observed_processing: "europe-west4",
    observed_storage: "Archive tier placement not reported by telemetry",
    subprocessor_locations: "None for this activity",
    transfer_record: "Not required if placement is confirmed in-region",
    telemetry_freshness: "Jul 30, 2026 · 02:00 UTC · STALE beyond the configured threshold",
    exception: "None",
    remediation: "Restore telemetry coverage for the archive storage class",
    note: "Telemetry cannot prove placement. This is not compliant and is not a conflict — it is unknown, and it is never rendered as compliant.",
  },
  {
    id: "RES-ORG-155",
    org: "Beacon Retail Group",
    activity: "PA-101 · Contribution and delivery",
    posture: "AT_RISK",
    required: "US preferred · EU delivery permitted",
    observed_processing: "us-west2 · europe-west2 delivery",
    observed_storage: "us-west2",
    subprocessor_locations: "SUB-002 · multi-region edge",
    transfer_record: "TR-0041 · approved",
    telemetry_freshness: "Aug 7, 2026 · 06:40 UTC · current",
    exception: "None",
    remediation: "Confirm edge cache regions against the permitted list",
    note: "Edge cache footprint is broader than the recorded permitted list. No conflict is proven yet.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V06 Retention & Deletion
// ─────────────────────────────────────────────────────────────────────────────
export const RETENTION_POLICIES = [
  {
    id: "RP-22",
    scope: "Recording and replay assets · all Organizations · all regions",
    trigger: "Event end",
    duration: "Resolved per Organization — 90 days to 10 years",
    action: "Delete",
    exceptions: "Legal hold, dispute, investigation, contractual exception",
    effective_version: "POL-RET-004 v6 · effective Jun 1, 2026",
    winning_rule: "Varies per asset — the resolver names the winner on each evaluation",
    deletion_evidence: "Job IDs and completion evidence per execution",
    verification: "Post-deletion verification required",
    next_evaluation: "Continuous",
  },
  {
    id: "RP-11",
    scope: "Session and playback telemetry · platform",
    trigger: "Creation",
    duration: "90 days",
    action: "Delete",
    exceptions: "Investigation hold",
    effective_version: "POL-RET-004 v6 · effective Jun 1, 2026",
    winning_rule: "Platform default — no higher precedence rule applies",
    deletion_evidence: "Daily job del_tel_* with completion counts",
    verification: "Sampled verification",
    next_evaluation: "Daily",
  },
  {
    id: "RP-31",
    scope: "Trust & Safety case evidence · classes C1–C4",
    trigger: "Case closure",
    duration: "12 to 36 months by class",
    action: "Review, then delete",
    exceptions: "Legal hold always overrides",
    effective_version: "POL-RET-004 v6 · effective Jun 1, 2026",
    winning_rule: "Legal hold where present, otherwise the case retention class",
    deletion_evidence: "Per-case deletion record",
    verification: "Required before closure",
    next_evaluation: "Monthly",
  },
  {
    id: "RP-40",
    scope: "Test-mode assets · all Organizations",
    trigger: "Recording end",
    duration: "7 days",
    action: "Delete",
    exceptions: "None",
    effective_version: "POL-RET-004 v6 · effective Jun 1, 2026",
    winning_rule: "Platform default (test mode)",
    deletion_evidence: "Job del_test_* with completion counts",
    verification: "Sampled verification",
    next_evaluation: "Daily",
  },
];

// A worked deletion preview, used by the deletion dialog. Shows what would be affected, what
// blocks it, and that job acceptance is not completion.
export const DELETION_PREVIEW = {
  target: "RP-22 scheduled deletion · 3 assets eligible in the next window",
  data_classes: "Media essence, derivatives, captions, transcripts, replay access records",
  systems: "Media asset service, storage (primary, replica, backup), search index, CDN cache",
  organizations: "Beacon Retail Group (1 asset), Helix Manufacturing (1 asset), Apex Systems (1 asset — blocked)",
  regions: "us-west2, europe-west4, us-east4",
  dependencies: "Replay publication, evidence export exp_0091, Trust & Safety case TS-1038",
  holds: "GOV-HOLD-0231 blocks the Apex Systems asset. Deletion for that asset is rejected authoritatively.",
  irreversibility: "Essence deletion is irreversible. Tombstone and audit records survive per the governed contract.",
  blocked: [
    { asset: "AST-2E540 · Apex Systems", reason: "Active legal hold GOV-HOLD-0231", outcome: "Rejected — a hold always overrides deletion scheduling" },
  ],
  eligible: [
    { asset: "AST-7C220 · Beacon Retail Group", reason: "Test retention elapsed", outcome: "Eligible" },
    { asset: "AST-5E447 · Helix Manufacturing", reason: "Platform default 90 days reached", outcome: "Eligible — but an active policy case is open, so it is held for review" },
  ],
  authorization: "Bulk and cross-tenant destructive changes require dual authorization plus typed confirmation.",
  completion: "Success requires authoritative per-system completion and verification. Job acceptance is not completion.",
};

// ─────────────────────────────────────────────────────────────────────────────
// S14-V07 Legal Holds
// ─────────────────────────────────────────────────────────────────────────────
export const LEGAL_HOLDS = [
  {
    hold_id: "GOV-HOLD-0231",
    authority: "External production order · detail restricted to Legal / Compliance",
    basis: "Recorded legal basis reference LB-0231",
    scope: "Apex Systems · asset AST-2E540 · session ses_2211 · Apr 1 – Jun 30, 2026",
    org: "Apex Systems",
    state: "ACTIVE",
    placed_by: "R. Duarte · Legal / Compliance",
    approved_by: "M. Ferreira · Data Governance",
    placed_local: "Jul 28, 2026 · 10:02 BST",
    placed_utc: "09:02 UTC",
    custodians: "Media asset service, storage (primary + nearline), evidence store",
    conflicts: "1 scheduled deletion blocked (RP-22). 1 privacy erasure request scoped over held data (PR-921).",
    collection: "Evidence export exp_0091 · manifest retained",
    review_date: "Oct 28, 2026",
    release_approval: "Dual authorization mandatory",
    release_verification: "Retention and deletion rules are re-resolved after release",
  },
  {
    hold_id: "GOV-HOLD-0118",
    authority: "Internal investigation · Governance",
    basis: "Recorded internal basis reference LB-0118",
    scope: "Meridian Holdings · asset AST-1D983 · session ses_1180",
    org: "Meridian Holdings",
    state: "ACTIVE",
    placed_by: "M. Ferreira · Data Governance",
    approved_by: "R. Duarte · Legal / Compliance",
    placed_local: "Dec 1, 2025 · 09:00 GMT",
    placed_utc: "09:00 UTC",
    custodians: "Media asset service, archive storage, evidence store",
    conflicts: "None currently. Archive placement telemetry is stale, so the custodian list may be incomplete.",
    collection: "Evidence export exp_0044",
    review_date: "Sep 1, 2026",
    release_approval: "Dual authorization mandatory",
    release_verification: "Retention rules re-resolved after release",
  },
  {
    hold_id: "GOV-HOLD-0204",
    authority: "External request · detail restricted to Legal / Compliance",
    basis: "Recorded legal basis reference LB-0204",
    scope: "Meridian Holdings · asset AST-1D983 · board records Nov 2025",
    org: "Meridian Holdings",
    state: "ACTIVE",
    placed_by: "R. Duarte · Legal / Compliance",
    approved_by: "M. Ferreira · Data Governance",
    placed_local: "Aug 4, 2026 · 09:15 BST",
    placed_utc: "08:15 UTC",
    custodians: "Media asset service, archive storage",
    conflicts: "Overlaps GOV-HOLD-0118 on the same asset. Overlap is recorded rather than merged.",
    collection: "Evidence export exp_0044 (shared)",
    review_date: "Nov 4, 2026",
    release_approval: "Dual authorization mandatory",
    release_verification: "Retention rules re-resolved after release",
  },
  {
    hold_id: "GOV-HOLD-0240",
    authority: "Internal dispute · Governance",
    basis: "Recorded internal basis reference LB-0240",
    scope: "City of Northfield · asset AST-9A014",
    org: "City of Northfield",
    state: "RELEASE_PENDING",
    placed_by: "M. Ferreira · Data Governance",
    approved_by: "R. Duarte · Legal / Compliance",
    placed_local: "May 2, 2026 · 11:00 BST",
    placed_utc: "10:00 UTC",
    custodians: "Media asset service, storage",
    conflicts: "Release would expose the asset to the 6-year regulatory retention rule, which then governs.",
    collection: "No export taken",
    review_date: "Release review in progress",
    release_approval: "Second approver outstanding — a single actor cannot release a hold",
    release_verification: "Post-release policy re-evaluation required before the case closes",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V08 Privacy Rights Requests
// ─────────────────────────────────────────────────────────────────────────────
export const PRIVACY_REQUESTS = [
  {
    id: "PR-921",
    type: "Deletion / erasure",
    org: "Apex Systems",
    jurisdiction: "UK",
    state: "IN_PROGRESS",
    timing: "WARNING",
    received_local: "Jul 16, 2026 · 09:12 BST",
    received_utc: "08:12 UTC",
    due_local: "Aug 13, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    identity_verification: "Verified Jul 17, 2026 · proportionate method, accessibility-compliant",
    scope: "One data subject · registration records and appearance in one recorded event",
    sources: [
      { system: "Identity service", action: "Erase registration record", result: "Complete · verified" },
      { system: "Media asset service", action: "Erase appearance in AST-2E540", result: "Blocked · legal hold GOV-HOLD-0231" },
      { system: "Analytics pipeline", action: "Erase playback events", result: "Complete · verified" },
    ],
    holds: "GOV-HOLD-0231 covers part of the requested scope. Constraint is visible before any deletion.",
    fulfillment_evidence: "Per-source completion records; one source outstanding",
    reason_code: "Not applicable yet — the request is open",
    note: "The request cannot close while an authoritative source action is incomplete. If it resolves as partial, that is recorded explicitly with a basis.",
  },
  {
    id: "PR-944",
    type: "Access",
    org: "Grace Network",
    jurisdiction: "US",
    state: "SCOPING",
    timing: "ON_TRACK",
    received_local: "Aug 4, 2026 · 14:20 BST",
    received_utc: "13:20 UTC",
    due_local: "Sep 3, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    identity_verification: "Verified Aug 5, 2026",
    scope: "One data subject · all processing across Grace Network events",
    sources: [
      { system: "Identity service", action: "Collect registration records", result: "In progress" },
      { system: "Media asset service", action: "Identify appearances", result: "Not started" },
    ],
    holds: "None",
    fulfillment_evidence: "Response package will be access-controlled and time-limited",
    reason_code: "—",
    note: "Cross-Organization data is excluded unless the verified request scope lawfully includes it.",
  },
  {
    id: "PR-902",
    type: "Correction",
    org: "Eastbridge University",
    jurisdiction: "EU",
    state: "FULFILLED",
    timing: "ON_TRACK",
    received_local: "Jun 30, 2026 · 10:00 BST",
    received_utc: "09:00 UTC",
    due_local: "Jul 30, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    identity_verification: "Verified Jun 30, 2026",
    scope: "One data subject · caption misattribution in one replay",
    sources: [{ system: "Media asset service", action: "Correct caption attribution", result: "Complete · verified" }],
    holds: "None",
    fulfillment_evidence: "Correction job evidence and verification record",
    reason_code: "—",
    note: "Closed only after the authoritative source action was verified complete.",
  },
  {
    id: "PR-955",
    type: "Objection / opt-out",
    org: "Beacon Retail Group",
    jurisdiction: "EU",
    state: "REVIEW",
    timing: "ON_TRACK",
    received_local: "Aug 6, 2026 · 08:40 BST",
    received_utc: "07:40 UTC",
    due_local: "Sep 5, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    identity_verification: "Verified Aug 6, 2026",
    scope: "One data subject · objection to engagement analytics processing",
    sources: [{ system: "Analytics pipeline", action: "Apply processing restriction", result: "Pending applicability review" }],
    holds: "None",
    fulfillment_evidence: "Basis recorded; applicability evaluation outstanding",
    reason_code: "—",
    note: "Applicability of the right in this jurisdiction is a Legal/Privacy determination, not a UI inference.",
  },
  {
    id: "PR-889",
    type: "Portability",
    org: "City of Northfield",
    jurisdiction: "US",
    state: "PARTIALLY_FULFILLED",
    timing: "ON_TRACK",
    received_local: "Jun 2, 2026 · 09:00 BST",
    received_utc: "08:00 UTC",
    due_local: "Jul 2, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    identity_verification: "Verified Jun 2, 2026",
    scope: "One data subject · structured export of registration and participation records",
    sources: [
      { system: "Identity service", action: "Structured export", result: "Complete · verified" },
      { system: "Media asset service", action: "Export appearance segments", result: "Denied · not portable under the approved export format" },
    ],
    holds: "None",
    fulfillment_evidence: "Export manifest; denial basis recorded",
    reason_code: "PARTIAL_NOT_PORTABLE — controlled reason code with review",
    note: "Recorded explicitly as partially fulfilled with a controlled reason code, never as fulfilled.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V09 DPIA / Privacy Risk Review
// ─────────────────────────────────────────────────────────────────────────────
export const DPIAS = [
  {
    id: "DPIA-204",
    name: "Viewer engagement analytics",
    activity: "PA-118",
    state: "BLOCKED",
    owner: "Privacy Operations · L. Haruna",
    decision_owner: "DPO — separate from the project owner",
    opened: "Jul 8, 2026",
    review_by: "Aug 21, 2026",
    stages: [
      { stage: "Screening", output: "Processing described; triggers met — a DPIA is required.", done: true },
      { stage: "Describe", output: "Purpose, data categories, subjects, flows, systems, recipients, regions and proposed retention recorded.", done: true },
      { stage: "Necessity & proportionality", output: "Purpose limitation acceptable; minimization is not — coarse location is not necessary for the stated purpose.", done: true },
      { stage: "Risk assessment", output: "2 high risks to individuals recorded with likelihood, severity and affected groups.", done: true },
      { stage: "Mitigation", output: "Proposed mitigations do not reduce residual risk below the acceptance threshold.", done: true },
      { stage: "Consultation", output: "DPO consulted. Stakeholder consultation outstanding.", done: false },
      { stage: "Decision", output: "BLOCKED. The governed options are risk reduction, scope change, consultation/escalation, or deferral.", done: true },
      { stage: "Implementation", output: "Not applicable while blocked.", done: false },
      { stage: "Review", output: "Re-opens on a material change to purpose, data, technology, risk, region or legal context.", done: false },
    ],
    risks: [
      { risk: "Re-identification of viewers from coarse location plus device class", likelihood: "Medium", severity: "High", groups: "Registered viewers at small events" },
      { risk: "Purpose creep into individual-level engagement profiling", likelihood: "Medium", severity: "High", groups: "All registered viewers" },
    ],
    mitigations: [
      { mitigation: "Remove coarse location from the collected set", state: "Proposed — not accepted by the project", effect: "Would reduce re-identification risk to Low" },
      { mitigation: "Aggregate at a minimum cohort size before storage", state: "Proposed", effect: "Would reduce profiling risk to Low" },
      { mitigation: "Contractual purpose limitation with Organizations", state: "In place", effect: "Partial — does not address technical re-identification" },
    ],
    conditions: [],
    note: "A blocked DPIA cannot become Approved because a launch date approaches.",
  },
  {
    id: "DPIA-192",
    name: "Caption and translation generation",
    activity: "PA-110",
    state: "APPROVED_WITH_CONDITIONS",
    owner: "Privacy Operations · L. Haruna",
    decision_owner: "DPO",
    opened: "Feb 3, 2026",
    review_by: "Feb 3, 2027",
    stages: [
      { stage: "Screening", output: "DPIA required — third-party processing of broadcast audio.", done: true },
      { stage: "Describe", output: "Flows, provider, regions and retention recorded.", done: true },
      { stage: "Necessity & proportionality", output: "Necessary for a contracted accessibility commitment; minimized to audio derivatives.", done: true },
      { stage: "Risk assessment", output: "1 medium risk recorded.", done: true },
      { stage: "Mitigation", output: "Provider region migration and transcript access controls.", done: true },
      { stage: "Consultation", output: "DPO and Security consulted.", done: true },
      { stage: "Decision", output: "Approved with conditions.", done: true },
      { stage: "Implementation", output: "2 conditions tracked as actions with evidence.", done: false },
      { stage: "Review", output: "Scheduled Feb 3, 2027 or on material change.", done: false },
    ],
    risks: [
      { risk: "Special-category content in transcripts processed outside the preferred region", likelihood: "Medium", severity: "Medium", groups: "Speakers and named individuals" },
    ],
    mitigations: [
      { mitigation: "Migrate provider processing into us-east4", state: "Condition — due Oct 31, 2026", effect: "Removes the cross-region element" },
      { mitigation: "Restrict transcript access to purpose-bound profiles", state: "In place · evidence current", effect: "Reduces exposure" },
    ],
    conditions: [
      { condition: "Provider region migration completed and evidenced", due: "Oct 31, 2026", state: "Open · tracked as EX-104 condition" },
      { condition: "Annual transcript access review evidenced", due: "Feb 3, 2027", state: "Open" },
    ],
    note: "Conditions are tracked actions with evidence, not aspirations.",
  },
  {
    id: "DPIA-188",
    name: "Live contribution, delivery, recording and preservation",
    activity: "PA-101 / PA-104",
    state: "APPROVED",
    owner: "Privacy Operations · L. Haruna",
    decision_owner: "DPO",
    opened: "Nov 2, 2025",
    review_by: "Nov 2, 2026",
    stages: [
      { stage: "Screening", output: "DPIA required — large-scale processing of audio-visual content.", done: true },
      { stage: "Describe", output: "Complete.", done: true },
      { stage: "Necessity & proportionality", output: "Core service function; minimized.", done: true },
      { stage: "Risk assessment", output: "Risks recorded and mitigated.", done: true },
      { stage: "Mitigation", output: "Encryption, access control, retention limits.", done: true },
      { stage: "Consultation", output: "DPO and Legal consulted.", done: true },
      { stage: "Decision", output: "Approved.", done: true },
      { stage: "Implementation", output: "Complete.", done: true },
      { stage: "Review", output: "Scheduled Nov 2, 2026.", done: false },
    ],
    risks: [{ risk: "Unauthorized access to customer media essence", likelihood: "Low", severity: "High", groups: "All broadcast participants" }],
    mitigations: [
      { mitigation: "Protected content-access sessions with audit", state: "In place · evidence current", effect: "Reduces likelihood to Low" },
      { mitigation: "CMEK encryption at rest", state: "In place · evidence current", effect: "Reduces severity of exposure" },
    ],
    conditions: [],
    note: "Approved with no outstanding conditions. Review still scheduled — approval is not permanent.",
  },
  {
    id: "DPIA-210",
    name: "Proposed automated safety detection expansion",
    activity: "PA-124",
    state: "SCREENING",
    owner: "Privacy Operations · L. Haruna",
    decision_owner: "DPO",
    opened: "Aug 5, 2026",
    review_by: "Sep 5, 2026",
    stages: [
      { stage: "Screening", output: "In progress — processing description drafted; trigger evaluation outstanding.", done: false },
      { stage: "Describe", output: "Not started.", done: false },
      { stage: "Necessity & proportionality", output: "Not started.", done: false },
      { stage: "Risk assessment", output: "Not started.", done: false },
      { stage: "Mitigation", output: "Not started.", done: false },
      { stage: "Consultation", output: "Not started.", done: false },
      { stage: "Decision", output: "Not reached.", done: false },
      { stage: "Implementation", output: "Not started.", done: false },
      { stage: "Review", output: "Not scheduled.", done: false },
    ],
    risks: [],
    mitigations: [],
    conditions: [],
    note: "Screening began before design was fixed, which is the point — a DPIA is a risk-management process, not paperwork filed after implementation.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V10 Subprocessors & Third Parties
// ─────────────────────────────────────────────────────────────────────────────
export const SUBPROCESSORS = [
  {
    id: "SUB-002",
    entity: "Cloudline Edge B.V.",
    service: "Content delivery and edge caching",
    purpose: "Deliver authorized playback to viewers and cache segments at the edge",
    data_scope: "Media segments, viewer connection metadata",
    activities: ["PA-101"],
    regions: "europe-west2, europe-west4, us-east4, us-west2",
    role: "Subprocessor",
    state: "APPROVED",
    diligence: "Security, privacy, resilience and legal checks completed Mar 2026",
    contract_status: "Data processing terms executed · effective Jan 1, 2026 – Dec 31, 2027",
    transfer_record: "TR-0041 · approved mechanism recorded for US delivery",
    evidence: "SOC 2 Type II · scope: delivery platform · period Jan–Dec 2025 · issuer Farrow Audit LLP · expires Mar 31, 2027",
    evidence_state: "CURRENT",
    incidents: "None in the last 12 months",
    exit_plan: "Segment cache purge and dependency migration runbook RB-VEN-002",
  },
  {
    id: "SUB-014",
    entity: "Verbit Technologies Ltd.",
    service: "Caption, transcript and translation generation",
    purpose: "Generate committed accessibility features from broadcast audio",
    data_scope: "Broadcast audio derivatives, transcripts (may contain special-category content)",
    activities: ["PA-110"],
    regions: "us-west2",
    role: "Subprocessor",
    state: "APPROVED",
    diligence: "Security and privacy checks completed Feb 2026; region review outstanding",
    contract_status: "Data processing terms executed · effective Feb 1, 2026 – Jan 31, 2028",
    transfer_record: "TR-0058 · approved mechanism recorded",
    evidence: "SOC 2 Type II · scope: transcription platform · period Jul 2025–Jun 2026 · issuer Marlin Assurance · expires Aug 31, 2026",
    evidence_state: "EXPIRING",
    incidents: "1 provider-side availability incident Jul 2026 · corrective actions recorded",
    exit_plan: "Transcript return and deletion within 30 days · runbook RB-VEN-014",
  },
  {
    id: "SUB-021",
    entity: "Northgate Analytics Inc.",
    service: "Engagement measurement processing",
    purpose: "Proposed processor for viewer engagement analytics",
    data_scope: "Playback events, device class, coarse location",
    activities: ["PA-118"],
    regions: "us-east4",
    role: "Processor (proposed)",
    state: "DUE_DILIGENCE",
    diligence: "In progress — security questionnaire returned; privacy review outstanding",
    contract_status: "Draft terms · not executed",
    transfer_record: "Not established",
    evidence: "Vendor-supplied summary only. A marketing claim is not assurance evidence.",
    evidence_state: "MISSING",
    incidents: "Not assessed",
    exit_plan: "Not required until approved",
  },
  {
    id: "SUB-030",
    entity: "Sable Object Storage GmbH",
    service: "Archive storage tier",
    purpose: "Long-term archive of preserved media",
    data_scope: "Media essence and derivatives in archive class",
    activities: ["PA-104"],
    regions: "europe-west4",
    role: "Subprocessor",
    state: "RESTRICTED",
    diligence: "Resilience finding open from the Jun 2026 review",
    contract_status: "Data processing terms executed · effective Apr 1, 2025 – Mar 31, 2027",
    transfer_record: "Not required — EU only",
    evidence: "ISO 27001 certificate · scope: EU storage operations · version 2024 · issuer Kestrel Certification · expires Sep 30, 2026",
    evidence_state: "EXPIRING",
    incidents: "1 durability event Jun 2026 · corrective actions in progress",
    exit_plan: "Archive migration plan drafted · not exercised",
  },
  {
    id: "SUB-041",
    entity: "Pinehill Notification Services",
    service: "Transactional email and notification delivery",
    purpose: "Deliver Organization notices and operator notifications",
    data_scope: "Recipient email addresses, message metadata",
    activities: ["PA-124"],
    regions: "europe-west2",
    role: "Subprocessor",
    state: "EXITING",
    diligence: "Superseded by an in-house replacement",
    contract_status: "Terminating · effective end Oct 31, 2026",
    transfer_record: "Not required",
    evidence: "SOC 2 Type II · scope: messaging platform · period 2025 · issuer Farrow Audit LLP · expired Jun 30, 2026",
    evidence_state: "EXPIRED",
    incidents: "None",
    exit_plan: "Recipient data return and deletion by Nov 30, 2026 · evidence required",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V11 Control Assurance
// ─────────────────────────────────────────────────────────────────────────────
export const CONTROLS = [
  {
    control_id: "CTL-340",
    title: "Customer media storage region enforcement",
    objective: "Keep customer media essence and derivatives inside the Organization's permitted regions",
    owner: "Security Engineering · T. Oyelaran",
    scope: "Media asset service, storage (primary, replica, backup) · all Organizations with a residency commitment",
    control_type: "Preventive",
    implementation: "Storage bucket location policy plus placement telemetry reconciliation",
    test_method: "Quarterly configuration test plus continuous placement telemetry review",
    test_period: "Apr 1 – Jun 30, 2026",
    assurance_state: "PARTIALLY_EFFECTIVE",
    findings: "One non-approved replica observed in us-east4 for one Organization. Preventive control did not stop replica creation.",
    evidence: ["EVD-3301", "EVD-3305"],
    evidence_state: "EXPIRED",
    next_test: "Aug 9, 2026 · reevaluation required because evidence has expired",
    obligations: ["OBL-1002"],
    compensating: "Continuous placement telemetry review (detective) is explicitly identified as compensating, not as a substitute.",
    tester: "T. Oyelaran · method: configuration sampling plus telemetry reconciliation",
  },
  {
    control_id: "CTL-345",
    title: "Cross-border transfer record completeness",
    objective: "Ensure every cross-border transfer has an approved mechanism on record",
    owner: "Legal / Compliance · R. Duarte",
    scope: "Platform · all transfers involving customer personal data",
    control_type: "Detective",
    implementation: "Transfer register reconciled against observed processing locations",
    test_method: "Quarterly register reconciliation",
    test_period: "Apr 1 – Jun 30, 2026",
    assurance_state: "EFFECTIVE",
    findings: "None",
    evidence: ["EVD-3312"],
    evidence_state: "CURRENT",
    next_test: "Oct 15, 2026",
    obligations: ["OBL-1002"],
    compensating: "None required",
    tester: "R. Duarte · method: register-to-telemetry reconciliation",
  },
  {
    control_id: "CTL-402",
    title: "Verified deletion completion",
    objective: "Confirm that authorized deletion actually completed in every affected system",
    owner: "Data Governance · M. Ferreira",
    scope: "Media asset service, storage, search index, CDN cache · all Organizations",
    control_type: "Detective",
    implementation: "Post-deletion verification job with per-system result reporting",
    test_method: "Sampled verification of completed deletion jobs",
    test_period: "Apr 1 – Jun 30, 2026",
    assurance_state: "INEFFECTIVE",
    findings:
      "Verification did not cover the CDN cache layer, so 3 of 20 sampled deletions could not be confirmed complete. An ineffective control against an active material obligation has created a Governance action.",
    evidence: ["EVD-3320"],
    evidence_state: "CURRENT",
    next_test: "Aug 18, 2026",
    obligations: ["OBL-1010"],
    compensating: "Manual cache invalidation checklist, identified explicitly as a compensating control.",
    tester: "S. Adeyinka · method: sampled job verification",
  },
  {
    control_id: "CTL-511",
    title: "Privacy request source discovery and verification",
    objective: "Find every system holding a data subject's records and verify each action",
    owner: "Privacy Operations · L. Haruna",
    scope: "Platform · all supported request types",
    control_type: "Preventive",
    implementation: "Source discovery against the service catalog plus per-source verification",
    test_method: "Test request executed each quarter",
    test_period: "Apr 1 – Jun 30, 2026",
    assurance_state: "EFFECTIVE_WITH_OBSERVATIONS",
    findings: "Discovery is complete, but hold conflicts surface later in the workflow than intended.",
    evidence: ["EVD-3330"],
    evidence_state: "CURRENT",
    next_test: "Oct 1, 2026",
    obligations: ["OBL-1004"],
    compensating: "None required",
    tester: "L. Haruna · method: end-to-end test request",
  },
  {
    control_id: "CTL-520",
    title: "Privacy screening in change intake",
    objective: "Screen new or materially changed processing before design is fixed",
    owner: "Privacy Operations · L. Haruna",
    scope: "Platform · product and change intake",
    control_type: "Preventive",
    implementation: "Mandatory screening gate in the change intake workflow",
    test_method: "Review of change records for screening completion",
    test_period: "Apr 1 – Jun 30, 2026",
    assurance_state: "EFFECTIVE",
    findings: "None",
    evidence: ["EVD-3336"],
    evidence_state: "CURRENT",
    next_test: "Oct 1, 2026",
    obligations: ["OBL-1004"],
    compensating: "None required",
    tester: "L. Haruna · method: change-record review",
  },
  {
    control_id: "CTL-608",
    title: "Accessibility commitment provisioning validation",
    objective: "Validate committed caption and translation provisioning before an event",
    owner: "Platform Operations · V. Okonkwo",
    scope: "Organizations with an accessibility commitment",
    control_type: "Preventive",
    implementation: "Readiness requirement ER-P02/ER-P03 gate before commercial live operation",
    test_method: "Review of readiness evidence across events in the period",
    test_period: "Apr 1 – Jun 30, 2026",
    assurance_state: "EFFECTIVE_WITH_OBSERVATIONS",
    findings: "Gate operates as designed. Provider-side failures produce conditions rather than blocks for recurring services.",
    evidence: ["EVD-3344"],
    evidence_state: "CURRENT",
    next_test: "Oct 1, 2026",
    obligations: ["OBL-1021"],
    compensating: "Exception EX-117 with conditions — the base requirement remains unsatisfied",
    tester: "V. Okonkwo · method: readiness evidence review",
  },
  {
    control_id: "CTL-712",
    title: "Subprocessor assurance evidence currency",
    objective: "Keep current, scoped assurance evidence for every approved subprocessor",
    owner: "GRC · S. Adeyinka",
    scope: "Platform · all approved subprocessors",
    control_type: "Detective",
    implementation: "Evidence register with expiry tracking and renewal actions",
    test_method: "Register review against contract and evidence expiry dates",
    test_period: "Apr 1 – Jun 30, 2026",
    assurance_state: "EFFECTIVE",
    findings: "None in period. Two evidence sets are now expiring and have renewal actions open.",
    evidence: ["EVD-3350"],
    evidence_state: "CURRENT",
    next_test: "Oct 1, 2026",
    obligations: ["OBL-1031"],
    compensating: "None required",
    tester: "S. Adeyinka · method: register review",
  },
  {
    control_id: "CTL-801",
    title: "Privileged access review",
    objective: "Review and certify privileged production access each quarter",
    owner: "GRC · S. Adeyinka",
    scope: "Platform · privileged production roles and standing elevations",
    control_type: "Detective",
    implementation: "Quarterly campaign in Identity & Access with recorded decisions and execution",
    test_method: "Campaign completion and execution evidence review",
    test_period: "Jul 1 – Sep 30, 2026",
    assurance_state: "NOT_TESTED",
    findings: "Q3 campaign is overdue and no execution evidence exists. Not tested is not the same as effective.",
    evidence: [],
    evidence_state: "MISSING",
    next_test: "Overdue since Aug 5, 2026",
    obligations: ["OBL-1015"],
    compensating: "JIT elevation with audit reduces standing exposure, identified explicitly as compensating.",
    tester: "Not assigned",
  },
  {
    control_id: "CTL-905",
    title: "Audience chat moderation controls",
    objective: "Moderate audience-generated content",
    owner: "Not assigned",
    scope: "Not applicable at launch",
    control_type: "Preventive",
    implementation: "Not implemented — the platform has no audience-generated content surface at launch",
    test_method: "Not applicable",
    test_period: "—",
    assurance_state: "NOT_APPLICABLE",
    findings: "Not applicable, with a documented scope basis and approval. This is explicitly not Effective.",
    evidence: ["EVD-3360"],
    evidence_state: "CURRENT",
    next_test: "On introduction of an audience content surface",
    obligations: [],
    compensating: "None",
    tester: "Scope basis approved by the Governance Board Jun 2026",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V12 Exceptions & Risk Acceptance
// ─────────────────────────────────────────────────────────────────────────────
export const EXCEPTIONS = [
  {
    id: "EX-104",
    requirement: "OBL-1002 / POL-RES-002 · caption provider processing region",
    scope: "Grace Network · PA-110 · provider processing in us-west2",
    org: "Grace Network",
    reason:
      "The contracted caption provider has no us-east4 processing region available before its Q4 platform migration. Removing captions would breach an accessibility commitment.",
    risk: "RSK-118 · residual risk assessed Medium after mitigations",
    mitigations: "Approved transfer record TR-0058; transcript access restricted to purpose-bound profiles; provider migration tracked as a condition",
    requester: "V. Okonkwo · Platform Operations",
    approvers: "Governance Board (2 approvers) · requester excluded",
    effective_from: "May 1, 2026 · 00:00 BST",
    expires_at: "Oct 31, 2026 · 23:59 GMT",
    conditions: "Monthly evidence of provider migration progress; immediate notification of any region change",
    renewal: "Requires a fresh review and approval. No silent auto-renewal.",
    state: "ACTIVE",
    post_review: "Required within 30 days of expiry",
    baseline_note: "OBL-1002 remains recorded as unsatisfied for this scope. This is operating-under-exception, not compliant-by-design.",
  },
  {
    id: "EX-117",
    requirement: "OBL-1021 · committed caption provisioning validated before the event",
    scope: "Grace Network · recurring weekly worship service",
    org: "Grace Network",
    reason:
      "The provider connection probe fails intermittently on the provider side. The Organization accepts best-effort captions for this recurring service rather than blocking it.",
    risk: "RSK-155 · residual risk assessed Medium",
    mitigations: "Pre-event manual provider check; post-event caption validation; Organization sign-off on best-effort delivery",
    requester: "M. Okafor · Platform Operations",
    approvers: "Governance Board (2 approvers) · requester excluded",
    effective_from: "Jun 15, 2026 · 00:00 BST",
    expires_at: "Aug 12, 2026 · 23:59 BST",
    conditions: "Weekly reporting of caption outcome; escalation if two consecutive events fail",
    renewal: "Approaching expiry. A renewal needs a fresh review; it will not roll over.",
    state: "ACTIVE",
    post_review: "Required — this is a high-impact class",
    baseline_note: "OBL-1021 remains unsatisfied for this scope while the exception is active.",
  },
  {
    id: "EX-121",
    requirement: "OBL-1015 · quarterly privileged access review",
    scope: "Platform · Q3 2026 campaign · 4 privileged roles",
    org: "All Organizations",
    reason: "The named reviewer for four roles is on extended leave and no delegate has been certified.",
    risk: "RSK-170 · residual risk assessed High",
    mitigations: "JIT elevation remains enforced with audit; standing access unchanged since Q2",
    requester: "S. Adeyinka · GRC",
    approvers: "Awaiting a second approver",
    effective_from: "Proposed Aug 8, 2026",
    expires_at: "Proposed Sep 30, 2026",
    conditions: "Delegate certified within 14 days; campaign completed before Q4 opens",
    renewal: "Not renewable — the campaign must complete",
    state: "UNDER_REVIEW",
    post_review: "Required",
    baseline_note: "The review obligation stays unsatisfied. An exception delays the deadline; it does not satisfy the requirement.",
  },
  {
    id: "EX-098",
    requirement: "OBL-1010 · post-deletion verification coverage",
    scope: "Platform · CDN cache layer",
    org: "All Organizations",
    reason: "Verification coverage for the CDN cache layer was not implemented when the policy took effect.",
    risk: "RSK-204 · residual risk assessed High",
    mitigations: "Manual cache invalidation checklist per deletion batch",
    requester: "M. Ferreira · Data Governance",
    approvers: "Governance Board (2 approvers)",
    effective_from: "Jun 1, 2026 · 00:00 BST",
    expires_at: "Jul 31, 2026 · 23:59 BST",
    conditions: "Coverage implemented before expiry",
    renewal: "Not renewed",
    state: "EXPIRED",
    post_review: "Completed Aug 4, 2026 — coverage was not delivered, so CTL-402 was assessed Ineffective",
    baseline_note: "The exception expired and the requirement remains unsatisfied. Expiry did not make the gap disappear.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V13 Governance Review Board
// ─────────────────────────────────────────────────────────────────────────────
export const BOARD_ITEMS = [
  {
    id: "GRB-2026-081",
    decision_class: "Legal-hold release",
    subject: "GOV-HOLD-0240 · City of Northfield · asset AST-9A014",
    requested_by: "M. Ferreira · Data Governance",
    approvals: "1 of 2 recorded · second approver outstanding",
    due: "Aug 11, 2026 · 17:00 BST · 16:00 UTC",
    timing: "WARNING",
    package: [
      ["Hold scope", "City of Northfield · asset AST-9A014"],
      ["Deletion consequences", "Release exposes the asset to the 6-year regulatory retention rule, which then governs. No immediate deletion follows."],
      ["Authority", "Internal dispute closed; the basis for preservation has ended."],
      ["Release basis", "Dispute resolved Jul 28, 2026 · reference LB-0240-R"],
      ["Downstream retention state", "RP-22 re-resolves to the regulatory 6-year rule on release"],
      ["Post-release verification", "Required before the record closes"],
    ],
    complete: true,
  },
  {
    id: "GRB-2026-084",
    decision_class: "Residency conflict exception",
    subject: "RES-ORG-184 · Northstar Services · non-approved us-east4 replica",
    requested_by: "T. Oyelaran · Security Engineering",
    approvals: "0 of 2 recorded",
    due: "Aug 8, 2026 · 17:00 BST · 16:00 UTC",
    timing: "WARNING",
    package: [
      ["Required vs observed placement", "Required EU/EEA only. Observed replica in us-east4."],
      ["Data classes", "Media essence and derivatives for one Organization"],
      ["Duration requested", "14 days to complete replica removal"],
      ["Transfer / legal analysis", "No approved mechanism covers this replica. Legal analysis attached."],
      ["Remediation plan", "Replica removal by Infrastructure & Delivery, verified by placement telemetry"],
      ["Alternative considered", "Immediate replica deletion — rejected because it would break the durability guarantee mid-restore"],
    ],
    complete: true,
  },
  {
    id: "GRB-2026-086",
    decision_class: "Blocked DPIA / high residual privacy risk",
    subject: "DPIA-204 · viewer engagement analytics",
    requested_by: "L. Haruna · Privacy Operations",
    approvals: "0 of 2 recorded",
    due: "Aug 21, 2026 · 17:00 BST · 16:00 UTC",
    timing: "ON_TRACK",
    package: [
      ["Processing", "Playback events, device class, coarse location for registered viewers"],
      ["Risks", "2 high risks: re-identification and purpose creep"],
      ["Mitigations", "Two proposed mitigations would reduce both risks to Low; the project has not accepted them"],
      ["Consultation status", "DPO consulted. Stakeholder consultation outstanding."],
      ["Decision owner", "DPO — separate from the project owner"],
      ["Governed options", "Risk reduction, scope change, consultation/escalation, or deferral. Launch pressure is not an option."],
    ],
    complete: true,
  },
  {
    id: "GRB-2026-088",
    decision_class: "Material control deficiency",
    subject: "CTL-402 · verified deletion completion assessed Ineffective",
    requested_by: "S. Adeyinka · GRC",
    approvals: "0 of 2 recorded",
    due: "Aug 18, 2026 · 17:00 BST · 16:00 UTC",
    timing: "ON_TRACK",
    package: [
      ["Affected obligations", "OBL-1010 · verified deletion and preservation execution"],
      ["Evidence", "EVD-3320 · 3 of 20 sampled deletions unconfirmed at the CDN cache layer"],
      ["Exposure", "Deletion may be reported complete while cached copies persist"],
      ["Remediation", "Extend verification coverage to the CDN layer · owner Media service"],
      ["Interim controls", "Manual cache invalidation checklist per batch, identified as compensating"],
      ["Prior exception", "EX-098 covered this gap and expired without delivery"],
    ],
    complete: true,
  },
  {
    id: "GRB-2026-090",
    decision_class: "High-impact exception",
    subject: "EX-121 · Q3 privileged access review delay",
    requested_by: "S. Adeyinka · GRC",
    approvals: "0 of 2 recorded",
    due: "Aug 8, 2026 · 17:00 BST · 16:00 UTC",
    timing: "OVERDUE",
    package: [
      ["Requirement", "OBL-1015 · quarterly privileged access review"],
      ["Scope", "4 privileged roles in the Q3 campaign"],
      ["Residual risk", "RSK-170 · High"],
      ["Mitigations", "JIT elevation with audit; standing access unchanged since Q2"],
      ["Expiry", "Proposed Sep 30, 2026 — before Q4 opens"],
      ["Requester", "S. Adeyinka · excluded from approving"],
      ["Affected services / Organizations", "Platform-wide privileged roles; no Organization-specific effect"],
    ],
    complete: true,
  },
  {
    id: "GRB-2026-092",
    decision_class: "Material Organization enforcement review",
    subject: "TS-1047 · Helix Manufacturing capability restriction",
    requested_by: "Automatic · created on material Organization-level enforcement",
    approvals: "Oversight only — not a re-adjudication",
    due: "Aug 14, 2026 · 17:00 BST · 16:00 UTC",
    timing: "ON_TRACK",
    package: [
      ["Trust & Safety decision references", "TS-0994 (final), TS-1021 (final), TS-1047 (proposed)"],
      ["Governance role", "Oversight of process and proportionality, not re-adjudication of the content finding"],
      ["Scope", "2 capabilities restricted; existing media, grantee access and sign-in unchanged"],
      ["Recovery criteria", "Two consecutive events with verified authorization evidence"],
      ["Transparency", "Recorded in the structured reporting model"],
    ],
    complete: true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V14 Evidence & Attestations
// ─────────────────────────────────────────────────────────────────────────────
export const EVIDENCE = [
  {
    id: "EVD-3301",
    evidence_class: "Test result",
    scope: "CTL-340 · storage location policy configuration · Apr–Jun 2026 · platform",
    issuer: "Security Engineering · T. Oyelaran",
    period: "Apr 1 – Jun 30, 2026",
    version: "r3",
    created: "Jul 2, 2026 · 10:12 BST · 09:12 UTC",
    valid_until: "Aug 1, 2026",
    review_by: "Aug 9, 2026",
    integrity: "sha256:9a11…4c02",
    sensitivity: "Internal · GRC and Security profiles",
    status: "EXPIRED",
    linked: "OBL-1002, CTL-340, POL-RES-002",
  },
  {
    id: "EVD-3305",
    evidence_class: "Audit log",
    scope: "CTL-340 · placement telemetry reconciliation extract · Jul 2026",
    issuer: "Audit service (referenced, not editable by Governance)",
    period: "Jul 1 – Jul 31, 2026",
    version: "—",
    created: "Aug 1, 2026 · 02:00 BST · 01:00 UTC",
    valid_until: "Nov 1, 2026",
    review_by: "Oct 1, 2026",
    integrity: "sha256:c740…8811",
    sensitivity: "Internal · GRC profile",
    status: "CURRENT",
    linked: "OBL-1002, CTL-340",
  },
  {
    id: "EVD-3312",
    evidence_class: "Report",
    scope: "CTL-345 · transfer register reconciliation · Apr–Jun 2026",
    issuer: "Legal / Compliance · R. Duarte",
    period: "Apr 1 – Jun 30, 2026",
    version: "v2",
    created: "Jul 8, 2026 · 11:40 BST · 10:40 UTC",
    valid_until: "Oct 15, 2026",
    review_by: "Oct 1, 2026",
    integrity: "sha256:2b04…9f31",
    sensitivity: "Internal · Legal and GRC profiles",
    status: "CURRENT",
    linked: "OBL-1002, CTL-345",
  },
  {
    id: "EVD-3320",
    evidence_class: "Test result",
    scope: "CTL-402 · sampled deletion verification · Apr–Jun 2026",
    issuer: "GRC · S. Adeyinka",
    period: "Apr 1 – Jun 30, 2026",
    version: "r1",
    created: "Jul 10, 2026 · 09:20 BST · 08:20 UTC",
    valid_until: "Oct 10, 2026",
    review_by: "Aug 18, 2026",
    integrity: "sha256:71ea…0044",
    sensitivity: "Internal · GRC profile",
    status: "CURRENT",
    linked: "OBL-1010, CTL-402",
  },
  {
    id: "EVD-3330",
    evidence_class: "Test result",
    scope: "CTL-511 · end-to-end privacy test request · Apr–Jun 2026",
    issuer: "Privacy Operations · L. Haruna",
    period: "Apr 1 – Jun 30, 2026",
    version: "r2",
    created: "Jul 6, 2026 · 11:05 BST · 10:05 UTC",
    valid_until: "Oct 6, 2026",
    review_by: "Oct 1, 2026",
    integrity: "sha256:5c22…b101",
    sensitivity: "Internal · Privacy and GRC profiles",
    status: "CURRENT",
    linked: "OBL-1004, CTL-511",
  },
  {
    id: "EVD-3336",
    evidence_class: "Test result",
    scope: "CTL-520 · change-intake screening completion review · Apr–Jun 2026",
    issuer: "Privacy Operations · L. Haruna",
    period: "Apr 1 – Jun 30, 2026",
    version: "r1",
    created: "Jul 6, 2026 · 11:40 BST · 10:40 UTC",
    valid_until: "Oct 6, 2026",
    review_by: "Oct 1, 2026",
    integrity: "sha256:9d40…22af",
    sensitivity: "Internal · Privacy and GRC profiles",
    status: "CURRENT",
    linked: "OBL-1004, CTL-520",
  },
  {
    id: "EVD-3344",
    evidence_class: "Test result",
    scope: "CTL-608 · readiness evidence review for accessibility commitments · Apr–Jun 2026",
    issuer: "Platform Operations · V. Okonkwo",
    period: "Apr 1 – Jun 30, 2026",
    version: "r1",
    created: "Jul 9, 2026 · 09:30 BST · 08:30 UTC",
    valid_until: "Oct 9, 2026",
    review_by: "Oct 1, 2026",
    integrity: "sha256:6b71…c033",
    sensitivity: "Internal · GRC profile",
    status: "CURRENT",
    linked: "OBL-1021, CTL-608",
  },
  {
    id: "EVD-3350",
    evidence_class: "Certification",
    scope: "SUB-014 · SOC 2 Type II · transcription platform · Jul 2025 – Jun 2026",
    issuer: "Marlin Assurance",
    period: "Jul 1, 2025 – Jun 30, 2026",
    version: "2026 issuance",
    created: "Jul 22, 2026 · 14:00 BST · 13:00 UTC",
    valid_until: "Aug 31, 2026",
    review_by: "Aug 15, 2026",
    integrity: "Publisher signature reference on file",
    sensitivity: "Vendor-confidential · GRC and Legal profiles",
    status: "EXPIRING",
    linked: "OBL-1031, CTL-712, SUB-014",
  },
  {
    id: "EVD-3360",
    evidence_class: "Policy approval",
    scope: "CTL-905 · Not-Applicable scope basis and Board approval",
    issuer: "Governance Board",
    period: "Jun 2026 onward",
    version: "v1",
    created: "Jun 18, 2026 · 15:02 BST · 14:02 UTC",
    valid_until: "On introduction of an audience content surface",
    review_by: "Jun 18, 2027",
    integrity: "sha256:aa90…1120",
    sensitivity: "Internal",
    status: "CURRENT",
    linked: "CTL-905",
  },
  {
    id: "EVD-3372",
    evidence_class: "Deletion proof",
    scope: "RP-40 · test-mode deletion batch · Aug 2026",
    issuer: "Media service (deletion job del_test_0806)",
    period: "Aug 1 – Aug 6, 2026",
    version: "—",
    created: "Aug 6, 2026 · 23:10 BST · 22:10 UTC",
    valid_until: "Aug 6, 2027",
    review_by: "Feb 6, 2027",
    integrity: "sha256:41cd…7702",
    sensitivity: "Internal",
    status: "CURRENT",
    linked: "OBL-1010, RP-40",
  },
  {
    id: "EVD-3380",
    evidence_class: "Access review",
    scope: "AR-2026-Q2 · privileged production roles · Apr–Jun 2026",
    issuer: "Identity & Access (execution evidence)",
    period: "Apr 1 – Jun 30, 2026",
    version: "—",
    created: "Jul 4, 2026 · 10:00 BST · 09:00 UTC",
    valid_until: "Oct 4, 2026",
    review_by: "Sep 30, 2026",
    integrity: "sha256:88a0…3391",
    sensitivity: "Internal · GRC profile",
    status: "CURRENT",
    linked: "OBL-1015, CTL-801",
  },
  {
    id: "EVD-3390",
    evidence_class: "Vendor evidence",
    scope: "SUB-041 · SOC 2 Type II · messaging platform · 2025",
    issuer: "Farrow Audit LLP",
    period: "Jan 1 – Dec 31, 2025",
    version: "2025 issuance",
    created: "Feb 14, 2026 · 12:00 GMT · 12:00 UTC",
    valid_until: "Jun 30, 2026",
    review_by: "Jun 1, 2026",
    integrity: "Publisher signature reference on file",
    sensitivity: "Vendor-confidential",
    status: "EXPIRED",
    linked: "OBL-1031, CTL-712, SUB-041",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V15 Access Review Oversight
// ─────────────────────────────────────────────────────────────────────────────
export const ACCESS_REVIEWS = [
  {
    id: "AR-2026-Q3",
    campaign: "Privileged production roles · Q3 2026",
    scope: "12 roles · 34 identities · production plane",
    systems: "Identity & Access, admin console, media services",
    reviewer: "S. Adeyinka · GRC",
    due_local: "Aug 5, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    timing: "OVERDUE",
    entitlement_evidence: "Snapshot taken Jul 1, 2026 from Identity & Access",
    decisions: "0 of 34 recorded",
    rationale_required: "Required for every privileged retain decision",
    execution: "Not started — Identity & Access executes; Governance observes the verified outcome",
    exceptions: "EX-121 proposed for 4 roles whose reviewer is on extended leave",
    completion: "Not complete. Completion requires all decisions plus authoritative execution evidence.",
    note: "Overdue is a timing state. It never becomes completion, and a reviewer's click is not execution.",
  },
  {
    id: "AR-2026-Q2",
    campaign: "Privileged production roles · Q2 2026",
    scope: "11 roles · 31 identities · production plane",
    systems: "Identity & Access, admin console, media services",
    reviewer: "S. Adeyinka · GRC",
    due_local: "May 5, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    timing: "ON_TRACK",
    entitlement_evidence: "Snapshot taken Apr 1, 2026 · EVD-3380",
    decisions: "31 of 31 recorded · 4 remove, 2 modify, 25 retain",
    rationale_required: "Recorded for all 25 retain decisions",
    execution: "Verified · 4 removals and 2 modifications executed by Identity & Access",
    exceptions: "None",
    completion: "Complete · execution evidence EVD-3380",
    note: "Closed only after Identity & Access reported verified execution.",
  },
  {
    id: "AR-2026-VEN",
    campaign: "Vendor and subprocessor support access · 2026",
    scope: "3 vendors · 8 support identities",
    systems: "Support tooling, media services",
    reviewer: "GRC · unassigned",
    due_local: "Sep 30, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    timing: "ON_TRACK",
    entitlement_evidence: "Snapshot not yet taken",
    decisions: "Not started",
    rationale_required: "Required for privileged retain decisions",
    execution: "Not started",
    exceptions: "None",
    completion: "Not started",
    note: "Scheduled. Nothing is claimed about its outcome.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// S14-V16 Governance History
// ─────────────────────────────────────────────────────────────────────────────
export const HISTORY = [
  { at: "Aug 7, 2026 · 06:40 BST · 05:40 UTC", kind: "residency", actor: "residency-telemetry", text: "Residency conflict RES-ORG-184 detected — non-approved us-east4 replica for Northstar Services. Priority action created; nothing was labelled compliant." },
  { at: "Aug 7, 2026 · 06:14 BST · 05:14 UTC", kind: "hold", actor: "governance-svc", text: "Legal-hold conflict report generated for lawful request LR-2026-0442 over Meridian Holdings." },
  { at: "Aug 6, 2026 · 22:10 BST · 21:10 UTC", kind: "evidence", actor: "media-svc", text: "Deletion proof EVD-3372 recorded for the test-mode batch; per-system completion verified." },
  { at: "Aug 5, 2026 · 09:00 BST · 08:00 UTC", kind: "review", actor: "L. Haruna", text: "DPIA-210 screening opened for the proposed safety detection expansion, before design was fixed." },
  { at: "Aug 4, 2026 · 10:12 BST · 09:12 UTC", kind: "policy", actor: "L. Haruna", text: "POL-PRV-007 v4 draft entered review. v3 remains the effective version — history is not overwritten." },
  { at: "Aug 4, 2026 · 09:40 BST · 08:40 UTC", kind: "exception", actor: "Governance Board", text: "Post-review of expired exception EX-098 completed: coverage was not delivered, so CTL-402 was assessed Ineffective." },
  { at: "Aug 4, 2026 · 09:15 BST · 08:15 UTC", kind: "hold", actor: "R. Duarte", text: "Legal hold GOV-HOLD-0204 placed over Meridian Holdings asset AST-1D983. Overlap with GOV-HOLD-0118 recorded, not merged." },
  { at: "Aug 1, 2026 · 02:00 BST · 01:00 UTC", kind: "evidence", actor: "audit-svc", text: "Placement telemetry extract EVD-3305 referenced as control evidence. Governance consumes Audit records and cannot edit them." },
  { at: "Jul 28, 2026 · 10:02 BST · 09:02 UTC", kind: "hold", actor: "R. Duarte", text: "Legal hold GOV-HOLD-0231 placed over Apex Systems asset AST-2E540; one scheduled deletion blocked." },
  { at: "Jul 10, 2026 · 09:20 BST · 08:20 UTC", kind: "assurance", actor: "S. Adeyinka", text: "CTL-402 assessed INEFFECTIVE for Apr–Jun 2026 — 3 of 20 sampled deletions unconfirmed at the CDN layer." },
  { at: "Jul 2, 2026 · 10:12 BST · 09:12 UTC", kind: "assurance", actor: "T. Oyelaran", text: "CTL-340 assessed PARTIALLY_EFFECTIVE; evidence EVD-3301 has since expired, so the assurance requires reevaluation." },
  { at: "Jun 18, 2026 · 15:02 BST · 14:02 UTC", kind: "approval", actor: "Governance Board", text: "CTL-905 recorded Not Applicable with a documented scope basis and approval. Not Applicable is not Effective." },
  { at: "Jun 1, 2026 · 00:00 BST · May 31, 23:00 UTC", kind: "policy", actor: "Governance Board", text: "POL-RET-004 v6 became effective; v5 marked Superseded." },
  { at: "May 1, 2026 · 00:00 BST · Apr 30, 23:00 UTC", kind: "policy", actor: "Governance Board", text: "POL-EXC-001 v2 became effective, removing the renewal-on-expiry default." },
];
