// Static wireframe data for Media (ZST-WF-SA-MEDIA-001 · screen S06).
//
// §36 of the spec lists the Media Asset Service, Processing Orchestrator, Preserve Service,
// Identity & Access and Audit Service as build blockers, and the platform media API is
// org-scoped today. So this module is the demonstration payload for the interface; the page
// says so on its face rather than presenting these figures as measured platform state.
//
// STD-04 is the rule that shapes every row here: lifecycle, processing, availability, policy,
// preservation, legal hold, provenance and mode are SEPARATE fields. There is deliberately
// no `status` key anywhere in this file.

export const ASSET_KINDS = ["recording", "replay", "clip", "audio", "transcript"];

export const LIFECYCLE_STATES = ["DRAFT", "PROCESSING", "FINALIZING", "READY", "ARCHIVED"];
export const PROCESSING_STATES = ["NOT_REQUIRED", "QUEUED", "RUNNING", "SUCCEEDED", "PARTIAL", "FAILED", "CANCELED"];
export const AVAILABILITY_STATES = ["PREPARING", "AVAILABLE", "DEGRADED", "UNAVAILABLE", "DISABLED"];
export const POLICY_STATES = ["NONE", "RESTRICTED", "QUARANTINED", "REMOVAL_PENDING", "REMOVED"];
export const PRESERVATION_STATES = [
  "FINALIZING",
  "RETAINED",
  "ARCHIVE_PENDING",
  "ARCHIVED",
  "RESTORE_PENDING",
  "DELETION_SCHEDULED",
  "DELETED",
];
export const PROVENANCE_STATES = ["NOT_PRESENT", "PRESENT_UNVERIFIED", "VERIFIED", "VERIFICATION_FAILED", "UNSUPPORTED"];
export const REPLAY_STATES = ["NOT_PROVIDED", "PROCESSING", "SCHEDULED", "AVAILABLE", "RESTRICTED", "EXPIRED", "REMOVED"];

export const REGIONS = [
  { id: "europe-west2", label: "Europe · London" },
  { id: "europe-west4", label: "Europe · Netherlands" },
  { id: "us-east4", label: "US · N. Virginia" },
  { id: "us-west2", label: "US · Los Angeles" },
];

// Registry-governed display maps. The console never invents a label for a state the
// registry did not give it — an unmapped value renders raw rather than as "Unknown".
export const LABEL = {
  NOT_REQUIRED: "Not required",
  NOT_PROVIDED: "Not provided",
  REMOVAL_PENDING: "Removal pending",
  ARCHIVE_PENDING: "Archive pending",
  RESTORE_PENDING: "Restore pending",
  DELETION_SCHEDULED: "Deletion scheduled",
  NOT_PRESENT: "Not present",
  PRESENT_UNVERIFIED: "Present · unverified",
  VERIFICATION_FAILED: "Verification failed",
};
// SCREAMING_SNAKE identifier -> display label, with an override map for the cases where
// sentence-casing is wrong. An unmapped value renders converted rather than as "Unknown":
// coercing a state the registry gave us into Unknown is the exact lie the state-separation
// rules exist to prevent.
//
// Kept local so this module stays a dependency-free payload — it is data, and data importing UI
// formatting helpers is the wrong direction (it also lets `node --test` load it directly).
const toLabel = (v, overrides) =>
  overrides[v] || (v ? v.charAt(0) + v.slice(1).toLowerCase().replace(/_/g, " ") : "—");
export const label = (v) => toLabel(v, LABEL);

export const LIFECYCLE_TONE = {
  DRAFT: "neutral",
  PROCESSING: "info",
  FINALIZING: "info",
  READY: "success",
  ARCHIVED: "neutral",
};
export const PROCESSING_TONE = {
  NOT_REQUIRED: "neutral",
  QUEUED: "info",
  RUNNING: "info",
  SUCCEEDED: "success",
  PARTIAL: "warning",
  FAILED: "danger",
  CANCELED: "neutral",
};
export const AVAILABILITY_TONE = {
  PREPARING: "info",
  AVAILABLE: "success",
  DEGRADED: "warning",
  UNAVAILABLE: "danger",
  DISABLED: "neutral",
};
export const POLICY_TONE = {
  NONE: "neutral",
  RESTRICTED: "warning",
  QUARANTINED: "danger",
  REMOVAL_PENDING: "danger",
  REMOVED: "danger",
};
export const PRESERVATION_TONE = {
  FINALIZING: "info",
  RETAINED: "success",
  ARCHIVE_PENDING: "info",
  ARCHIVED: "neutral",
  RESTORE_PENDING: "info",
  DELETION_SCHEDULED: "warning",
  DELETED: "danger",
};
export const PROVENANCE_TONE = {
  NOT_PRESENT: "neutral",
  PRESENT_UNVERIFIED: "warning",
  VERIFIED: "success",
  VERIFICATION_FAILED: "danger",
  UNSUPPORTED: "neutral",
};
export const REPLAY_TONE = {
  NOT_PROVIDED: "neutral",
  PROCESSING: "info",
  SCHEDULED: "info",
  AVAILABLE: "success",
  RESTRICTED: "warning",
  EXPIRED: "neutral",
  REMOVED: "danger",
};
export const TRACK_TONE = { validated: "success", provisioned: "info", failed: "danger", pending: "warning", absent: "neutral" };

export const ASSETS = [
  {
    asset_id: "AST-8F31A",
    name: "Memorial Service Recording",
    org: "Northstar Services",
    tenant_id: "tnt_northstar_01",
    kind: "recording",
    mode: "LIVE",
    lifecycle: "READY",
    processing: "SUCCEEDED",
    availability: "AVAILABLE",
    policy: "NONE",
    preservation: "RETAINED",
    legal_hold: { active: false, count: 0 },
    provenance: "VERIFIED",
    created_local: "Aug 5, 2026 · 14:02 BST",
    created_utc: "13:02 UTC",
    created_days_ago: 2,
    region: "europe-west2",
    size: "24.8 GB",
    duration: "01:58:12",
    last_activity_local: "Aug 7, 2026 · 06:40 BST",
    last_activity_utc: "05:40 UTC",
    source_event: "EVT-2026-0788 · Memorial Service",
    source_origin: "live_session",
    blockers: [],
    essence: [
      ["Container", "fMP4"],
      ["Source video", "H.264 High · 1080p50 · 12.0 Mbps"],
      ["Source audio", "AAC-LC · stereo · 48 kHz · 192 kbps"],
      ["Encryption context", "CMEK · key ref kms/eu-west2/media-01 (reference only)"],
      ["Content classification", "Customer content · protected essence"],
      ["Storage objects", "3 objects · service-mediated access only"],
    ],
    renditions: [
      { id: "rnd_1080p50", profile: "H.264 High · 1080p50 · 6.0 Mbps", audio: "AAC-LC stereo 128 kbps", packaging: "LL-HLS v3", validation: "Pass · validator 4.2 · Aug 5 13:44 UTC", availability: "AVAILABLE", lineage: "From AST-8F31A · job job_7712" },
      { id: "rnd_720p50", profile: "H.264 Main · 720p50 · 3.2 Mbps", audio: "AAC-LC stereo 128 kbps", packaging: "LL-HLS v3", validation: "Pass · validator 4.2 · Aug 5 13:44 UTC", availability: "AVAILABLE", lineage: "From AST-8F31A · job job_7712" },
      { id: "rnd_540p25", profile: "H.264 Main · 540p25 · 1.4 Mbps", audio: "AAC-LC stereo 96 kbps", packaging: "LL-HLS v3", validation: "Pass · validator 4.2 · Aug 5 13:44 UTC", availability: "AVAILABLE", lineage: "From AST-8F31A · job job_7712" },
    ],
    tracks: [
      { cls: "Audio", language: "en-GB", detail: "Primary · stereo · AAC-LC · default", state: "validated", processing: "SUCCEEDED", automated: false },
      { cls: "Captions", language: "en-GB", detail: "WebVTT · provider Verbit · timing validated", state: "validated", processing: "SUCCEEDED", automated: true },
      { cls: "Translation", language: "en-GB → cy-GB", detail: "Provider Verbit · model v3 · no QA artifact", state: "provisioned", processing: "SUCCEEDED", automated: true },
      { cls: "Transcript", language: "en-GB", detail: "Aligned · generated from captions", state: "validated", processing: "SUCCEEDED", automated: true },
      { cls: "Audio description", language: "en-GB", detail: "Not provided for this asset", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Timed metadata", language: "—", detail: "Chapter markers · schema zst.chapters/1", state: "validated", processing: "SUCCEEDED", automated: false },
    ],
    playback: [
      ["Playback path", "Service-mediated · scoped expiring URL"],
      ["Manifest", "LL-HLS v3 · 3 renditions advertised"],
      ["DRM / access binding", "Token-bound · reference only, no key material shown"],
      ["Error telemetry (7d)", "0.12% playback error rate · 4,102 sessions"],
      ["Rendition selection", "1080p50 61% · 720p50 29% · 540p25 10%"],
    ],
    recording: {
      capture_source: "EVT-2026-0788 · session ses_41ab · output out_primary",
      state: "Finalized",
      start_local: "Aug 5, 2026 · 14:02 BST",
      start_utc: "13:02 UTC",
      end_local: "Aug 5, 2026 · 16:00 BST",
      end_utc: "15:00 UTC",
      continuity: "No gaps detected",
      finalization: "Complete · Aug 5, 2026 · 16:14 BST · 15:14 UTC",
      resulting_asset: "AST-8F31A",
      storage_target: "eu-west2 · standard class",
      retention: "7 years · Organization governed policy",
      failures: "None",
    },
    replay: {
      state: "AVAILABLE",
      window: "Aug 6, 2026 · 09:00 BST · 08:00 UTC → indefinite",
      access_policy: "Invite only · registration enforced on the media",
      note: "Replay availability is independent of recording finalization and of policy state.",
    },
    access: [
      ["Effective access policy", "Invite only · registered grantees"],
      ["Grantees with access", "1,102 registered of 1,284 invited"],
      ["Passphrase", "Configured — gates media, not the page"],
      ["Protected essence", "Requires a content-access session"],
      ["Security references", "sec_pol_41c9 (reference only)"],
    ],
    preservation_detail: {
      effective_policy: "ret_pol_northstar_7y",
      policy_source: "Organization-specific governed policy",
      duration: "7 years from recording end",
      next_evaluation: "Aug 5, 2027 · 15:00 UTC",
      state: "RETAINED",
      storage_locations: "eu-west2 · standard class",
      archive_state: "Not applicable",
      deletion_eligibility: "Not eligible · retention_active",
      deletion_schedule: "—",
      legal_hold: "None",
      dependencies: "Replay publication, audience registration records",
    },
    policy_detail: {
      state: "NONE",
      decision_ref: "—",
      authority: "—",
      effective_from: "—",
      expiry: "—",
      execution: "No active media restriction known to the enforcement service.",
    },
    provenance_detail: {
      presence: "Content Credential manifest present",
      verification: "VERIFIED",
      spec: "C2PA 2.4 · profile live-video",
      signer: "ZoikoStream Capture Service (platform trust anchor)",
      binding: "Validated · hard binding over fMP4 segments",
      ingredients: "1 ingredient · live capture output",
      redactions: "None",
      validated_at: "Aug 5, 2026 · 15:20 UTC · verifier 2.4.1",
      warnings: "None",
    },
    history: [
      { at: "Aug 7, 2026 · 06:40 BST · 05:40 UTC", kind: "system", text: "Availability reevaluated — AVAILABLE (all required renditions validated)." },
      { at: "Aug 6, 2026 · 08:00 BST · 07:00 UTC", kind: "system", text: "Replay became AVAILABLE under the event's access policy." },
      { at: "Aug 5, 2026 · 15:20 BST · 14:20 UTC", kind: "provenance", text: "Content Credential verified · verifier 2.4.1." },
      { at: "Aug 5, 2026 · 15:14 BST · 14:14 UTC", kind: "recording", text: "Recording finalized; asset AST-8F31A created." },
    ],
  },
  {
    asset_id: "AST-6C102",
    name: "University Commencement",
    org: "Eastbridge University",
    tenant_id: "tnt_eastbridge_04",
    kind: "replay",
    mode: "LIVE",
    lifecycle: "READY",
    processing: "SUCCEEDED",
    availability: "AVAILABLE",
    policy: "NONE",
    preservation: "RETAINED",
    legal_hold: { active: false, count: 0 },
    provenance: "PRESENT_UNVERIFIED",
    created_local: "Jul 31, 2026 · 11:00 BST",
    created_utc: "10:00 UTC",
    created_days_ago: 7,
    region: "europe-west2",
    size: "18.2 GB",
    duration: "02:31:44",
    last_activity_local: "Aug 6, 2026 · 21:12 BST",
    last_activity_utc: "20:12 UTC",
    source_event: "EVT-2026-0701 · Summer Commencement",
    source_origin: "live_session",
    blockers: [],
    essence: [
      ["Container", "fMP4"],
      ["Source video", "H.264 High · 1080p50 · 10.0 Mbps"],
      ["Source audio", "AAC-LC · stereo · 48 kHz · 192 kbps"],
      ["Encryption context", "CMEK · key ref kms/eu-west2/media-01 (reference only)"],
      ["Content classification", "Customer content · protected essence"],
      ["Storage objects", "4 objects · service-mediated access only"],
    ],
    renditions: [
      { id: "rnd_1080p50", profile: "H.264 High · 1080p50 · 6.0 Mbps", audio: "AAC-LC stereo 128 kbps", packaging: "HLS v3 + DASH", validation: "Pass · validator 4.2 · Jul 31 12:40 UTC", availability: "AVAILABLE", lineage: "From AST-6C102 · job job_7502" },
      { id: "rnd_720p50", profile: "H.264 Main · 720p50 · 3.2 Mbps", audio: "AAC-LC stereo 128 kbps", packaging: "HLS v3 + DASH", validation: "Pass · validator 4.2 · Jul 31 12:40 UTC", availability: "AVAILABLE", lineage: "From AST-6C102 · job job_7502" },
    ],
    tracks: [
      { cls: "Audio", language: "en-GB", detail: "Primary · stereo · AAC-LC · default", state: "validated", processing: "SUCCEEDED", automated: false },
      { cls: "Captions", language: "en-GB", detail: "WebVTT · timing validated", state: "validated", processing: "SUCCEEDED", automated: true },
      { cls: "Translation", language: "en-GB → fr-FR, es-ES", detail: "Provider Verbit · model v3", state: "validated", processing: "SUCCEEDED", automated: true },
      { cls: "Transcript", language: "en-GB", detail: "Aligned", state: "validated", processing: "SUCCEEDED", automated: true },
      { cls: "Audio description", language: "en-GB", detail: "Provisioned · synchronization not yet validated", state: "provisioned", processing: "SUCCEEDED", automated: false },
      { cls: "Timed metadata", language: "—", detail: "Chapter markers · schema zst.chapters/1", state: "validated", processing: "SUCCEEDED", automated: false },
    ],
    playback: [
      ["Playback path", "Service-mediated · scoped expiring URL"],
      ["Manifest", "HLS v3 + DASH · 2 renditions advertised"],
      ["DRM / access binding", "Token-bound · reference only"],
      ["Error telemetry (7d)", "0.08% playback error rate · 9,880 sessions"],
      ["Rendition selection", "1080p50 72% · 720p50 28%"],
    ],
    recording: {
      capture_source: "EVT-2026-0701 · session ses_3a02 · output out_primary",
      state: "Finalized",
      start_local: "Jul 31, 2026 · 11:00 BST",
      start_utc: "10:00 UTC",
      end_local: "Jul 31, 2026 · 13:31 BST",
      end_utc: "12:31 UTC",
      continuity: "One known discontinuity · 00:41:12–00:41:19 (7s)",
      finalization: "Complete · Jul 31, 2026 · 13:48 BST · 12:48 UTC",
      resulting_asset: "AST-6C102",
      storage_target: "eu-west2 · standard class",
      retention: "3 years · plan entitlement",
      failures: "None",
    },
    replay: {
      state: "AVAILABLE",
      window: "Aug 1, 2026 · 09:00 BST · 08:00 UTC → Jul 31, 2029",
      access_policy: "Public with registration",
      note: "Replay availability is independent of recording finalization and of policy state.",
    },
    access: [
      ["Effective access policy", "Public with registration"],
      ["Grantees with access", "Open · registration recorded per viewer"],
      ["Passphrase", "Not configured"],
      ["Protected essence", "Requires a content-access session"],
      ["Security references", "sec_pol_3390 (reference only)"],
    ],
    preservation_detail: {
      effective_policy: "ret_pol_plan_business_3y",
      policy_source: "Plan / service entitlement",
      duration: "3 years from recording end",
      next_evaluation: "Jul 31, 2029 · 12:31 UTC",
      state: "RETAINED",
      storage_locations: "eu-west2 · standard class",
      archive_state: "Not applicable",
      deletion_eligibility: "Not eligible · retention_active",
      deletion_schedule: "—",
      legal_hold: "None",
      dependencies: "Replay publication",
    },
    policy_detail: {
      state: "NONE",
      decision_ref: "—",
      authority: "—",
      effective_from: "—",
      expiry: "—",
      execution: "No active media restriction known to the enforcement service.",
    },
    provenance_detail: {
      presence: "Content Credential manifest present",
      verification: "PRESENT_UNVERIFIED",
      spec: "C2PA 2.4 · profile live-video",
      signer: "Not evaluated — verifier has not yet processed this manifest",
      binding: "Not evaluated",
      ingredients: "Not read",
      redactions: "Unknown until validated",
      validated_at: "—",
      warnings: "Verification has not run. Presence of a manifest is not verification.",
    },
    history: [
      { at: "Aug 6, 2026 · 21:12 BST · 20:12 UTC", kind: "track", text: "Audio description track provisioned; synchronization validation pending." },
      { at: "Aug 1, 2026 · 08:00 BST · 07:00 UTC", kind: "system", text: "Replay became AVAILABLE." },
      { at: "Jul 31, 2026 · 12:48 BST · 11:48 UTC", kind: "recording", text: "Recording finalized with one known 7s discontinuity." },
    ],
  },
  {
    asset_id: "AST-4B77C",
    name: "Annual Worship Recording",
    org: "Grace Network",
    tenant_id: "tnt_gracenet_09",
    kind: "recording",
    mode: "LIVE",
    lifecycle: "FINALIZING",
    processing: "RUNNING",
    availability: "PREPARING",
    policy: "NONE",
    preservation: "FINALIZING",
    legal_hold: { active: false, count: 0 },
    provenance: "NOT_PRESENT",
    created_local: "Aug 7, 2026 · 06:00 BST",
    created_utc: "05:00 UTC",
    created_days_ago: 0,
    region: "us-east4",
    size: "9.1 GB",
    duration: "01:12:03",
    last_activity_local: "Aug 7, 2026 · 07:42 BST",
    last_activity_utc: "06:42 UTC",
    source_event: "EVT-2026-0812 · Annual Worship Service",
    source_origin: "live_session",
    blockers: [{ text: "Replay preparation is underway; no authorized playback path exists yet.", tone: "info" }],
    essence: [
      ["Container", "fMP4"],
      ["Source video", "H.264 High · 1080p30 · 8.0 Mbps"],
      ["Source audio", "AAC-LC · stereo · 48 kHz · 192 kbps"],
      ["Encryption context", "CMEK · key ref kms/us-east4/media-02 (reference only)"],
      ["Content classification", "Customer content · protected essence"],
      ["Storage objects", "2 objects · finalization in progress"],
    ],
    renditions: [
      { id: "rnd_1080p30", profile: "H.264 High · 1080p30 · 5.0 Mbps", audio: "AAC-LC stereo 128 kbps", packaging: "HLS v3", validation: "In progress", availability: "PREPARING", lineage: "From AST-4B77C · job job_8120" },
      { id: "rnd_720p30", profile: "H.264 Main · 720p30 · 2.8 Mbps", audio: "AAC-LC stereo 128 kbps", packaging: "HLS v3", validation: "Queued", availability: "PREPARING", lineage: "From AST-4B77C · job job_8120" },
    ],
    tracks: [
      { cls: "Audio", language: "en-US", detail: "Primary · stereo · AAC-LC · default", state: "validated", processing: "SUCCEEDED", automated: false },
      { cls: "Captions", language: "en-US", detail: "Generation running", state: "pending", processing: "RUNNING", automated: true },
      { cls: "Translation", language: "—", detail: "Not committed for this asset", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Transcript", language: "en-US", detail: "Awaiting caption completion", state: "pending", processing: "QUEUED", automated: true },
      { cls: "Audio description", language: "—", detail: "Not provided", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Timed metadata", language: "—", detail: "Not provided", state: "absent", processing: "NOT_REQUIRED", automated: false },
    ],
    playback: [
      ["Playback path", "Not yet available — preparation in progress"],
      ["Manifest", "Not published"],
      ["DRM / access binding", "Token-bound · reference only"],
      ["Error telemetry (7d)", "No sessions yet"],
      ["Rendition selection", "No data"],
    ],
    recording: {
      capture_source: "EVT-2026-0812 · session ses_5c11 · output out_primary",
      state: "Finalizing",
      start_local: "Aug 7, 2026 · 06:00 BST",
      start_utc: "05:00 UTC",
      end_local: "Aug 7, 2026 · 07:12 BST",
      end_utc: "06:12 UTC",
      continuity: "No gaps detected",
      finalization: "In progress · 68% complete",
      resulting_asset: "Pending finalization",
      storage_target: "us-east4 · standard class",
      retention: "1 year · plan entitlement",
      failures: "None",
    },
    replay: {
      state: "PROCESSING",
      window: "Scheduled to open on finalization",
      access_policy: "Public",
      note: "A finalized recording does not automatically imply an audience replay.",
    },
    access: [
      ["Effective access policy", "Public"],
      ["Grantees with access", "Open"],
      ["Passphrase", "Not configured"],
      ["Protected essence", "Requires a content-access session"],
      ["Security references", "sec_pol_5511 (reference only)"],
    ],
    preservation_detail: {
      effective_policy: "ret_pol_plan_business_1y",
      policy_source: "Plan / service entitlement",
      duration: "1 year from recording end",
      next_evaluation: "Aug 7, 2027 · 06:12 UTC",
      state: "FINALIZING",
      storage_locations: "us-east4 · standard class",
      archive_state: "Not applicable",
      deletion_eligibility: "Not eligible · finalization_in_progress",
      deletion_schedule: "—",
      legal_hold: "None",
      dependencies: "Recording finalization, replay preparation",
    },
    policy_detail: {
      state: "NONE",
      decision_ref: "—",
      authority: "—",
      effective_from: "—",
      expiry: "—",
      execution: "No active media restriction known to the enforcement service.",
    },
    provenance_detail: {
      presence: "No provenance manifest present",
      verification: "NOT_PRESENT",
      spec: "—",
      signer: "—",
      binding: "—",
      ingredients: "—",
      redactions: "—",
      validated_at: "—",
      warnings: "Absence of provenance is not evidence of tampering, and its presence would not establish truthfulness.",
    },
    history: [
      { at: "Aug 7, 2026 · 07:42 BST · 06:42 UTC", kind: "processing", text: "Job job_8120 running — 1080p30 rendition transcoding." },
      { at: "Aug 7, 2026 · 07:14 BST · 06:14 UTC", kind: "recording", text: "Recording finalization started." },
      { at: "Aug 7, 2026 · 06:00 BST · 05:00 UTC", kind: "recording", text: "Capture started from session ses_5c11." },
    ],
  },
  {
    asset_id: "AST-2E540",
    name: "Corporate Results Broadcast",
    org: "Apex Systems",
    tenant_id: "tnt_apex_02",
    kind: "replay",
    mode: "LIVE",
    lifecycle: "READY",
    processing: "PARTIAL",
    availability: "DEGRADED",
    policy: "RESTRICTED",
    preservation: "RETAINED",
    legal_hold: { active: true, count: 1 },
    provenance: "VERIFIED",
    created_local: "May 14, 2026 · 15:00 BST",
    created_utc: "14:00 UTC",
    created_days_ago: 85,
    region: "us-east4",
    size: "31.4 GB",
    duration: "01:04:58",
    last_activity_local: "Aug 7, 2026 · 05:11 BST",
    last_activity_utc: "04:11 UTC",
    source_event: "EVT-2026-0402 · Q1 Results Broadcast",
    source_origin: "live_session",
    blockers: [
      { text: "One 1080p rendition failed validation. Replay remains available through healthy renditions.", tone: "warning" },
      { text: "An authoritative Trust & Safety decision restricts distribution. Media cannot lift it.", tone: "danger" },
      { text: "Deletion is blocked by an active legal hold. Media cannot remove or weaken it.", tone: "danger" },
    ],
    essence: [
      ["Container", "fMP4"],
      ["Source video", "H.264 High · 1080p50 · 15.0 Mbps"],
      ["Source audio", "AAC-LC · stereo · 48 kHz · 256 kbps"],
      ["Encryption context", "CMEK · key ref kms/us-east4/media-02 (reference only)"],
      ["Content classification", "Customer content · protected essence · restricted"],
      ["Storage objects", "5 objects · service-mediated access only"],
    ],
    renditions: [
      { id: "rnd_1080p50", profile: "H.264 High · 1080p50 · 6.0 Mbps", audio: "AAC-LC stereo 128 kbps", packaging: "HLS v3 + DASH", validation: "FAIL · validator 4.2 · missing init segment · Aug 7 04:11 UTC", availability: "UNAVAILABLE", lineage: "From AST-2E540 · job job_8004 (attempt 2)" },
      { id: "rnd_720p50", profile: "H.264 Main · 720p50 · 3.2 Mbps", audio: "AAC-LC stereo 128 kbps", packaging: "HLS v3 + DASH", validation: "Pass · validator 4.2 · May 14 14:52 UTC", availability: "AVAILABLE", lineage: "From AST-2E540 · job job_6110" },
      { id: "rnd_540p25", profile: "H.264 Main · 540p25 · 1.4 Mbps", audio: "AAC-LC stereo 96 kbps", packaging: "HLS v3 + DASH", validation: "Pass · validator 4.2 · May 14 14:52 UTC", availability: "AVAILABLE", lineage: "From AST-2E540 · job job_6110" },
    ],
    tracks: [
      { cls: "Audio", language: "en-US", detail: "Primary · stereo · AAC-LC · default", state: "validated", processing: "SUCCEEDED", automated: false },
      { cls: "Captions", language: "en-US", detail: "WebVTT · human-reviewed · QA artifact qa_2201", state: "validated", processing: "SUCCEEDED", automated: false },
      { cls: "Translation", language: "en-US → ja-JP", detail: "Provider Verbit · model v3 · no QA artifact", state: "provisioned", processing: "SUCCEEDED", automated: true },
      { cls: "Transcript", language: "en-US", detail: "Aligned · human-reviewed", state: "validated", processing: "SUCCEEDED", automated: false },
      { cls: "Audio description", language: "—", detail: "Not provided", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Timed metadata", language: "—", detail: "Financial disclosure markers · schema zst.markers/2 · validation failed", state: "failed", processing: "FAILED", automated: false },
    ],
    playback: [
      ["Playback path", "Service-mediated · restricted by policy decision"],
      ["Manifest", "HLS v3 + DASH · 2 of 3 renditions advertised"],
      ["DRM / access binding", "Token-bound · reference only"],
      ["Error telemetry (7d)", "3.4% playback error rate · 212 sessions"],
      ["Rendition selection", "720p50 81% · 540p25 19%"],
    ],
    recording: {
      capture_source: "EVT-2026-0402 · session ses_2211 · output out_primary",
      state: "Finalized",
      start_local: "May 14, 2026 · 15:00 BST",
      start_utc: "14:00 UTC",
      end_local: "May 14, 2026 · 16:05 BST",
      end_utc: "15:05 UTC",
      continuity: "No gaps detected",
      finalization: "Complete · May 14, 2026 · 16:22 BST · 15:22 UTC",
      resulting_asset: "AST-2E540",
      storage_target: "us-east4 · nearline class",
      retention: "10 years · regulatory requirement",
      failures: "None at capture; one derivative failed later revalidation",
    },
    replay: {
      state: "RESTRICTED",
      window: "May 15, 2026 · 09:00 BST · 08:00 UTC → May 14, 2036",
      access_policy: "Invite only · restricted by active Trust & Safety decision",
      note: "Replay exists but an active policy decision restricts access.",
    },
    access: [
      ["Effective access policy", "Invite only · restricted"],
      ["Grantees with access", "388 registered of 412 invited"],
      ["Passphrase", "Configured"],
      ["Protected essence", "Requires a content-access session"],
      ["Security references", "sec_pol_2280, case ref TS-2026-0914"],
    ],
    preservation_detail: {
      effective_policy: "ret_pol_regulatory_10y",
      policy_source: "Regulatory / contractual requirement",
      duration: "10 years from recording end",
      next_evaluation: "May 14, 2036 · 15:05 UTC",
      state: "RETAINED",
      storage_locations: "us-east4 · nearline class",
      archive_state: "Not applicable",
      deletion_eligibility: "Not eligible · legal_hold_active, retention_active",
      deletion_schedule: "—",
      legal_hold: "Active · hold ref GOV-HOLD-0231 (detail is permission-gated)",
      dependencies: "Policy decision TS-2026-0914, legal hold GOV-HOLD-0231, evidence export exp_0091",
    },
    policy_detail: {
      state: "RESTRICTED",
      decision_ref: "TS-2026-0914",
      authority: "Trust & Safety",
      effective_from: "Aug 3, 2026 · 11:20 UTC",
      expiry: "No expiry recorded",
      execution: "Restriction executed on delivery and on cached previews. Media may retry a failed technical execution; it cannot change the decision.",
    },
    provenance_detail: {
      presence: "Content Credential manifest present",
      verification: "VERIFIED",
      spec: "C2PA 2.4 · profile live-video",
      signer: "ZoikoStream Capture Service (platform trust anchor)",
      binding: "Validated · hard binding over fMP4 segments",
      ingredients: "2 ingredients · live capture output, caption overlay",
      redactions: "1 assertion redacted by policy (no implication of tampering)",
      validated_at: "May 14, 2026 · 15:40 UTC · verifier 2.4.1",
      warnings: "None",
    },
    history: [
      { at: "Aug 7, 2026 · 05:11 BST · 04:11 UTC", kind: "rendition", text: "1080p50 rendition revalidation FAILED — missing init segment. Availability moved to DEGRADED." },
      { at: "Aug 3, 2026 · 12:20 BST · 11:20 UTC", kind: "policy", text: "Trust & Safety decision TS-2026-0914 applied — asset RESTRICTED." },
      { at: "Jul 28, 2026 · 10:02 BST · 09:02 UTC", kind: "governance", text: "Legal hold GOV-HOLD-0231 placed. Deletion scheduling blocked." },
      { at: "May 14, 2026 · 15:40 BST · 14:40 UTC", kind: "provenance", text: "Content Credential verified · verifier 2.4.1." },
    ],
  },
  {
    asset_id: "AST-9A014",
    name: "Civic Town Hall",
    org: "City of Northfield",
    tenant_id: "tnt_northfield_11",
    kind: "recording",
    mode: "LIVE",
    lifecycle: "READY",
    processing: "FAILED",
    availability: "UNAVAILABLE",
    policy: "NONE",
    preservation: "RETAINED",
    legal_hold: { active: false, count: 0 },
    provenance: "VERIFICATION_FAILED",
    created_local: "Aug 2, 2026 · 11:00 BST",
    created_utc: "10:00 UTC",
    created_days_ago: 5,
    region: "us-west2",
    size: "7.6 GB",
    duration: "00:58:20",
    last_activity_local: "Aug 7, 2026 · 04:02 BST",
    last_activity_utc: "03:02 UTC",
    source_event: "EVT-2026-0770 · July Town Hall",
    source_origin: "live_session",
    blockers: [
      { text: "Required transcode job failed on three attempts. No usable authorized playback path exists.", tone: "danger" },
      { text: "Content Credential verification failed. This is a verification outcome, not a safety judgement.", tone: "warning" },
    ],
    essence: [
      ["Container", "fMP4"],
      ["Source video", "H.264 Main · 720p30 · 6.0 Mbps"],
      ["Source audio", "AAC-LC · stereo · 48 kHz · 128 kbps"],
      ["Encryption context", "CMEK · key ref kms/us-west2/media-03 (reference only)"],
      ["Content classification", "Customer content · protected essence"],
      ["Storage objects", "2 objects · source essence intact"],
    ],
    renditions: [
      { id: "rnd_720p30", profile: "H.264 Main · 720p30 · 2.8 Mbps", audio: "AAC-LC stereo 128 kbps", packaging: "HLS v3", validation: "Not produced — job failed", availability: "UNAVAILABLE", lineage: "Expected from job job_8091 (3 attempts)" },
      { id: "rnd_480p30", profile: "H.264 Main · 480p30 · 1.2 Mbps", audio: "AAC-LC stereo 96 kbps", packaging: "HLS v3", validation: "Not produced — job failed", availability: "UNAVAILABLE", lineage: "Expected from job job_8091 (3 attempts)" },
    ],
    tracks: [
      { cls: "Audio", language: "en-US", detail: "Primary · stereo · AAC-LC · default", state: "validated", processing: "SUCCEEDED", automated: false },
      { cls: "Captions", language: "en-US", detail: "WebVTT · provisioned, timing validation not run", state: "provisioned", processing: "SUCCEEDED", automated: true },
      { cls: "Translation", language: "en-US → es-US", detail: "Provider test failed", state: "failed", processing: "FAILED", automated: true },
      { cls: "Transcript", language: "en-US", detail: "Aligned", state: "validated", processing: "SUCCEEDED", automated: true },
      { cls: "Audio description", language: "—", detail: "Not provided", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Timed metadata", language: "—", detail: "Agenda markers · schema zst.chapters/1", state: "validated", processing: "SUCCEEDED", automated: false },
    ],
    playback: [
      ["Playback path", "No usable authorized playback path"],
      ["Manifest", "Not published — no validated rendition"],
      ["DRM / access binding", "Token-bound · reference only"],
      ["Error telemetry (7d)", "No sessions — asset is unavailable"],
      ["Rendition selection", "No data"],
    ],
    recording: {
      capture_source: "EVT-2026-0770 · session ses_4780 · output out_primary",
      state: "Finalized",
      start_local: "Aug 2, 2026 · 11:00 BST",
      start_utc: "10:00 UTC",
      end_local: "Aug 2, 2026 · 11:58 BST",
      end_utc: "10:58 UTC",
      continuity: "Two known discontinuities · 00:12:04 (3s), 00:41:55 (11s)",
      finalization: "Complete · Aug 2, 2026 · 12:10 BST · 11:10 UTC",
      resulting_asset: "AST-9A014",
      storage_target: "us-west2 · standard class",
      retention: "6 years · regulatory requirement",
      failures: "FAIL_TRANSCODE_TIMEOUT · retryable · source essence is not at risk",
    },
    replay: {
      state: "PROCESSING",
      window: "Blocked pending a validated rendition",
      access_policy: "Public",
      note: "Replay cannot open while no authorized playback path exists.",
    },
    access: [
      ["Effective access policy", "Public"],
      ["Grantees with access", "Open"],
      ["Passphrase", "Not configured"],
      ["Protected essence", "Requires a content-access session"],
      ["Security references", "sec_pol_4790 (reference only)"],
    ],
    preservation_detail: {
      effective_policy: "ret_pol_regulatory_6y",
      policy_source: "Regulatory / contractual requirement",
      duration: "6 years from recording end",
      next_evaluation: "Aug 2, 2032 · 10:58 UTC",
      state: "RETAINED",
      storage_locations: "us-west2 · standard class",
      archive_state: "Not applicable",
      deletion_eligibility: "Not eligible · retention_active",
      deletion_schedule: "—",
      legal_hold: "None",
      dependencies: "Processing job job_8091",
    },
    policy_detail: {
      state: "NONE",
      decision_ref: "—",
      authority: "—",
      effective_from: "—",
      expiry: "—",
      execution: "No active media restriction. A processing failure is not a reason to bypass or invent enforcement.",
    },
    provenance_detail: {
      presence: "Content Credential manifest present",
      verification: "VERIFICATION_FAILED",
      spec: "C2PA 2.4 · profile live-video",
      signer: "ZoikoStream Capture Service (platform trust anchor)",
      binding: "Content binding did not validate over segment range 00:41:50–00:42:10",
      ingredients: "1 ingredient · live capture output",
      redactions: "None",
      validated_at: "Aug 7, 2026 · 03:02 UTC · verifier 2.4.1",
      warnings: "Binding mismatch overlaps a known capture discontinuity. Verification failure is a technical result, not a truth or safety judgement.",
    },
    history: [
      { at: "Aug 7, 2026 · 04:02 BST · 03:02 UTC", kind: "provenance", text: "Content Credential verification FAILED — binding mismatch over a known discontinuity." },
      { at: "Aug 6, 2026 · 22:31 BST · 21:31 UTC", kind: "processing", text: "Job job_8091 attempt 3 FAILED — FAIL_TRANSCODE_TIMEOUT." },
      { at: "Aug 2, 2026 · 12:10 BST · 11:10 UTC", kind: "recording", text: "Recording finalized with two known discontinuities." },
    ],
  },
  {
    asset_id: "AST-1D983",
    name: "Board Broadcast",
    org: "Meridian Holdings",
    tenant_id: "tnt_meridian_07",
    kind: "recording",
    mode: "LIVE",
    lifecycle: "ARCHIVED",
    processing: "NOT_REQUIRED",
    availability: "UNAVAILABLE",
    policy: "NONE",
    preservation: "ARCHIVED",
    legal_hold: { active: true, count: 2 },
    provenance: "VERIFIED",
    created_local: "Nov 12, 2025 · 09:00 GMT",
    created_utc: "09:00 UTC",
    created_days_ago: 268,
    region: "europe-west4",
    size: "12.9 GB",
    duration: "02:10:41",
    last_activity_local: "Aug 4, 2026 · 09:15 BST",
    last_activity_utc: "08:15 UTC",
    source_event: "EVT-2025-1122 · Annual Board Broadcast",
    source_origin: "live_session",
    blockers: [
      { text: "Asset is archived. Playback requires a governed restore before any content access.", tone: "info" },
      { text: "Deletion is blocked by two active legal holds. Media cannot remove or weaken them.", tone: "danger" },
    ],
    essence: [
      ["Container", "fMP4"],
      ["Source video", "H.264 High · 1080p25 · 10.0 Mbps"],
      ["Source audio", "AAC-LC · stereo · 48 kHz · 192 kbps"],
      ["Encryption context", "CMEK · key ref kms/eu-west4/media-04 (reference only)"],
      ["Content classification", "Customer content · protected essence · archived"],
      ["Storage objects", "1 archive object · restore required"],
    ],
    renditions: [
      { id: "rnd_1080p25", profile: "H.264 High · 1080p25 · 5.0 Mbps", audio: "AAC-LC stereo 128 kbps", packaging: "HLS v3", validation: "Pass · validator 3.9 · Nov 12 2025 11:20 UTC", availability: "UNAVAILABLE", lineage: "From AST-1D983 · job job_2201 (archived)" },
    ],
    tracks: [
      { cls: "Audio", language: "en-GB", detail: "Primary · stereo · AAC-LC · default", state: "validated", processing: "NOT_REQUIRED", automated: false },
      { cls: "Captions", language: "en-GB", detail: "WebVTT · human-reviewed · QA artifact qa_1109", state: "validated", processing: "NOT_REQUIRED", automated: false },
      { cls: "Translation", language: "—", detail: "Not committed for this asset", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Transcript", language: "en-GB", detail: "Aligned · human-reviewed", state: "validated", processing: "NOT_REQUIRED", automated: false },
      { cls: "Audio description", language: "—", detail: "Not provided", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Timed metadata", language: "—", detail: "Resolution markers · schema zst.markers/2", state: "validated", processing: "NOT_REQUIRED", automated: false },
    ],
    playback: [
      ["Playback path", "None — asset is archived"],
      ["Manifest", "Withdrawn on archive"],
      ["DRM / access binding", "Token-bound · reference only"],
      ["Error telemetry (7d)", "No sessions"],
      ["Rendition selection", "No data"],
    ],
    recording: {
      capture_source: "EVT-2025-1122 · session ses_1180 · output out_primary",
      state: "Finalized",
      start_local: "Nov 12, 2025 · 09:00 GMT",
      start_utc: "09:00 UTC",
      end_local: "Nov 12, 2025 · 11:10 GMT",
      end_utc: "11:10 UTC",
      continuity: "No gaps detected",
      finalization: "Complete · Nov 12, 2025 · 11:26 GMT · 11:26 UTC",
      resulting_asset: "AST-1D983",
      storage_target: "eu-west4 · archive class",
      retention: "Indefinite while legal holds are active",
      failures: "None",
    },
    replay: {
      state: "EXPIRED",
      window: "Nov 13, 2025 → Feb 13, 2026 (ended)",
      access_policy: "Invite only",
      note: "Replay availability window has ended. The asset itself remains preserved.",
    },
    access: [
      ["Effective access policy", "Invite only · archived"],
      ["Grantees with access", "None — replay window ended"],
      ["Passphrase", "Configured"],
      ["Protected essence", "Requires a governed restore, then a content-access session"],
      ["Security references", "sec_pol_1188, holds GOV-HOLD-0118 / GOV-HOLD-0204"],
    ],
    preservation_detail: {
      effective_policy: "ret_pol_hold_override",
      policy_source: "Legal hold or binding preservation order",
      duration: "Indefinite while holds remain active",
      next_evaluation: "On hold release",
      state: "ARCHIVED",
      storage_locations: "eu-west4 · archive class",
      archive_state: "Archived · restore available on governed request",
      deletion_eligibility: "Not eligible · legal_hold_active (×2)",
      deletion_schedule: "—",
      legal_hold: "Active · 2 holds · GOV-HOLD-0118, GOV-HOLD-0204 (detail is permission-gated)",
      dependencies: "Governance holds, evidence export exp_0044",
    },
    policy_detail: {
      state: "NONE",
      decision_ref: "—",
      authority: "—",
      effective_from: "—",
      expiry: "—",
      execution: "No Trust & Safety restriction. Preservation state and policy state are independent axes.",
    },
    provenance_detail: {
      presence: "Content Credential manifest present",
      verification: "VERIFIED",
      spec: "C2PA 2.3 · profile video",
      signer: "ZoikoStream Capture Service (platform trust anchor)",
      binding: "Validated · hard binding over fMP4 segments",
      ingredients: "1 ingredient · live capture output",
      redactions: "None",
      validated_at: "Nov 12, 2025 · 11:40 UTC · verifier 2.3.0",
      warnings: "Validated under an earlier specification version than the current verifier.",
    },
    history: [
      { at: "Aug 4, 2026 · 09:15 BST · 08:15 UTC", kind: "governance", text: "Legal hold GOV-HOLD-0204 placed. Two holds now active." },
      { at: "Feb 13, 2026 · 00:00 GMT · 00:00 UTC", kind: "system", text: "Replay window ended — replay EXPIRED." },
      { at: "Dec 12, 2025 · 02:00 GMT · 02:00 UTC", kind: "preservation", text: "Asset archived to archive storage class." },
    ],
  },
  {
    asset_id: "AST-7C220",
    name: "Product Launch Rehearsal",
    org: "Beacon Retail Group",
    tenant_id: "tnt_beacon_22",
    kind: "clip",
    mode: "TEST",
    lifecycle: "READY",
    processing: "SUCCEEDED",
    availability: "AVAILABLE",
    policy: "NONE",
    preservation: "DELETION_SCHEDULED",
    legal_hold: { active: false, count: 0 },
    provenance: "UNSUPPORTED",
    created_local: "Aug 6, 2026 · 16:20 BST",
    created_utc: "15:20 UTC",
    created_days_ago: 1,
    region: "us-west2",
    size: "1.2 GB",
    duration: "00:08:44",
    last_activity_local: "Aug 6, 2026 · 16:44 BST",
    last_activity_utc: "15:44 UTC",
    source_event: "EVT-2026-0829 · Product Launch Livestream (test mode)",
    source_origin: "test_session",
    blockers: [{ text: "Test-mode asset. Deletion is scheduled under the test retention policy.", tone: "info" }],
    essence: [
      ["Container", "fMP4"],
      ["Source video", "H.264 Main · 720p30 · 4.0 Mbps"],
      ["Source audio", "AAC-LC · stereo · 48 kHz · 128 kbps"],
      ["Encryption context", "CMEK · key ref kms/us-west2/media-03 (reference only)"],
      ["Content classification", "Test-mode content"],
      ["Storage objects", "1 object · service-mediated access only"],
    ],
    renditions: [
      { id: "rnd_720p30", profile: "H.264 Main · 720p30 · 2.8 Mbps", audio: "AAC-LC stereo 128 kbps", packaging: "HLS v3", validation: "Pass · validator 4.2 · Aug 6 15:38 UTC", availability: "AVAILABLE", lineage: "From AST-7C220 · job job_8110" },
    ],
    tracks: [
      { cls: "Audio", language: "en-US", detail: "Primary · stereo · AAC-LC · default", state: "validated", processing: "SUCCEEDED", automated: false },
      { cls: "Captions", language: "en-US", detail: "Automated draft · timing not validated", state: "provisioned", processing: "SUCCEEDED", automated: true },
      { cls: "Translation", language: "—", detail: "Not committed", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Transcript", language: "—", detail: "Not generated", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Audio description", language: "—", detail: "Not provided", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Timed metadata", language: "—", detail: "Not provided", state: "absent", processing: "NOT_REQUIRED", automated: false },
    ],
    playback: [
      ["Playback path", "Service-mediated · test mode"],
      ["Manifest", "HLS v3 · 1 rendition advertised"],
      ["DRM / access binding", "Not applied in test mode"],
      ["Error telemetry (7d)", "No production sessions — test mode"],
      ["Rendition selection", "720p30 100%"],
    ],
    recording: {
      capture_source: "EVT-2026-0829 · session ses_6001 (test) · output out_primary",
      state: "Finalized",
      start_local: "Aug 6, 2026 · 16:20 BST",
      start_utc: "15:20 UTC",
      end_local: "Aug 6, 2026 · 16:29 BST",
      end_utc: "15:29 UTC",
      continuity: "No gaps detected",
      finalization: "Complete · Aug 6, 2026 · 16:36 BST · 15:36 UTC",
      resulting_asset: "AST-7C220",
      storage_target: "us-west2 · standard class",
      retention: "7 days · test-mode default",
      failures: "None",
    },
    replay: {
      state: "NOT_PROVIDED",
      window: "—",
      access_policy: "Test mode — no audience replay is provided",
      note: "No replay is contractually or configurationally provided for test-mode assets.",
    },
    access: [
      ["Effective access policy", "Test mode · organization members only"],
      ["Grantees with access", "4 organization members"],
      ["Passphrase", "Not configured"],
      ["Protected essence", "Requires a content-access session"],
      ["Security references", "sec_pol_6002 (reference only)"],
    ],
    preservation_detail: {
      effective_policy: "ret_pol_test_7d",
      policy_source: "Platform default (test mode)",
      duration: "7 days from recording end",
      next_evaluation: "Aug 13, 2026 · 15:29 UTC",
      state: "DELETION_SCHEDULED",
      storage_locations: "us-west2 · standard class",
      archive_state: "Not applicable",
      deletion_eligibility: "Eligible · test_retention_elapsed",
      deletion_schedule: "Aug 13, 2026 · 16:29 BST · 15:29 UTC",
      legal_hold: "None",
      dependencies: "None",
    },
    policy_detail: {
      state: "NONE",
      decision_ref: "—",
      authority: "—",
      effective_from: "—",
      expiry: "—",
      execution: "No active media restriction known to the enforcement service.",
    },
    provenance_detail: {
      presence: "Provenance collection is not enabled for test-mode capture",
      verification: "UNSUPPORTED",
      spec: "—",
      signer: "—",
      binding: "—",
      ingredients: "—",
      redactions: "—",
      validated_at: "—",
      warnings: "Unsupported means the capability is not enabled here — not that verification failed.",
    },
    history: [
      { at: "Aug 6, 2026 · 16:44 BST · 15:44 UTC", kind: "preservation", text: "Deletion scheduled for Aug 13, 2026 15:29 UTC under the test retention policy." },
      { at: "Aug 6, 2026 · 16:36 BST · 15:36 UTC", kind: "recording", text: "Test recording finalized." },
    ],
  },
  {
    asset_id: "AST-5E447",
    name: "Regional Sales Kickoff Promo",
    org: "Helix Manufacturing",
    tenant_id: "tnt_helix_15",
    kind: "clip",
    mode: "LIVE",
    lifecycle: "PROCESSING",
    processing: "QUEUED",
    availability: "PREPARING",
    policy: "QUARANTINED",
    preservation: "RETAINED",
    legal_hold: { active: false, count: 0 },
    provenance: "NOT_PRESENT",
    created_local: "Aug 7, 2026 · 05:30 BST",
    created_utc: "04:30 UTC",
    created_days_ago: 0,
    region: "europe-west4",
    size: "640 MB",
    duration: "00:03:12",
    last_activity_local: "Aug 7, 2026 · 07:02 BST",
    last_activity_utc: "06:02 UTC",
    source_event: "—",
    source_origin: "upload",
    blockers: [
      { text: "Asset is quarantined by Trust & Safety while a case is active. It is isolated from ordinary delivery.", tone: "danger" },
      { text: "Processing is queued behind the quarantine; no derivative will be published while the case is open.", tone: "warning" },
    ],
    essence: [
      ["Container", "MP4"],
      ["Source video", "H.264 High · 1080p25 · 8.0 Mbps"],
      ["Source audio", "AAC-LC · stereo · 48 kHz · 192 kbps"],
      ["Encryption context", "CMEK · key ref kms/eu-west4/media-04 (reference only)"],
      ["Content classification", "Customer content · protected essence · quarantined"],
      ["Storage objects", "1 object · isolated from delivery"],
    ],
    renditions: [],
    tracks: [
      { cls: "Audio", language: "en-GB", detail: "Primary · stereo · AAC-LC", state: "provisioned", processing: "QUEUED", automated: false },
      { cls: "Captions", language: "—", detail: "Queued behind quarantine", state: "pending", processing: "QUEUED", automated: true },
      { cls: "Translation", language: "—", detail: "Not committed", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Transcript", language: "—", detail: "Not generated", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Audio description", language: "—", detail: "Not provided", state: "absent", processing: "NOT_REQUIRED", automated: false },
      { cls: "Timed metadata", language: "—", detail: "Not provided", state: "absent", processing: "NOT_REQUIRED", automated: false },
    ],
    playback: [
      ["Playback path", "Isolated from ordinary delivery by quarantine"],
      ["Manifest", "Not published"],
      ["DRM / access binding", "Token-bound · reference only"],
      ["Error telemetry (7d)", "No sessions"],
      ["Rendition selection", "No data"],
    ],
    recording: {
      capture_source: "Not applicable — uploaded asset",
      state: "Not applicable",
      start_local: "—",
      start_utc: "—",
      end_local: "—",
      end_utc: "—",
      continuity: "Not applicable",
      finalization: "Not applicable",
      resulting_asset: "AST-5E447",
      storage_target: "eu-west4 · standard class",
      retention: "90 days · platform default",
      failures: "None",
    },
    replay: {
      state: "NOT_PROVIDED",
      window: "—",
      access_policy: "Not applicable — uploaded clip, no event replay",
      note: "No replay is contractually or configurationally provided for this asset.",
    },
    access: [
      ["Effective access policy", "Organization members only"],
      ["Grantees with access", "Suspended while quarantined"],
      ["Passphrase", "Not configured"],
      ["Protected essence", "Requires a content-access session"],
      ["Security references", "case ref TS-2026-0951"],
    ],
    preservation_detail: {
      effective_policy: "ret_pol_platform_90d",
      policy_source: "Platform default",
      duration: "90 days from creation",
      next_evaluation: "Nov 5, 2026 · 04:30 UTC",
      state: "RETAINED",
      storage_locations: "eu-west4 · standard class",
      archive_state: "Not applicable",
      deletion_eligibility: "Not eligible · active_policy_case",
      deletion_schedule: "—",
      legal_hold: "None",
      dependencies: "Policy decision TS-2026-0951",
    },
    policy_detail: {
      state: "QUARANTINED",
      decision_ref: "TS-2026-0951",
      authority: "Trust & Safety",
      effective_from: "Aug 7, 2026 · 06:02 UTC",
      expiry: "While case is active",
      execution: "Isolation executed on delivery, previews and cached thumbnails. Media may open the case; it cannot create, weaken or lift the decision.",
    },
    provenance_detail: {
      presence: "No provenance manifest present",
      verification: "NOT_PRESENT",
      spec: "—",
      signer: "—",
      binding: "—",
      ingredients: "—",
      redactions: "—",
      validated_at: "—",
      warnings: "Absence of provenance is not evidence of tampering.",
    },
    history: [
      { at: "Aug 7, 2026 · 07:02 BST · 06:02 UTC", kind: "policy", text: "Trust & Safety decision TS-2026-0951 applied — asset QUARANTINED." },
      { at: "Aug 7, 2026 · 05:30 BST · 04:30 UTC", kind: "system", text: "Asset created from upload." },
    ],
  },
];

// Processing jobs (§13.1). Cross-asset, so the queue answers "what is failing right now?"
// without opening each asset. `outputs` states expected vs produced — never a bare count.
export const JOBS = [
  {
    job_id: "job_8091",
    asset_id: "AST-9A014",
    asset_name: "Civic Town Hall",
    type: "transcode_ladder",
    region: "us-west2",
    state: "FAILED",
    priority: "Standard",
    created: "Aug 6, 2026 · 21:02 BST · 20:02 UTC",
    started: "Aug 6, 2026 · 21:05 BST · 20:05 UTC",
    completed: "Aug 6, 2026 · 22:31 BST · 21:31 UTC",
    attempt: 3,
    attempts_total: 3,
    failure_code: "FAIL_TRANSCODE_TIMEOUT",
    failure_summary: "Worker exceeded the segment deadline three times in the same region.",
    outputs: "0 of 2 required renditions produced",
    retryable: true,
  },
  {
    job_id: "job_8004",
    asset_id: "AST-2E540",
    asset_name: "Corporate Results Broadcast",
    type: "rendition_revalidate",
    region: "us-east4",
    state: "PARTIAL",
    priority: "High",
    created: "Aug 7, 2026 · 03:40 BST · 02:40 UTC",
    started: "Aug 7, 2026 · 03:41 BST · 02:41 UTC",
    completed: "Aug 7, 2026 · 05:11 BST · 04:11 UTC",
    attempt: 2,
    attempts_total: 2,
    failure_code: "FAIL_MISSING_INIT_SEGMENT",
    failure_summary: "1080p50 init segment absent from the package; 720p50 and 540p25 validated.",
    outputs: "2 of 3 renditions validated",
    retryable: true,
  },
  {
    job_id: "job_8120",
    asset_id: "AST-4B77C",
    asset_name: "Annual Worship Recording",
    type: "transcode_ladder",
    region: "us-east4",
    state: "RUNNING",
    priority: "High",
    created: "Aug 7, 2026 · 07:14 BST · 06:14 UTC",
    started: "Aug 7, 2026 · 07:15 BST · 06:15 UTC",
    completed: "—",
    attempt: 1,
    attempts_total: 1,
    failure_code: "—",
    failure_summary: "—",
    outputs: "0 of 2 renditions produced · in progress",
    retryable: false,
  },
  {
    job_id: "job_8121",
    asset_id: "AST-4B77C",
    asset_name: "Annual Worship Recording",
    type: "caption_generate",
    region: "us-east4",
    state: "RUNNING",
    priority: "Standard",
    created: "Aug 7, 2026 · 07:14 BST · 06:14 UTC",
    started: "Aug 7, 2026 · 07:16 BST · 06:16 UTC",
    completed: "—",
    attempt: 1,
    attempts_total: 1,
    failure_code: "—",
    failure_summary: "—",
    outputs: "0 of 1 caption track produced · in progress",
    retryable: false,
  },
  {
    job_id: "job_8130",
    asset_id: "AST-5E447",
    asset_name: "Regional Sales Kickoff Promo",
    type: "transcode_ladder",
    region: "europe-west4",
    state: "QUEUED",
    priority: "Low",
    created: "Aug 7, 2026 · 05:32 BST · 04:32 UTC",
    started: "—",
    completed: "—",
    attempt: 1,
    attempts_total: 1,
    failure_code: "—",
    failure_summary: "—",
    outputs: "0 of 2 renditions produced · held behind an active policy case",
    retryable: false,
  },
  {
    job_id: "job_8077",
    asset_id: "AST-9A014",
    asset_name: "Civic Town Hall",
    type: "translation_generate",
    region: "us-west2",
    state: "FAILED",
    priority: "Standard",
    created: "Aug 5, 2026 · 10:02 BST · 09:02 UTC",
    started: "Aug 5, 2026 · 10:04 BST · 09:04 UTC",
    completed: "Aug 5, 2026 · 10:19 BST · 09:19 UTC",
    attempt: 2,
    attempts_total: 2,
    failure_code: "FAIL_PROVIDER_REJECTED_LOCALE",
    failure_summary: "Provider rejected the es-US language pair for this source audio profile.",
    outputs: "0 of 1 translation track produced",
    retryable: false,
  },
  {
    job_id: "job_7712",
    asset_id: "AST-8F31A",
    asset_name: "Memorial Service Recording",
    type: "transcode_ladder",
    region: "europe-west2",
    state: "SUCCEEDED",
    priority: "High",
    created: "Aug 5, 2026 · 16:15 BST · 15:15 UTC",
    started: "Aug 5, 2026 · 16:16 BST · 15:16 UTC",
    completed: "Aug 5, 2026 · 16:44 BST · 15:44 UTC",
    attempt: 1,
    attempts_total: 1,
    failure_code: "—",
    failure_summary: "—",
    outputs: "3 of 3 renditions produced and validated",
    retryable: false,
  },
  {
    job_id: "job_8110",
    asset_id: "AST-7C220",
    asset_name: "Product Launch Rehearsal",
    type: "transcode_ladder",
    region: "us-west2",
    state: "SUCCEEDED",
    priority: "Low",
    created: "Aug 6, 2026 · 16:30 BST · 15:30 UTC",
    started: "Aug 6, 2026 · 16:31 BST · 15:31 UTC",
    completed: "Aug 6, 2026 · 16:38 BST · 15:38 UTC",
    attempt: 1,
    attempts_total: 1,
    failure_code: "—",
    failure_summary: "—",
    outputs: "1 of 1 rendition produced and validated",
    retryable: false,
  },
  {
    job_id: "job_8055",
    asset_id: "AST-6C102",
    asset_name: "University Commencement",
    type: "audio_description_validate",
    region: "europe-west2",
    state: "CANCELED",
    priority: "Low",
    created: "Aug 6, 2026 · 20:40 BST · 19:40 UTC",
    started: "Aug 6, 2026 · 20:41 BST · 19:41 UTC",
    completed: "Aug 6, 2026 · 21:12 BST · 20:12 UTC",
    attempt: 1,
    attempts_total: 1,
    failure_code: "—",
    failure_summary: "Canceled through an authorized workflow; existing outputs were not deleted.",
    outputs: "Validation not completed · provisioned track retained",
    retryable: true,
  },
];

export const ORGANIZATIONS = [...new Set(ASSETS.map((a) => a.org))].sort();

export const JOB_TYPES = [...new Set(JOBS.map((j) => j.type))].sort();
