// Static wireframe data for Event Readiness (ZST-WF-SA-ER-001 · screen S04).
//
// There is no readiness policy engine behind this console yet — §34 of the spec lists the
// Readiness Policy Registry, the event state machine and Identity & Access as build
// blockers. So this module is the demonstration payload for the interface, and the page
// labels itself as such rather than presenting these figures as measured platform state.
//
// Timestamps are stored PRE-FORMATTED (local named zone + persistent UTC, per STD-17)
// instead of being derived from Date.now(), so a fixed demo set never drifts into
// "starts in -412h" and the console never invents a relative time it cannot support.

export const GATES = ["NOT_STARTED", "IN_PROGRESS", "PASSED", "CONDITIONAL", "BLOCKED"];

export const GATE_LABEL = {
  NOT_STARTED: "Not started",
  IN_PROGRESS: "In progress",
  PASSED: "Passed",
  CONDITIONAL: "Conditional",
  BLOCKED: "Blocked",
};

// Gate → badge tone. Treatment column of §3.1.
export const GATE_TONE = {
  NOT_STARTED: "neutral",
  IN_PROGRESS: "info",
  PASSED: "success",
  CONDITIONAL: "warning",
  BLOCKED: "danger",
};

// Evidence state → badge tone (§11.1). Anything unsatisfied reads as danger; anything the
// system cannot confidently evaluate reads as warning. Never coerced to success.
export const EVIDENCE_TONE = {
  valid: "success",
  expiring: "warning",
  expired: "danger",
  missing: "danger",
  failed: "danger",
  conflicting: "danger",
  indeterminate: "warning",
  superseded: "neutral",
  not_applicable: "neutral",
};

export const EVIDENCE_LABEL = {
  valid: "Valid",
  expiring: "Expiring",
  expired: "Expired",
  missing: "Missing",
  failed: "Failed",
  conflicting: "Conflicting",
  indeterminate: "Indeterminate",
  superseded: "Superseded",
  not_applicable: "N/A",
};

export const RISK_TONE = { unrepeatable: "danger", high: "warning", medium: "info", standard: "neutral" };

export const RISK_LABEL = { unrepeatable: "Unrepeatable", high: "High", medium: "Medium", standard: "Standard" };

export const REGIONS = [
  { id: "europe-west2", label: "Europe · London" },
  { id: "europe-west4", label: "Europe · Netherlands" },
  { id: "us-east4", label: "US · N. Virginia" },
  { id: "us-west2", label: "US · Los Angeles" },
];

export const SERVICE_TIERS = ["Enterprise", "Business", "Standard"];

export const REQUIREMENT_CATEGORIES = [
  "Contribute",
  "Ingest",
  "Produce",
  "Secure",
  "Deliver",
  "Understand",
  "Preserve",
  "Operations",
];

// §10 requirement catalogue. The console renders the current rule result; it does not own
// applicability logic, so each row carries its class and expected artifact only.
const CATALOG = [
  { id: "ER-C01", stage: "Contribute", label: "Primary ingest path test", mandatory: true, owner: "Platform Operations", artifact: "Recorded test session over the production contribution path" },
  { id: "ER-C02", stage: "Contribute", label: "Independent backup contribution verified", mandatory: true, owner: "Platform Operations", artifact: "Recorded test session over an independent backup path + independence assertion" },
  { id: "ER-I01", stage: "Ingest", label: "Input validation and regional capacity", mandatory: true, owner: "Platform Operations", artifact: "Input validation result + capacity availability at planned ingest region" },
  { id: "ER-P01", stage: "Produce", label: "Production profile validation", mandatory: true, owner: "Media Engineering", artifact: "Approved rendition/packaging configuration validation" },
  { id: "ER-P02", stage: "Produce", label: "Caption provisioning", mandatory: false, owner: "Media Engineering", artifact: "Provider connection test + language mapping" },
  { id: "ER-P03", stage: "Produce", label: "Translation provisioning", mandatory: false, owner: "Media Engineering", artifact: "Provider test result + language mapping" },
  { id: "ER-S01", stage: "Secure", label: "Access configuration", mandatory: false, owner: "Customer Operations", artifact: "Saved access policy + sample grant/token evaluation in test mode" },
  { id: "ER-D01", stage: "Deliver", label: "Delivery readiness", mandatory: true, owner: "Platform Operations", artifact: "Delivery route healthy; required regions reachable" },
  { id: "ER-D02", stage: "Deliver", label: "Pre-warm / reserved capacity", mandatory: false, owner: "Capacity Engineering", artifact: "Pre-warm / reservation completion artifact" },
  { id: "ER-U01", stage: "Understand", label: "Operational telemetry readiness", mandatory: true, owner: "Platform Operations", artifact: "Event telemetry correlation active; identifiers resolved" },
  { id: "ER-R01", stage: "Preserve", label: "Recording target", mandatory: false, owner: "Preserve Operations", artifact: "Storage target + recording profile validation" },
  { id: "ER-R02", stage: "Preserve", label: "Retention policy", mandatory: false, owner: "Data Governance", artifact: "Effective retention policy resolved; no conflict" },
  { id: "ER-O01", stage: "Operations", label: "Primary + backup operator assignment", mandatory: true, owner: "Platform Operations", artifact: "Accepted assignments with reachable status" },
  { id: "ER-O02", stage: "Operations", label: "Runbook", mandatory: true, owner: "Platform Operations", artifact: "Versioned event runbook, linked and approved" },
  { id: "ER-O03", stage: "Operations", label: "Contact tree", mandatory: true, owner: "Customer Operations", artifact: "Organization emergency contacts validated inside the configured window" },
];

// Per-event requirement rows: catalogue + the states that make this event interesting.
// Anything not overridden is valid, which is what a mostly-ready event looks like.
const requirements = (overrides = {}) =>
  CATALOG.map((r) => ({
    state: "valid",
    evidence_id: `ev_${r.id.toLowerCase().replace(/-/g, "")}_8f2a`,
    recorded: "Aug 6, 2026 · 09:41 BST · 08:41 UTC",
    valid_until: "Aug 7, 2026 · 23:59 BST · 22:59 UTC",
    producer: "readiness-runner",
    result: "Pass",
    ...r,
    ...(overrides[r.id] || {}),
  }));

export const EVENTS = [
  {
    id: "evt_9f21a",
    event_id: "EVT-2026-0814",
    name: "Global Memorial Broadcast",
    org: "Northstar Services",
    tenant_id: "tnt_northstar_01",
    region: "europe-west2",
    risk: "unrepeatable",
    tier: "Enterprise",
    gate: "BLOCKED",
    start_local: "Aug 7, 2026 · 14:00 BST",
    start_utc: "13:00 UTC",
    starts_in: "6h 12m",
    within_24h: true,
    days_out: 0,
    completed: false,
    primary_path: "valid",
    backup_path: "missing",
    access: "valid",
    captions: "valid",
    preservation: "valid",
    operator: "L. Chen",
    operator_oncall: "On call",
    backup_operator: "R. Adeyemi",
    backup_operator_oncall: "On call",
    blockers: 1,
    evidence_expiry: "Aug 7 · 22:59 UTC",
    evidence_expiring_soon: false,
    evaluated_at: "Aug 7, 2026 · 07:48 BST · 06:48 UTC",
    policy_version: "readiness-policy/2026.07.3",
    audience_expectation: "Approx. 48,000 concurrent, single occurrence",
    requirements: requirements({
      "ER-C02": {
        state: "missing",
        evidence_id: null,
        recorded: "—",
        valid_until: "—",
        result: "No artifact",
        producer: "—",
      },
      "ER-D02": { state: "expiring", valid_until: "Aug 7, 2026 · 13:30 BST · 12:30 UTC" },
      "ER-P03": { state: "not_applicable", result: "No translation commitment", evidence_id: null, recorded: "—", valid_until: "—", producer: "—" },
    }),
    blocker_details: [
      {
        title: "Independent backup contribution path is not verified",
        requirement: "ER-C02 · Independent backup contribution verified",
        stage: "Contribute",
        why: "No recorded test session exists over a contribution path that is independent of the primary encoder's failure domain.",
        state: "missing",
        required: "Recorded test session over the backup path plus a topology independence assertion",
        owner: "Platform Operations · L. Chen",
        deadline: "Aug 7, 2026 · 12:00 BST · 11:00 UTC",
        actions: ["Request backup path re-test", "Escalate operational resources", "Request dual-authorized single-path exception"],
        runbook: "RB-CONTRIB-014 · Backup contribution verification",
        dependencies: "Customer encoder vendor, secondary ISP circuit",
      },
    ],
    detail: {
      contribution: [
        ["Primary source", "SRT · enc-northstar-a1 · 12 Mbps CBR"],
        ["Primary verified", "Aug 6, 2026 · 21:12 BST · 20:12 UTC"],
        ["Backup source", "Configured · srt://backup.northstar — never verified"],
        ["Path independence", "Unproven — both paths resolve to one uplink"],
      ],
      production: [
        ["Rendition ladder", "1080p50 / 720p50 / 540p25 — validated"],
        ["Packaging", "LL-HLS + DASH · manifest v3"],
        ["Captions", "Live provider connected · en-GB"],
        ["Translation", "Not committed for this event"],
      ],
      security: [
        ["Visibility", "Invite only"],
        ["Grant evaluation", "Sample token evaluated in test mode · pass"],
        ["Passphrase", "Configured — gates media, not the page"],
        ["Restricted grantees", "1,284 invited · 1,102 registered"],
      ],
      delivery: [
        ["Required regions", "Europe · London, Europe · Netherlands"],
        ["Route health", "Healthy at last probe"],
        ["Pre-warm", "Reserved — artifact expires 13:30 BST"],
        ["Expected concurrency", "48,000"],
      ],
      preservation: [
        ["Recording target", "Validated · eu-west2 · standard class"],
        ["Recording profile", "1080p50 archive + audio-only"],
        ["Retention", "7 years · Organization governed policy"],
        ["Replay commitment", "Yes — audience replay after finalization"],
      ],
    },
    people: {
      primary: { name: "L. Chen", role: "Primary operator", detail: "On call · accepted Aug 5" },
      backup: { name: "R. Adeyemi", role: "Backup operator", detail: "On call · accepted Aug 6" },
      runbook: "RB-EVT-0814 · v4 · approved Aug 5, 2026",
      rehearsal: "Completed Aug 6, 2026 · 18:00 BST · 17:00 UTC",
      handover: "Not required — single operating window",
    },
    contacts: [
      { name: "Marcus Hale", role: "Organization event owner", detail: "Validated Aug 4, 2026" },
      { name: "Northstar duty desk", role: "Emergency escalation", detail: "Validated Aug 4, 2026" },
      { name: "V. Okonkwo", role: "ZoikoStream duty manager", detail: "On call" },
    ],
    exceptions: [
      {
        id: "exc_4c81",
        requirement: "ER-C02",
        status: "Draft — not submitted",
        requester: "L. Chen · Platform Operations",
        justification: "—",
        approvers: "Two distinct approvers required; requester excluded",
        window: "—",
        review: "Governance review item is created automatically on approval",
      },
    ],
    history: [
      { at: "Aug 7, 2026 · 07:48 BST · 06:48 UTC", kind: "evaluation", actor: "policy engine", text: "Evaluation completed — gate BLOCKED (policy readiness-policy/2026.07.3, evaluation ev_2f81c4)." },
      { at: "Aug 7, 2026 · 07:47 BST · 06:47 UTC", kind: "requirement", actor: "policy engine", text: "ER-C02 regressed to Missing — prior artifact superseded by configuration change." },
      { at: "Aug 7, 2026 · 06:12 BST · 05:12 UTC", kind: "evidence", actor: "readiness-runner", text: "ER-D02 pre-warm artifact recorded; expires Aug 7 12:30 UTC." },
      { at: "Aug 6, 2026 · 21:12 BST · 20:12 UTC", kind: "evidence", actor: "readiness-runner", text: "ER-C01 primary ingest path test passed over enc-northstar-a1." },
      { at: "Aug 6, 2026 · 20:40 BST · 19:40 UTC", kind: "transition", actor: "event service", text: "Transition to commercial live REJECTED — unrepeatable event with unverified backup path." },
      { at: "Aug 5, 2026 · 11:02 BST · 10:02 UTC", kind: "assignment", actor: "V. Okonkwo", text: "Backup operator set to R. Adeyemi." },
    ],
  },
  {
    id: "evt_71bc4",
    event_id: "EVT-2026-0815",
    name: "University Commencement",
    org: "Eastbridge University",
    tenant_id: "tnt_eastbridge_04",
    region: "europe-west2",
    risk: "unrepeatable",
    tier: "Enterprise",
    gate: "PASSED",
    start_local: "Aug 7, 2026 · 17:30 BST",
    start_utc: "16:30 UTC",
    starts_in: "9h 42m",
    within_24h: true,
    days_out: 0,
    completed: false,
    primary_path: "valid",
    backup_path: "valid",
    access: "valid",
    captions: "valid",
    preservation: "valid",
    operator: "A. Patel",
    operator_oncall: "On call",
    backup_operator: "J. Moreau",
    backup_operator_oncall: "On call",
    blockers: 0,
    evidence_expiry: "Aug 7 · 22:59 UTC",
    evidence_expiring_soon: false,
    evaluated_at: "Aug 7, 2026 · 07:44 BST · 06:44 UTC",
    policy_version: "readiness-policy/2026.07.3",
    audience_expectation: "Approx. 12,500 concurrent, single occurrence",
    requirements: requirements({
      "ER-P03": { state: "valid", result: "Pass · en-GB → fr-FR, es-ES" },
    }),
    blocker_details: [],
    detail: {
      contribution: [
        ["Primary source", "SRT · enc-eastbridge-hall · 10 Mbps CBR"],
        ["Primary verified", "Aug 6, 2026 · 15:30 BST · 14:30 UTC"],
        ["Backup source", "RTMP · independent 5G bonded uplink"],
        ["Path independence", "Asserted and verified — separate uplink and venue rack"],
      ],
      production: [
        ["Rendition ladder", "1080p50 / 720p50 / 540p25 — validated"],
        ["Packaging", "LL-HLS + DASH · manifest v3"],
        ["Captions", "Live provider connected · en-GB"],
        ["Translation", "fr-FR, es-ES · provider test passed"],
      ],
      security: [
        ["Visibility", "Public with registration"],
        ["Grant evaluation", "Sample token evaluated in test mode · pass"],
        ["Passphrase", "Not configured"],
        ["Restricted grantees", "Not applicable"],
      ],
      delivery: [
        ["Required regions", "Europe · London"],
        ["Route health", "Healthy at last probe"],
        ["Pre-warm", "Reserved · artifact valid to Aug 7 22:59 UTC"],
        ["Expected concurrency", "12,500"],
      ],
      preservation: [
        ["Recording target", "Validated · eu-west2 · standard class"],
        ["Recording profile", "1080p50 archive"],
        ["Retention", "3 years · plan entitlement"],
        ["Replay commitment", "Yes — replay scheduled 24h after end"],
      ],
    },
    people: {
      primary: { name: "A. Patel", role: "Primary operator", detail: "On call · accepted Aug 4" },
      backup: { name: "J. Moreau", role: "Backup operator", detail: "On call · accepted Aug 4" },
      runbook: "RB-EVT-0815 · v2 · approved Aug 4, 2026",
      rehearsal: "Completed Aug 6, 2026 · 14:00 BST · 13:00 UTC",
      handover: "Not required — single operating window",
    },
    contacts: [
      { name: "Dr. H. Whitfield", role: "Organization event owner", detail: "Validated Aug 3, 2026" },
      { name: "Eastbridge AV desk", role: "Venue technical contact", detail: "Validated Aug 3, 2026" },
    ],
    exceptions: [],
    history: [
      { at: "Aug 7, 2026 · 07:44 BST · 06:44 UTC", kind: "evaluation", actor: "policy engine", text: "Evaluation completed — gate PASSED (evaluation ev_2f80aa)." },
      { at: "Aug 6, 2026 · 15:30 BST · 14:30 UTC", kind: "evidence", actor: "readiness-runner", text: "ER-C02 backup path test passed with independence assertion." },
      { at: "Aug 6, 2026 · 15:02 BST · 14:02 UTC", kind: "evidence", actor: "readiness-runner", text: "ER-C01 primary ingest path test passed." },
      { at: "Aug 4, 2026 · 09:20 BST · 08:20 UTC", kind: "assignment", actor: "V. Okonkwo", text: "Primary and backup operators assigned and accepted." },
    ],
  },
  {
    id: "evt_5aa02",
    event_id: "EVT-2026-0817",
    name: "Annual Worship Service",
    org: "Grace Network",
    tenant_id: "tnt_gracenet_09",
    region: "us-east4",
    risk: "high",
    tier: "Business",
    gate: "CONDITIONAL",
    start_local: "Aug 8, 2026 · 09:00 BST",
    start_utc: "08:00 UTC",
    starts_in: "1d 1h",
    within_24h: false,
    days_out: 1,
    completed: false,
    primary_path: "valid",
    backup_path: "valid",
    access: "valid",
    captions: "indeterminate",
    preservation: "valid",
    operator: "M. Okafor",
    operator_oncall: "On call",
    backup_operator: "T. Berg",
    backup_operator_oncall: "Off shift until 06:00 UTC",
    blockers: 0,
    evidence_expiry: "Aug 8 · 06:00 UTC",
    evidence_expiring_soon: true,
    evaluated_at: "Aug 7, 2026 · 07:31 BST · 06:31 UTC",
    policy_version: "readiness-policy/2026.07.3",
    audience_expectation: "Approx. 22,000 concurrent, weekly recurrence",
    requirements: requirements({
      "ER-P02": {
        state: "indeterminate",
        result: "Provider connection test returned no result",
        valid_until: "—",
        producer: "caption-provider-probe",
      },
      "ER-O01": { state: "expiring", valid_until: "Aug 8, 2026 · 07:00 BST · 06:00 UTC" },
    }),
    blocker_details: [],
    detail: {
      contribution: [
        ["Primary source", "SRT · enc-grace-main · 8 Mbps CBR"],
        ["Primary verified", "Aug 6, 2026 · 22:05 BST · 21:05 UTC"],
        ["Backup source", "SRT · enc-grace-b · separate venue circuit"],
        ["Path independence", "Asserted and verified"],
      ],
      production: [
        ["Rendition ladder", "1080p30 / 720p30 / 480p30 — validated"],
        ["Packaging", "LL-HLS · manifest v3"],
        ["Captions", "Provider probe returned no result — Indeterminate"],
        ["Translation", "Not committed for this event"],
      ],
      security: [
        ["Visibility", "Public"],
        ["Grant evaluation", "Not applicable — unrestricted"],
        ["Passphrase", "Not configured"],
        ["Restricted grantees", "Not applicable"],
      ],
      delivery: [
        ["Required regions", "US · N. Virginia"],
        ["Route health", "Healthy at last probe"],
        ["Pre-warm", "Not required at this audience threshold"],
        ["Expected concurrency", "22,000"],
      ],
      preservation: [
        ["Recording target", "Validated · us-east4 · standard class"],
        ["Recording profile", "1080p30 archive + audio-only"],
        ["Retention", "1 year · plan entitlement"],
        ["Replay commitment", "Yes — replay available immediately after finalization"],
      ],
    },
    people: {
      primary: { name: "M. Okafor", role: "Primary operator", detail: "On call · accepted Aug 5" },
      backup: { name: "T. Berg", role: "Backup operator", detail: "Accepted — off shift until 06:00 UTC" },
      runbook: "RB-EVT-0817 · v7 · approved Aug 2, 2026",
      rehearsal: "Not required — recurring service",
      handover: "Shift handover at 06:00 UTC",
    },
    contacts: [
      { name: "Pastor R. Nkemelu", role: "Organization event owner", detail: "Validated Aug 1, 2026" },
      { name: "Grace Network media desk", role: "Emergency escalation", detail: "Validated Aug 1, 2026" },
    ],
    exceptions: [
      {
        id: "exc_31a7",
        requirement: "ER-P02",
        status: "Open condition — deadline Aug 8, 06:00 UTC",
        requester: "M. Okafor · Platform Operations",
        justification: "Caption provider probe is failing on the provider side; service commitment is best-effort captions for this recurring service.",
        approvers: "Not required — non-mandatory item tracked as a condition",
        window: "Until Aug 8, 2026 · 07:00 BST · 06:00 UTC",
        review: "Condition lapses to Blocked if unresolved at the deadline",
      },
    ],
    history: [
      { at: "Aug 7, 2026 · 07:31 BST · 06:31 UTC", kind: "evaluation", actor: "policy engine", text: "Evaluation completed — gate CONDITIONAL (evaluation ev_2f7f19)." },
      { at: "Aug 7, 2026 · 07:30 BST · 06:30 UTC", kind: "requirement", actor: "policy engine", text: "ER-P02 became Indeterminate — provider probe returned no result." },
      { at: "Aug 6, 2026 · 22:05 BST · 21:05 UTC", kind: "evidence", actor: "readiness-runner", text: "ER-C01 and ER-C02 contribution tests passed." },
    ],
  },
  {
    id: "evt_2de77",
    event_id: "EVT-2026-0819",
    name: "Corporate Results Broadcast",
    org: "Apex Systems",
    tenant_id: "tnt_apex_02",
    region: "us-east4",
    risk: "medium",
    tier: "Enterprise",
    gate: "IN_PROGRESS",
    start_local: "Aug 8, 2026 · 15:00 BST",
    start_utc: "14:00 UTC",
    starts_in: "1d 7h",
    within_24h: false,
    days_out: 1,
    completed: false,
    primary_path: "valid",
    backup_path: "configured",
    access: "valid",
    captions: "valid",
    preservation: "valid",
    operator: "S. Rao",
    operator_oncall: "On call",
    backup_operator: "Unassigned",
    backup_operator_oncall: "—",
    blockers: 1,
    evidence_expiry: "Aug 8 · 12:00 UTC",
    evidence_expiring_soon: true,
    evaluated_at: "Aug 7, 2026 · 07:20 BST · 06:20 UTC",
    policy_version: "readiness-policy/2026.07.3",
    audience_expectation: "Approx. 6,800 concurrent, quarterly recurrence",
    requirements: requirements({
      "ER-C02": { state: "indeterminate", result: "Configured, test session not yet recorded", evidence_id: null, valid_until: "—" },
      "ER-O01": { state: "missing", result: "Backup operator not assigned", evidence_id: null, recorded: "—", valid_until: "—", producer: "—" },
      "ER-D02": { state: "expiring", valid_until: "Aug 8, 2026 · 13:00 BST · 12:00 UTC" },
    }),
    blocker_details: [
      {
        title: "Backup operator is not assigned",
        requirement: "ER-O01 · Primary + backup operator assignment",
        stage: "Operations",
        why: "The assignment requirement expects two accepted operator assignments with reachable status; only one exists.",
        state: "missing",
        required: "Accepted backup operator assignment with reachable on-call status",
        owner: "Platform Operations · duty manager",
        deadline: "Aug 8, 2026 · 11:00 BST · 10:00 UTC",
        actions: ["Assign backup operator", "Escalate operational resources"],
        runbook: "RB-OPS-002 · Event staffing",
        dependencies: "Duty roster availability",
      },
    ],
    detail: {
      contribution: [
        ["Primary source", "SRT · enc-apex-studio · 15 Mbps CBR"],
        ["Primary verified", "Aug 6, 2026 · 17:44 BST · 16:44 UTC"],
        ["Backup source", "Configured · awaiting recorded test session"],
        ["Path independence", "Asserted from topology — not yet verified by test"],
      ],
      production: [
        ["Rendition ladder", "1080p50 / 720p50 — validated"],
        ["Packaging", "LL-HLS + DASH · manifest v3"],
        ["Captions", "Live provider connected · en-US"],
        ["Translation", "Not committed for this event"],
      ],
      security: [
        ["Visibility", "Invite only"],
        ["Grant evaluation", "Sample token evaluated in test mode · pass"],
        ["Passphrase", "Configured"],
        ["Restricted grantees", "412 invited · 388 registered"],
      ],
      delivery: [
        ["Required regions", "US · N. Virginia, Europe · London"],
        ["Route health", "Healthy at last probe"],
        ["Pre-warm", "Reserved — artifact expires 12:00 UTC"],
        ["Expected concurrency", "6,800"],
      ],
      preservation: [
        ["Recording target", "Validated · us-east4 · nearline class"],
        ["Recording profile", "1080p50 archive"],
        ["Retention", "10 years · regulatory requirement"],
        ["Replay commitment", "Yes — restricted replay for invited grantees"],
      ],
    },
    people: {
      primary: { name: "S. Rao", role: "Primary operator", detail: "On call · accepted Aug 6" },
      backup: { name: "Unassigned", role: "Backup operator", detail: "Mandatory assignment outstanding" },
      runbook: "RB-EVT-0819 · v3 · approved Aug 6, 2026",
      rehearsal: "Scheduled Aug 8, 2026 · 12:00 BST · 11:00 UTC",
      handover: "Not required — single operating window",
    },
    contacts: [
      { name: "K. Lindqvist", role: "Organization event owner", detail: "Validated Aug 5, 2026" },
      { name: "Apex investor relations", role: "Approval authority", detail: "Validated Aug 5, 2026" },
    ],
    exceptions: [],
    history: [
      { at: "Aug 7, 2026 · 07:20 BST · 06:20 UTC", kind: "evaluation", actor: "policy engine", text: "Evaluation completed — gate IN_PROGRESS (evaluation ev_2f7d02)." },
      { at: "Aug 6, 2026 · 17:44 BST · 16:44 UTC", kind: "evidence", actor: "readiness-runner", text: "ER-C01 primary ingest path test passed." },
      { at: "Aug 6, 2026 · 09:15 BST · 08:15 UTC", kind: "assignment", actor: "V. Okonkwo", text: "Primary operator set to S. Rao. Backup operator still outstanding." },
    ],
  },
  {
    id: "evt_88f13",
    event_id: "EVT-2026-0821",
    name: "Civic Town Hall",
    org: "City of Northfield",
    tenant_id: "tnt_northfield_11",
    region: "us-west2",
    risk: "high",
    tier: "Business",
    gate: "PASSED",
    start_local: "Aug 9, 2026 · 11:00 BST",
    start_utc: "10:00 UTC",
    starts_in: "2d 3h",
    within_24h: false,
    days_out: 2,
    completed: false,
    primary_path: "valid",
    backup_path: "valid",
    access: "valid",
    captions: "valid",
    preservation: "valid",
    operator: "J. Davis",
    operator_oncall: "On call",
    backup_operator: "P. Sandoval",
    backup_operator_oncall: "On call",
    blockers: 0,
    evidence_expiry: "Aug 9 · 08:00 UTC",
    evidence_expiring_soon: false,
    evaluated_at: "Aug 7, 2026 · 07:05 BST · 06:05 UTC",
    policy_version: "readiness-policy/2026.07.3",
    audience_expectation: "Approx. 3,200 concurrent, monthly recurrence",
    requirements: requirements(),
    blocker_details: [],
    detail: {
      contribution: [
        ["Primary source", "RTMP · council-chamber-a · 6 Mbps CBR"],
        ["Primary verified", "Aug 6, 2026 · 19:10 BST · 18:10 UTC"],
        ["Backup source", "SRT · mobile bonded uplink"],
        ["Path independence", "Asserted and verified"],
      ],
      production: [
        ["Rendition ladder", "720p30 / 480p30 — validated"],
        ["Packaging", "LL-HLS · manifest v3"],
        ["Captions", "Live provider connected · en-US"],
        ["Translation", "es-US · provider test passed"],
      ],
      security: [
        ["Visibility", "Public"],
        ["Grant evaluation", "Not applicable — unrestricted"],
        ["Passphrase", "Not configured"],
        ["Restricted grantees", "Not applicable"],
      ],
      delivery: [
        ["Required regions", "US · Los Angeles"],
        ["Route health", "Healthy at last probe"],
        ["Pre-warm", "Not required at this audience threshold"],
        ["Expected concurrency", "3,200"],
      ],
      preservation: [
        ["Recording target", "Validated · us-west2 · standard class"],
        ["Recording profile", "720p30 archive + transcript"],
        ["Retention", "6 years · regulatory requirement"],
        ["Replay commitment", "Yes — public replay, indefinite window"],
      ],
    },
    people: {
      primary: { name: "J. Davis", role: "Primary operator", detail: "On call · accepted Aug 3" },
      backup: { name: "P. Sandoval", role: "Backup operator", detail: "On call · accepted Aug 3" },
      runbook: "RB-EVT-0821 · v11 · approved Jul 30, 2026",
      rehearsal: "Not required — recurring session",
      handover: "Not required — single operating window",
    },
    contacts: [
      { name: "City clerk's office", role: "Organization event owner", detail: "Validated Jul 30, 2026" },
      { name: "Northfield IT duty line", role: "Emergency escalation", detail: "Validated Jul 30, 2026" },
    ],
    exceptions: [],
    history: [
      { at: "Aug 7, 2026 · 07:05 BST · 06:05 UTC", kind: "evaluation", actor: "policy engine", text: "Evaluation completed — gate PASSED (evaluation ev_2f7b44)." },
      { at: "Aug 6, 2026 · 19:10 BST · 18:10 UTC", kind: "evidence", actor: "readiness-runner", text: "All Contribute requirements satisfied." },
    ],
  },
  {
    id: "evt_4bd90",
    event_id: "EVT-2026-0824",
    name: "Founders Keynote",
    org: "Meridian Holdings",
    tenant_id: "tnt_meridian_07",
    region: "europe-west4",
    risk: "medium",
    tier: "Enterprise",
    gate: "BLOCKED",
    start_local: "Aug 9, 2026 · 18:00 BST",
    start_utc: "17:00 UTC",
    starts_in: "2d 10h",
    within_24h: false,
    days_out: 2,
    completed: false,
    primary_path: "failed",
    backup_path: "valid",
    access: "expired",
    captions: "valid",
    preservation: "conflicting",
    operator: "N. Ferreira",
    operator_oncall: "On call",
    backup_operator: "D. Kowalski",
    backup_operator_oncall: "On call",
    blockers: 3,
    evidence_expiry: "Aug 7 · 09:00 UTC",
    evidence_expiring_soon: true,
    evaluated_at: "Aug 7, 2026 · 06:58 BST · 05:58 UTC",
    policy_version: "readiness-policy/2026.07.3",
    audience_expectation: "Approx. 15,000 concurrent, annual recurrence",
    requirements: requirements({
      "ER-C01": { state: "failed", result: "Fail · bitrate floor not sustained for 60s" },
      "ER-S01": { state: "expired", valid_until: "Aug 7, 2026 · 10:00 BST · 09:00 UTC" },
      "ER-R02": { state: "conflicting", result: "Organization policy and regulatory requirement disagree" },
    }),
    blocker_details: [
      {
        title: "Primary ingest path test failed",
        requirement: "ER-C01 · Primary ingest path test",
        stage: "Contribute",
        why: "The recorded test session did not sustain the configured bitrate floor for the required 60-second window.",
        state: "failed",
        required: "Passing recorded test session over the production contribution path",
        owner: "Platform Operations · N. Ferreira",
        deadline: "Aug 9, 2026 · 14:00 BST · 13:00 UTC",
        actions: ["Request re-test", "Escalate to Media Infrastructure"],
        runbook: "RB-CONTRIB-003 · Ingest path diagnosis",
        dependencies: "Customer venue network",
      },
      {
        title: "Access configuration evidence has expired",
        requirement: "ER-S01 · Access configuration",
        stage: "Secure",
        why: "The sample grant evaluation is outside its validity window; the saved policy has changed since.",
        state: "expired",
        required: "Fresh sample grant/token evaluation in test mode",
        owner: "Customer Operations",
        deadline: "Aug 9, 2026 · 14:00 BST · 13:00 UTC",
        actions: ["Request re-test", "Open access configuration"],
        runbook: "RB-SEC-009 · Access policy validation",
        dependencies: "Organization access policy owner",
      },
      {
        title: "Retention policy sources disagree",
        requirement: "ER-R02 · Retention policy",
        stage: "Preserve",
        why: "The Organization governed policy resolves to 3 years; a regulatory requirement resolves to 7. Destructive execution is blocked until Governance resolves the conflict.",
        state: "conflicting",
        required: "Single resolved effective retention policy with no conflict",
        owner: "Data Governance",
        deadline: "Aug 9, 2026 · 12:00 BST · 11:00 UTC",
        actions: ["Open Governance record"],
        runbook: "RB-GOV-021 · Retention conflict resolution",
        dependencies: "Governance decision",
      },
    ],
    detail: {
      contribution: [
        ["Primary source", "SRT · enc-meridian-stage · 14 Mbps CBR"],
        ["Primary verified", "Failed Aug 7, 2026 · 05:40 BST · 04:40 UTC"],
        ["Backup source", "SRT · independent venue circuit — verified"],
        ["Path independence", "Asserted and verified"],
      ],
      production: [
        ["Rendition ladder", "1080p50 / 720p50 / 540p25 — validated"],
        ["Packaging", "LL-HLS + DASH · manifest v3"],
        ["Captions", "Live provider connected · en-GB"],
        ["Translation", "Not committed for this event"],
      ],
      security: [
        ["Visibility", "Invite only"],
        ["Grant evaluation", "Expired — last evaluated Aug 6, 10:00 UTC"],
        ["Passphrase", "Configured"],
        ["Restricted grantees", "2,140 invited · 1,902 registered"],
      ],
      delivery: [
        ["Required regions", "Europe · Netherlands, Europe · London"],
        ["Route health", "Healthy at last probe"],
        ["Pre-warm", "Reserved · artifact valid to Aug 9 15:00 UTC"],
        ["Expected concurrency", "15,000"],
      ],
      preservation: [
        ["Recording target", "Validated · eu-west4 · nearline class"],
        ["Recording profile", "1080p50 archive"],
        ["Retention", "Conflict — 3 years (Organization) vs 7 years (regulatory)"],
        ["Replay commitment", "Yes — restricted replay"],
      ],
    },
    people: {
      primary: { name: "N. Ferreira", role: "Primary operator", detail: "On call · accepted Aug 5" },
      backup: { name: "D. Kowalski", role: "Backup operator", detail: "On call · accepted Aug 5" },
      runbook: "RB-EVT-0824 · v2 · approved Aug 5, 2026",
      rehearsal: "Scheduled Aug 9, 2026 · 14:00 BST · 13:00 UTC",
      handover: "Not required — single operating window",
    },
    contacts: [
      { name: "E. Vasquez", role: "Organization event owner", detail: "Validated Aug 2, 2026" },
      { name: "Meridian comms desk", role: "Emergency escalation", detail: "Validated Aug 2, 2026" },
    ],
    exceptions: [],
    history: [
      { at: "Aug 7, 2026 · 06:58 BST · 05:58 UTC", kind: "evaluation", actor: "policy engine", text: "Evaluation completed — gate BLOCKED with 3 mandatory blockers (evaluation ev_2f7a01)." },
      { at: "Aug 7, 2026 · 05:40 BST · 04:40 UTC", kind: "evidence", actor: "readiness-runner", text: "ER-C01 primary ingest path test FAILED — bitrate floor not sustained." },
      { at: "Aug 7, 2026 · 05:02 BST · 04:02 UTC", kind: "requirement", actor: "policy engine", text: "ER-R02 became Conflicting — two authoritative retention sources disagree." },
      { at: "Aug 6, 2026 · 11:00 BST · 10:00 UTC", kind: "evidence", actor: "access-probe", text: "ER-S01 sample grant evaluation recorded; validity ended Aug 7 09:00 UTC." },
    ],
  },
  {
    id: "evt_60ca8",
    event_id: "EVT-2026-0826",
    name: "Regional Sales Kickoff",
    org: "Helix Manufacturing",
    tenant_id: "tnt_helix_15",
    region: "europe-west4",
    risk: "standard",
    tier: "Standard",
    gate: "NOT_STARTED",
    start_local: "Aug 12, 2026 · 10:00 BST",
    start_utc: "09:00 UTC",
    starts_in: "5d 2h",
    within_24h: false,
    days_out: 5,
    completed: false,
    primary_path: "missing",
    backup_path: "not_applicable",
    access: "not_applicable",
    captions: "not_applicable",
    preservation: "missing",
    operator: "Unassigned",
    operator_oncall: "—",
    backup_operator: "Unassigned",
    backup_operator_oncall: "—",
    blockers: 0,
    evidence_expiry: null,
    evidence_expiring_soon: false,
    evaluated_at: "Aug 7, 2026 · 06:40 BST · 05:40 UTC",
    policy_version: "readiness-policy/2026.07.3",
    audience_expectation: "Approx. 900 concurrent, annual recurrence",
    requirements: requirements({
      "ER-C01": { state: "missing", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No artifact" },
      "ER-C02": { state: "not_applicable", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "Not applicable at this risk class" },
      "ER-I01": { state: "missing", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No artifact" },
      "ER-P01": { state: "missing", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No artifact" },
      "ER-P02": { state: "not_applicable", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No caption commitment" },
      "ER-P03": { state: "not_applicable", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No translation commitment" },
      "ER-S01": { state: "not_applicable", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "Event is not restricted" },
      "ER-D01": { state: "missing", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No artifact" },
      "ER-D02": { state: "not_applicable", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "Below audience threshold" },
      "ER-U01": { state: "missing", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No artifact" },
      "ER-R01": { state: "missing", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No artifact" },
      "ER-R02": { state: "missing", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No artifact" },
      "ER-O01": { state: "missing", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No assignment" },
      "ER-O02": { state: "missing", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No runbook linked" },
      "ER-O03": { state: "missing", evidence_id: null, recorded: "—", valid_until: "—", producer: "—", result: "No validated contacts" },
    }),
    blocker_details: [],
    detail: {
      contribution: [
        ["Primary source", "Not configured"],
        ["Primary verified", "—"],
        ["Backup source", "Not applicable at this risk class"],
        ["Path independence", "—"],
      ],
      production: [
        ["Rendition ladder", "Platform default — not yet validated"],
        ["Packaging", "LL-HLS · manifest v3"],
        ["Captions", "Not committed for this event"],
        ["Translation", "Not committed for this event"],
      ],
      security: [
        ["Visibility", "Public"],
        ["Grant evaluation", "Not applicable — unrestricted"],
        ["Passphrase", "Not configured"],
        ["Restricted grantees", "Not applicable"],
      ],
      delivery: [
        ["Required regions", "Europe · Netherlands"],
        ["Route health", "Not probed for this event yet"],
        ["Pre-warm", "Not required at this audience threshold"],
        ["Expected concurrency", "900"],
      ],
      preservation: [
        ["Recording target", "Not configured"],
        ["Recording profile", "—"],
        ["Retention", "Platform default — 90 days"],
        ["Replay commitment", "Not committed"],
      ],
    },
    people: {
      primary: { name: "Unassigned", role: "Primary operator", detail: "Mandatory assignment outstanding" },
      backup: { name: "Unassigned", role: "Backup operator", detail: "Mandatory assignment outstanding" },
      runbook: "Not linked",
      rehearsal: "Not scheduled",
      handover: "—",
    },
    contacts: [{ name: "Helix events inbox", role: "Organization event owner", detail: "Not yet validated" }],
    exceptions: [],
    history: [
      { at: "Aug 7, 2026 · 06:40 BST · 05:40 UTC", kind: "evaluation", actor: "policy engine", text: "Evaluation completed — gate NOT_STARTED; no applicable evidence activity yet." },
      { at: "Aug 6, 2026 · 14:22 BST · 13:22 UTC", kind: "requirement", actor: "event service", text: "Event entered the readiness horizon." },
    ],
  },
  {
    id: "evt_3fe45",
    event_id: "EVT-2026-0829",
    name: "Product Launch Livestream",
    org: "Beacon Retail Group",
    tenant_id: "tnt_beacon_22",
    region: "us-west2",
    risk: "medium",
    tier: "Business",
    gate: "CONDITIONAL",
    start_local: "Aug 13, 2026 · 16:00 BST",
    start_utc: "15:00 UTC",
    starts_in: "6d 8h",
    within_24h: false,
    days_out: 6,
    completed: false,
    primary_path: "valid",
    backup_path: "valid",
    access: "valid",
    captions: "failed",
    preservation: "valid",
    operator: "C. Nwosu",
    operator_oncall: "On call",
    backup_operator: "H. Tanaka",
    backup_operator_oncall: "On call",
    blockers: 0,
    evidence_expiry: "Aug 13 · 13:00 UTC",
    evidence_expiring_soon: false,
    evaluated_at: "Aug 7, 2026 · 06:22 BST · 05:22 UTC",
    policy_version: "readiness-policy/2026.07.3",
    audience_expectation: "Approx. 9,400 concurrent, single occurrence",
    requirements: requirements({
      "ER-P02": { state: "failed", result: "Fail · language mapping rejected two committed locales" },
    }),
    blocker_details: [],
    detail: {
      contribution: [
        ["Primary source", "SRT · enc-beacon-studio · 12 Mbps CBR"],
        ["Primary verified", "Aug 6, 2026 · 23:40 BST · 22:40 UTC"],
        ["Backup source", "RTMP · independent studio uplink — verified"],
        ["Path independence", "Asserted and verified"],
      ],
      production: [
        ["Rendition ladder", "1080p50 / 720p50 — validated"],
        ["Packaging", "LL-HLS + DASH · manifest v3"],
        ["Captions", "Provider test failed for de-DE and ja-JP"],
        ["Translation", "en-US → fr-FR · provider test passed"],
      ],
      security: [
        ["Visibility", "Public with registration"],
        ["Grant evaluation", "Sample token evaluated in test mode · pass"],
        ["Passphrase", "Not configured"],
        ["Restricted grantees", "Not applicable"],
      ],
      delivery: [
        ["Required regions", "US · Los Angeles, Europe · London"],
        ["Route health", "Healthy at last probe"],
        ["Pre-warm", "Reserved · artifact valid to Aug 13 13:00 UTC"],
        ["Expected concurrency", "9,400"],
      ],
      preservation: [
        ["Recording target", "Validated · us-west2 · standard class"],
        ["Recording profile", "1080p50 archive + audio-only"],
        ["Retention", "2 years · plan entitlement"],
        ["Replay commitment", "Yes — public replay for 90 days"],
      ],
    },
    people: {
      primary: { name: "C. Nwosu", role: "Primary operator", detail: "On call · accepted Aug 6" },
      backup: { name: "H. Tanaka", role: "Backup operator", detail: "On call · accepted Aug 6" },
      runbook: "RB-EVT-0829 · v1 · approved Aug 6, 2026",
      rehearsal: "Scheduled Aug 12, 2026 · 16:00 BST · 15:00 UTC",
      handover: "Not required — single operating window",
    },
    contacts: [
      { name: "L. Osei", role: "Organization event owner", detail: "Validated Aug 5, 2026" },
      { name: "Beacon brand desk", role: "Approval authority", detail: "Validated Aug 5, 2026" },
    ],
    exceptions: [
      {
        id: "exc_9f02",
        requirement: "ER-P02",
        status: "Open condition — deadline Aug 13, 13:00 UTC",
        requester: "C. Nwosu · Platform Operations",
        justification: "Two of four committed caption locales failed provider mapping. Organization has agreed to launch with en-US and fr-FR if the remaining locales cannot be provisioned.",
        approvers: "Not required — non-mandatory item tracked as a condition",
        window: "Until Aug 13, 2026 · 14:00 BST · 13:00 UTC",
        review: "Condition lapses to Blocked if unresolved at the deadline",
      },
    ],
    history: [
      { at: "Aug 7, 2026 · 06:22 BST · 05:22 UTC", kind: "evaluation", actor: "policy engine", text: "Evaluation completed — gate CONDITIONAL (evaluation ev_2f78bb)." },
      { at: "Aug 6, 2026 · 23:40 BST · 22:40 UTC", kind: "evidence", actor: "readiness-runner", text: "Contribution requirements satisfied on both paths." },
      { at: "Aug 6, 2026 · 18:05 BST · 17:05 UTC", kind: "evidence", actor: "caption-provider-probe", text: "ER-P02 provider test FAILED for de-DE and ja-JP." },
    ],
  },
  // Ended event, surfaced only by "Include completed" — kept for post-event comparison and
  // never counted in the KPI strip, which measures current workload.
  {
    id: "evt_11a03",
    event_id: "EVT-2026-0806",
    name: "Q2 Investor Briefing",
    org: "Apex Systems",
    tenant_id: "tnt_apex_02",
    region: "us-east4",
    risk: "medium",
    tier: "Enterprise",
    gate: "PASSED",
    start_local: "Aug 6, 2026 · 15:00 BST",
    start_utc: "14:00 UTC",
    starts_in: "Ended 17h ago",
    within_24h: false,
    days_out: -1,
    completed: true,
    primary_path: "valid",
    backup_path: "valid",
    access: "valid",
    captions: "valid",
    preservation: "valid",
    operator: "S. Rao",
    operator_oncall: "Off shift",
    backup_operator: "H. Tanaka",
    backup_operator_oncall: "Off shift",
    blockers: 0,
    evidence_expiry: "Aug 6 · 14:00 UTC",
    evidence_expiring_soon: false,
    evaluated_at: "Aug 6, 2026 · 13:40 BST · 12:40 UTC",
    policy_version: "readiness-policy/2026.07.2",
    audience_expectation: "Approx. 5,100 concurrent, quarterly recurrence — completed",
    requirements: requirements({
      "ER-P03": { state: "not_applicable", result: "No translation commitment", evidence_id: null, recorded: "—", valid_until: "—", producer: "—" },
    }),
    blocker_details: [],
    detail: {
      contribution: [
        ["Primary source", "SRT · enc-apex-studio · 15 Mbps CBR"],
        ["Primary verified", "Aug 5, 2026 · 18:02 BST · 17:02 UTC"],
        ["Backup source", "RTMP · independent studio uplink — verified"],
        ["Path independence", "Asserted and verified"],
      ],
      production: [
        ["Rendition ladder", "1080p50 / 720p50 — validated"],
        ["Packaging", "LL-HLS + DASH · manifest v3"],
        ["Captions", "Live provider connected · en-US"],
        ["Translation", "Not committed for this event"],
      ],
      security: [
        ["Visibility", "Invite only"],
        ["Grant evaluation", "Sample token evaluated in test mode · pass"],
        ["Passphrase", "Configured"],
        ["Restricted grantees", "301 invited · 287 registered"],
      ],
      delivery: [
        ["Required regions", "US · N. Virginia"],
        ["Route health", "Healthy throughout the session"],
        ["Pre-warm", "Reserved and consumed"],
        ["Expected concurrency", "5,100 · peak observed 4,880"],
      ],
      preservation: [
        ["Recording target", "Validated · us-east4 · nearline class"],
        ["Recording profile", "1080p50 archive"],
        ["Retention", "10 years · regulatory requirement"],
        ["Replay commitment", "Yes — restricted replay, available"],
      ],
    },
    people: {
      primary: { name: "S. Rao", role: "Primary operator", detail: "Off shift · operated the session" },
      backup: { name: "H. Tanaka", role: "Backup operator", detail: "Off shift · not engaged" },
      runbook: "RB-EVT-0806 · v5 · approved Aug 3, 2026",
      rehearsal: "Completed Aug 5, 2026 · 18:00 BST · 17:00 UTC",
      handover: "Not required — single operating window",
    },
    contacts: [{ name: "K. Lindqvist", role: "Organization event owner", detail: "Validated Aug 3, 2026" }],
    exceptions: [],
    history: [
      { at: "Aug 6, 2026 · 16:12 BST · 15:12 UTC", kind: "transition", actor: "event service", text: "Session ended; readiness record closed for post-event review." },
      { at: "Aug 6, 2026 · 13:40 BST · 12:40 UTC", kind: "evaluation", actor: "policy engine", text: "Evaluation completed — gate PASSED (evaluation ev_2f6011)." },
    ],
  },
];

// Distinct Organizations for the type-ahead-style filter, derived from the set above so the
// filter can never offer an Organization the table has no row for.
export const ORGANIZATIONS = [...new Set(EVENTS.map((e) => e.org))].sort();

export const OPERATORS = [...new Set(EVENTS.map((e) => e.operator))].sort();
