// Static wireframe data for Trust & Safety (ZST-WF-SA-TS-001 · screen S08).
//
// §36 lists the Trust & Safety Policy Registry, Identity & Access, Audit and the Evidence store
// as build blockers, so there is nothing authoritative to call yet. This module is the
// demonstration payload for the interface and the page labels itself as such.
//
// Three rules from the spec shape every record below:
//   · STD-04 / §4 — case, priority, signal confidence, finding, enforcement, appeal, content
//     availability and live context are SEPARATE axes. There is no `status` key in this file.
//   · NO AUTOMATED GUILT — `confidence` belongs to a SIGNAL. It never becomes a finding, so a
//     high-confidence detector hit still sits at POTENTIAL_VIOLATION until a human reviewer
//     records a clause and a rationale.
//   · LOCKED LAUNCH RULE — every case concerns tenant-originated broadcast content. There is no
//     audience chat, comment, reaction or audience report anywhere in this data.

export const CASE_STATES = [
  "NEW",
  "TRIAGED",
  "EVIDENCE_REQUIRED",
  "UNDER_REVIEW",
  "DECISION_PENDING",
  "ACTION_PENDING",
  "VERIFYING",
  "RESOLVED",
  "CLOSED",
];
export const PRIORITIES = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"];
export const CONFIDENCE = ["HIGH", "MEDIUM", "LOW", "INDETERMINATE"];
export const FINDINGS = [
  "NO_FINDING",
  "POTENTIAL_VIOLATION",
  "VIOLATION_CONFIRMED",
  "LEGAL_ESCALATION",
  "OUT_OF_SCOPE",
  "INSUFFICIENT_EVIDENCE",
];
export const ENFORCEMENT_STATES = ["NONE", "PROPOSED", "APPROVED", "EXECUTING", "ACTIVE", "FAILED", "REVERSED", "EXPIRED"];
export const APPEAL_STATES = [
  "NOT_APPLICABLE",
  "AVAILABLE",
  "FILED",
  "UNDER_REVIEW",
  "UPHELD",
  "MODIFIED",
  "OVERTURNED",
  "EXPIRED",
];
export const AVAILABILITY_STATES = ["AVAILABLE", "RESTRICTED", "QUARANTINED", "REMOVED", "UNAVAILABLE_FOR_OTHER_REASON"];
export const LIVE_CONTEXTS = ["NOT_LIVE", "LIVE", "ENDING", "ENDED"];
export const SLA_STATES = ["ON_TRACK", "WARNING", "BREACHED"];

export const CONTENT_TYPES = ["live_event", "recorded_event", "replay", "uploaded_asset", "tenant_media"];

// §14 launch policy-reason taxonomy. Controlled policy data, surfaced here as the demo
// registry — the page reads it, it does not define it.
export const POLICY_FAMILIES = [
  "Safety",
  "Harassment / abuse",
  "Hate / discriminatory content",
  "Sexual / exploitative content",
  "Child-safety concern",
  "Privacy",
  "Impersonation / deception",
  "Fraud / unlawful activity",
  "Intellectual property",
  "Unauthorized recording",
  "Platform abuse",
  "Other",
];

export const SIGNAL_SOURCES = [
  "organization_report",
  "automated_signal",
  "internal_referral",
  "security_referral",
  "rights_holder_notice",
  "lawful_request",
];

export const SIGNAL_LABEL = {
  organization_report: "Organization report",
  automated_signal: "Automated signal",
  internal_referral: "Internal referral",
  security_referral: "Security referral",
  rights_holder_notice: "Rights-holder notice",
  lawful_request: "Lawful request",
};

// Every source is an ALLEGATION or a SIGNAL until a reviewer records a finding. The treatment
// text is rendered next to the source, so nobody reads "automated_signal · HIGH" as a verdict.
export const SIGNAL_TREATMENT = {
  organization_report: "Authenticated allegation; not a finding",
  automated_signal: "Signal only; requires human review",
  internal_referral: "Audited allegation",
  security_referral: "High-integrity referral",
  rights_holder_notice: "Validation required before action",
  lawful_request: "Legal validation required before enforcement",
};

const LABEL = {
  EVIDENCE_REQUIRED: "Evidence required",
  DECISION_PENDING: "Decision pending",
  ACTION_PENDING: "Action pending",
  UNDER_REVIEW: "Under review",
  NO_FINDING: "No finding",
  POTENTIAL_VIOLATION: "Potential violation",
  VIOLATION_CONFIRMED: "Violation confirmed",
  LEGAL_ESCALATION: "Legal escalation",
  OUT_OF_SCOPE: "Out of scope",
  INSUFFICIENT_EVIDENCE: "Insufficient evidence",
  NOT_APPLICABLE: "Not applicable",
  NOT_LIVE: "Not live",
  ON_TRACK: "On track",
  UNAVAILABLE_FOR_OTHER_REASON: "Unavailable (other reason)",
  INDETERMINATE: "Indeterminate",
};
// SCREAMING_SNAKE identifier -> display label, with an override map for the cases where
// sentence-casing is wrong. An unmapped value renders converted rather than as "Unknown":
// coercing a state the registry gave us into Unknown is the exact lie the state-separation
// rules exist to prevent.
//
// Kept local so this module stays a dependency-free payload — it is data, and data importing UI
// formatting helpers is the wrong direction (it also lets `node --test` load it directly).
const toLabel = (v, overrides) =>
  overrides[v] || (v ? v.charAt(0) + v.slice(1).toLowerCase().replace(/_/g, " ") : "—");
export const label = (v) => toLabel(v, LABEL);

export const PRIORITY_TONE = {
  CRITICAL: "danger",
  HIGH: "warning",
  MEDIUM: "info",
  LOW: "neutral",
  INFORMATIONAL: "neutral",
};
export const CASE_STATE_TONE = {
  NEW: "info",
  TRIAGED: "info",
  EVIDENCE_REQUIRED: "warning",
  UNDER_REVIEW: "info",
  DECISION_PENDING: "warning",
  ACTION_PENDING: "warning",
  VERIFYING: "info",
  RESOLVED: "success",
  CLOSED: "neutral",
};
// Confidence is deliberately NOT red/green. A high-confidence signal is not a bad thing to be
// alarmed by and a low-confidence one is not a pass — colouring it as severity would smuggle
// automated guilt back in through the palette.
export const CONFIDENCE_TONE = { HIGH: "brand", MEDIUM: "info", LOW: "neutral", INDETERMINATE: "neutral" };
export const FINDING_TONE = {
  NO_FINDING: "success",
  POTENTIAL_VIOLATION: "warning",
  VIOLATION_CONFIRMED: "danger",
  LEGAL_ESCALATION: "danger",
  OUT_OF_SCOPE: "neutral",
  INSUFFICIENT_EVIDENCE: "warning",
};
export const ENFORCEMENT_TONE = {
  NONE: "neutral",
  PROPOSED: "info",
  APPROVED: "info",
  EXECUTING: "info",
  ACTIVE: "danger",
  FAILED: "danger",
  REVERSED: "neutral",
  EXPIRED: "neutral",
};
export const APPEAL_TONE = {
  NOT_APPLICABLE: "neutral",
  AVAILABLE: "neutral",
  FILED: "info",
  UNDER_REVIEW: "info",
  UPHELD: "success",
  MODIFIED: "warning",
  OVERTURNED: "danger",
  EXPIRED: "neutral",
};
export const AVAILABILITY_TONE = {
  AVAILABLE: "success",
  RESTRICTED: "warning",
  QUARANTINED: "danger",
  REMOVED: "danger",
  UNAVAILABLE_FOR_OTHER_REASON: "neutral",
};
export const LIVE_TONE = { NOT_LIVE: "neutral", LIVE: "danger", ENDING: "warning", ENDED: "neutral" };
export const SLA_TONE = { ON_TRACK: "success", WARNING: "warning", BREACHED: "danger" };
export const EVIDENCE_INTEGRITY_TONE = { verified: "success", present: "info", unverified: "warning", failed: "danger", absent: "neutral" };

export const REGIONS = [
  { id: "europe-west2", label: "Europe · London" },
  { id: "europe-west4", label: "Europe · Netherlands" },
  { id: "us-east4", label: "US · N. Virginia" },
  { id: "us-west2", label: "US · Los Angeles" },
];

export const OWNERS = ["N. Rahman", "J. Levine", "A. Costa", "D. Mbeki", "Unassigned"];

// §15 decision outcomes, narrowest first. The order is the proportionality ladder — the UI
// presents them in this sequence so the cheapest reversible action is the closest to hand.
export const OUTCOMES = [
  { id: "NO_ACTION", label: "No action", meaning: "No adequate policy basis for action.", severity: "none" },
  { id: "PRESERVE_EVIDENCE", label: "Preserve evidence", meaning: "Preservation action; does not imply a violation.", severity: "none" },
  { id: "WARNING", label: "Warning", meaning: "Organization warning or corrective instruction.", severity: "low" },
  { id: "CONTENT_NOTICE", label: "Content notice", meaning: "Only where approved policy and an audience surface support a truthful notice.", severity: "low" },
  { id: "AUDIENCE_RESTRICTION", label: "Audience restriction", meaning: "Restrict access scope where supported.", severity: "medium" },
  { id: "ASSET_RESTRICTION", label: "Asset restriction", meaning: "Restrict playback or publication of a recorded asset.", severity: "medium" },
  { id: "LIVE_EVENT_RESTRICTION", label: "Live event restriction", meaning: "Restrict event access or distribution without full interruption.", severity: "high" },
  { id: "USER_ACCESS_RESTRICTION", label: "User access restriction", meaning: "Restrict a tenant user where Identity & Access policy supports it.", severity: "high" },
  { id: "LIVE_BROADCAST_INTERRUPTION", label: "Interrupt live broadcast", meaning: "Stop or block an active broadcast under the severe/emergency policy path.", severity: "severe" },
  { id: "ORGANIZATION_RESTRICTION", label: "Organization restriction", meaning: "Limit defined Organization capabilities.", severity: "severe" },
  { id: "ORGANIZATION_SUSPENSION_PROPOSAL", label: "Propose Organization suspension", meaning: "High-impact proposal requiring defined authorization.", severity: "severe" },
  { id: "ESCALATE_LEGAL_OR_SAFETY", label: "Escalate legal / safety", meaning: "Route for specialized determination.", severity: "medium" },
];

// §15.1 proportionality review. Rendered as questions, not as a score — a number here would
// invite an operator to clear a threshold instead of answering.
export const PROPORTIONALITY_FACTORS = [
  ["Verified harm", "What harm is established, probable, or imminent?"],
  ["Confidence", "How certain are the relevant facts?"],
  ["Scope", "Segment, asset, event, user, or Organization?"],
  ["Live exposure", "Is the content reaching viewers now?"],
  ["Reversibility", "Can a narrower reversible action address the risk?"],
  ["Unrepeatability", "Would interruption irreversibly destroy an unrepeatable event? This raises rigor, not immunity."],
  ["Legal / policy duty", "Is action required or constrained by a verified instruction or policy?"],
  ["Prior history", "Are relevant prior enforcement outcomes final and comparable?"],
  ["Collateral impact", "Which legitimate viewers, accessibility features, recordings, evidence, or workflows are affected?"],
];

export const CASES = [
  {
    case_id: "TS-1042",
    title: "Threat of violence alleged during live memorial broadcast",
    org: "Northstar Services",
    tenant_id: "tnt_northstar_01",
    tier: "Enterprise",
    region: "europe-west2",
    content_type: "live_event",
    content_ref: "EVT-2026-0814 · session ses_41ab",
    asset_ref: "—",
    live_context: "LIVE",
    unrepeatable: true,
    risk_classification: "Unrepeatable",
    viewers: "41,208 concurrent",
    reason_family: "Safety",
    reason: "Threats or violence",
    signal_sources: ["automated_signal", "organization_report"],
    confidence: "HIGH",
    case_state: "UNDER_REVIEW",
    priority: "CRITICAL",
    mode: "LIVE",
    opened_local: "Aug 7, 2026 · 07:42 BST",
    opened_utc: "06:42 UTC",
    age: "6m",
    due_local: "Aug 7, 2026 · 07:57 BST",
    due_utc: "06:57 UTC",
    sla_state: "WARNING",
    owner: "N. Rahman",
    finding: "POTENTIAL_VIOLATION",
    enforcement_state: "NONE",
    appeal_state: "NOT_APPLICABLE",
    content_availability: "AVAILABLE",
    legal_escalation: "Not escalated",
    policy_version: "ts-policy/2026.07.4",
    urgent_live: true,
    verification_pending: false,
    next_action: "Complete protected review, then record a finding and a proportionate scope. Interruption is the severe path and needs dual authorization.",
    blockers: [
      { tone: "danger", text: "Live and unrepeatable. Interruption would irreversibly end a single-occurrence memorial — this raises the evidence and authorization bar; it does not create immunity." },
      { tone: "warning", text: "Protected preview has not been opened. Case metadata permission does not grant content-view permission." },
    ],
    content_context: [
      ["Event", "EVT-2026-0814 · Global Memorial Broadcast"],
      ["Distribution scope", "Invite only · 1,102 registered grantees · Europe London + Netherlands"],
      ["Recording", "Active · retention 7 years, Organization governed policy"],
      ["Organization history", "No final adverse decision in the last 24 months"],
      ["Exposure", "41,208 concurrent viewers at last sample"],
      ["Platform health", "Contribute and Deliver healthy at last probe"],
    ],
    evidence: [
      {
        evidence_id: "EV-88120",
        type: "Automated signal",
        source: "system · detector zst.speech.threat/4.2.1",
        collector: "safety-detector-svc",
        created: "Aug 7, 2026 · 07:41 BST · 06:41 UTC",
        content_ref: "ses_41ab · 00:48:12–00:48:41",
        integrity: "verified",
        integrity_ref: "sha256:9f21…a4c1",
        provenance: "Derived from live transcript stream; no C2PA manifest applies",
        confidence: "HIGH",
        sensitivity: "Customer content derivative · protected",
        access_rule: "Trust & Safety with content-access scope",
        retention: "Case retention class C2 · 24 months",
        relation: "—",
      },
      {
        evidence_id: "EV-88121",
        type: "Transcript excerpt",
        source: "system · caption pipeline",
        collector: "safety-detector-svc",
        created: "Aug 7, 2026 · 07:41 BST · 06:41 UTC",
        content_ref: "ses_41ab · 00:48:05–00:48:50 · en-GB",
        integrity: "verified",
        integrity_ref: "sha256:41bd…77e9",
        provenance: "Automated caption output; automated generation is not human review",
        confidence: "MEDIUM",
        sensitivity: "Customer content · protected",
        access_rule: "Trust & Safety with content-access scope",
        retention: "Case retention class C2 · 24 months",
        relation: "Supports EV-88120",
      },
      {
        evidence_id: "EV-88124",
        type: "Report",
        source: "Organization · Northstar Services duty desk",
        collector: "M. Hale (Organization event owner)",
        created: "Aug 7, 2026 · 07:44 BST · 06:44 UTC",
        content_ref: "ses_41ab · reported window 00:47–00:50",
        integrity: "present",
        integrity_ref: "Submission receipt rcpt_2201",
        provenance: "Authenticated Organization submission",
        confidence: "MEDIUM",
        sensitivity: "Contains reporter identity · PII gated",
        access_rule: "Trust & Safety; reporter identity separately gated",
        retention: "Case retention class C2 · 24 months",
        relation: "Independent of EV-88120",
      },
      {
        evidence_id: "EV-88129",
        type: "Metadata",
        source: "system · event service",
        collector: "event-svc",
        created: "Aug 7, 2026 · 07:45 BST · 06:45 UTC",
        content_ref: "EVT-2026-0814 configuration snapshot",
        integrity: "verified",
        integrity_ref: "sha256:c001…12ab",
        provenance: "Authoritative service read",
        confidence: "—",
        sensitivity: "Operational metadata",
        access_rule: "Standing read in scope",
        retention: "Case retention class C2 · 24 months",
        relation: "Context for scope decisions",
      },
    ],
    assessments: [
      {
        family: "Safety",
        clause: "TS-SAF-004",
        clause_text: "Content that threatens violence against an identifiable person or group is prohibited on ZoikoStream broadcast surfaces.",
        version_at_content: "ts-policy/2026.07.4",
        version_current: "ts-policy/2026.07.4",
        applicability: "The detected utterance is directed at a named individual within the broadcast audio, inside tenant-originated content.",
        supporting: ["EV-88120", "EV-88121", "EV-88124"],
        challenging: [],
        reviewer_confidence: "Medium — transcript is automated and the audio has not yet been reviewed by a human.",
        countervailing: "The event is a memorial service; the phrase may be a quotation within a eulogy. This has not been ruled out.",
        jurisdiction: "Event produced in Europe · London. Routing fact only — not a legal conclusion.",
        finding: "POTENTIAL_VIOLATION",
        rationale: "A high-confidence detector plus an independent Organization report establishes a credible potential violation. A confirmed finding requires human review of the audio in context, which has not happened yet.",
      },
    ],
    decision: {
      outcome: "—",
      recorded_by: "—",
      recorded_at: "—",
      rationale: "No decision recorded. The case is under review.",
      approvers: "Dual authorization required for interruption; requester excluded from approval.",
      scope: "—",
      reversibility: "Interruption is not reversible for a single-occurrence event. Event restriction and asset restriction are.",
    },
    enforcement: {
      state: "NONE",
      requested: "—",
      approved: "—",
      executing: "—",
      verified: "—",
      correlation: "—",
      residual: "—",
      note: "No enforcement requested. Request acceptance would not be success — only authoritative verification is.",
    },
    communications: [
      {
        kind: "Urgent live notice",
        to: "Northstar Services duty desk",
        sent: "Aug 7, 2026 · 07:45 BST · 06:45 UTC",
        delivery: "Delivered",
        summary: "Operational summary that a safety review is open on the live broadcast, with the contact route. No accusation stated.",
      },
    ],
    appeal: {
      state: "NOT_APPLICABLE",
      eligibility: "No decision exists yet, so no appeal right has arisen.",
      deadline: "—",
      reviewer: "—",
      submission: "—",
      outcome: "—",
      effect: "—",
    },
    verification: [],
    repeat: {
      final_adverse: 0,
      overturned_excluded: 0,
      window: "24 months, per retention policy",
      note: "No final, comparable adverse decision for this Organization in the visible window.",
      items: [],
    },
    history: [
      { at: "Aug 7, 2026 · 07:45 BST · 06:45 UTC", kind: "communication", actor: "N. Rahman", text: "Urgent live notice sent to the Organization duty desk." },
      { at: "Aug 7, 2026 · 07:44 BST · 06:44 UTC", kind: "evidence", actor: "M. Hale (Organization)", text: "Organization report EV-88124 attached — independent of the detector signal." },
      { at: "Aug 7, 2026 · 07:43 BST · 06:43 UTC", kind: "assignment", actor: "A. Costa", text: "Case assigned to N. Rahman and moved to Under review." },
      { at: "Aug 7, 2026 · 07:42 BST · 06:42 UTC", kind: "assessment", actor: "N. Rahman", text: "Candidate clause TS-SAF-004 recorded as Potential violation pending human review of the audio." },
      { at: "Aug 7, 2026 · 07:41 BST · 06:41 UTC", kind: "signal", actor: "zst.speech.threat/4.2.1", text: "Automated signal created at HIGH confidence. Signal only — no finding and no enforcement." },
    ],
  },
  {
    case_id: "TS-1038",
    title: "Impersonation of a named executive in a recorded results broadcast",
    org: "Apex Systems",
    tenant_id: "tnt_apex_02",
    tier: "Enterprise",
    region: "us-east4",
    content_type: "recorded_event",
    content_ref: "EVT-2026-0402 · Q1 Results Broadcast",
    asset_ref: "AST-2E540",
    live_context: "ENDED",
    unrepeatable: false,
    risk_classification: "Medium",
    viewers: "212 replay sessions in the last 7 days",
    reason_family: "Impersonation / deception",
    reason: "Material impersonation of an identified person",
    signal_sources: ["organization_report", "internal_referral"],
    confidence: "MEDIUM",
    case_state: "EVIDENCE_REQUIRED",
    priority: "HIGH",
    mode: "LIVE",
    opened_local: "Aug 7, 2026 · 07:06 BST",
    opened_utc: "06:06 UTC",
    age: "42m",
    due_local: "Aug 7, 2026 · 15:06 BST",
    due_utc: "14:06 UTC",
    sla_state: "ON_TRACK",
    owner: "J. Levine",
    finding: "INSUFFICIENT_EVIDENCE",
    enforcement_state: "ACTIVE",
    appeal_state: "AVAILABLE",
    content_availability: "RESTRICTED",
    legal_escalation: "Not escalated",
    policy_version: "ts-policy/2026.07.4",
    urgent_live: false,
    verification_pending: false,
    next_action: "Awaiting the Organization's identity documentation. The existing asset restriction stays active while the request is outstanding.",
    blockers: [
      { tone: "warning", text: "Blocked on external information: the Organization has been asked for documentation establishing the speaker's identity and authorization." },
      { tone: "info", text: "An asset restriction from a prior decision is already ACTIVE. Its appeal window is open." },
    ],
    content_context: [
      ["Asset", "AST-2E540 · Corporate Results Broadcast replay"],
      ["Distribution scope", "Invite only · 388 registered grantees · US N. Virginia + Europe London"],
      ["Recording", "Finalized · retention 10 years, regulatory requirement, legal hold GOV-HOLD-0231 active"],
      ["Organization history", "1 final warning (Jan 2026), unrelated policy family"],
      ["Exposure", "212 replay sessions in the last 7 days"],
      ["Platform health", "Deliver degraded for this asset — one rendition failed validation"],
    ],
    evidence: [
      {
        evidence_id: "EV-87004",
        type: "Report",
        source: "Organization · Apex Systems investor relations",
        collector: "K. Lindqvist",
        created: "Aug 7, 2026 · 07:04 BST · 06:04 UTC",
        content_ref: "AST-2E540 · 00:12:40–00:19:02",
        integrity: "present",
        integrity_ref: "Submission receipt rcpt_2188",
        provenance: "Authenticated Organization submission",
        confidence: "MEDIUM",
        sensitivity: "Contains named individuals · PII gated",
        access_rule: "Trust & Safety; identity fields separately gated",
        retention: "Case retention class C1 · legal hold overrides",
        relation: "—",
      },
      {
        evidence_id: "EV-87011",
        type: "Recording segment",
        source: "system · media service",
        collector: "J. Levine",
        created: "Aug 7, 2026 · 07:22 BST · 06:22 UTC",
        content_ref: "AST-2E540 · 00:12:40–00:19:02 · 720p50 rendition",
        integrity: "verified",
        integrity_ref: "sha256:77aa…0f31",
        provenance: "C2PA manifest present and VERIFIED on the source asset",
        confidence: "—",
        sensitivity: "Customer content · protected essence",
        access_rule: "Trust & Safety with content-access scope",
        retention: "Case retention class C1 · legal hold overrides",
        relation: "Supports EV-87004",
      },
      {
        evidence_id: "EV-87019",
        type: "Metadata",
        source: "system · identity service",
        collector: "identity-svc",
        created: "Aug 7, 2026 · 07:30 BST · 06:30 UTC",
        content_ref: "Speaker grant record for ses_2211",
        integrity: "verified",
        integrity_ref: "sha256:2b90…ccd4",
        provenance: "Authoritative service read",
        confidence: "—",
        sensitivity: "User-level identifiers · PII gated",
        access_rule: "Profile-gated; justification required",
        retention: "Case retention class C1 · legal hold overrides",
        relation: "Challenges EV-87004 — the speaker held a valid Organization speaker grant",
      },
      {
        evidence_id: "EV-87025",
        type: "Other (controlled)",
        source: "Organization · pending",
        collector: "—",
        created: "Requested Aug 7, 2026 · 07:34 BST · 06:34 UTC",
        content_ref: "Identity and authorization documentation for the named speaker",
        integrity: "absent",
        integrity_ref: "—",
        provenance: "—",
        confidence: "—",
        sensitivity: "Expected to contain PII",
        access_rule: "Trust & Safety; PII fields gated on receipt",
        retention: "Case retention class C1",
        relation: "Requested to resolve the disagreement between EV-87004 and EV-87019",
      },
    ],
    assessments: [
      {
        family: "Impersonation / deception",
        clause: "TS-IMP-002",
        clause_text: "Presenting as a person you are not, in a way that is material to the audience's understanding, is prohibited.",
        version_at_content: "ts-policy/2026.05.1",
        version_current: "ts-policy/2026.07.4",
        applicability: "The allegation is that the speaker in the identified segment was presented as a named executive who was not present.",
        supporting: ["EV-87004", "EV-87011"],
        challenging: ["EV-87019"],
        reviewer_confidence: "Low — two authoritative sources disagree and the console does not silently prefer one.",
        countervailing: "The identity service shows a valid Organization speaker grant for the session. That is consistent with an authorized stand-in rather than impersonation.",
        jurisdiction: "Produced in US · N. Virginia. Routing fact only.",
        finding: "INSUFFICIENT_EVIDENCE",
        rationale: "Sources disagree on a material fact. The current asset restriction is proportionate and reversible while the Organization supplies documentation; a confirmed finding is not supportable on this record.",
      },
    ],
    decision: {
      outcome: "ASSET_RESTRICTION",
      recorded_by: "J. Levine · Trust & Safety",
      recorded_at: "Aug 3, 2026 · 12:14 BST · 11:14 UTC",
      rationale: "Narrowest reversible action that limits distribution of the disputed segment while the factual disagreement is resolved. Interruption was not applicable — the event had ended.",
      approvers: "A. Costa (second reviewer, severe-class separation not required at this severity)",
      scope: "Asset AST-2E540 · replay distribution · both delivery regions",
      reversibility: "Fully reversible — restriction lift restores the existing renditions.",
    },
    enforcement: {
      state: "ACTIVE",
      requested: "Aug 3, 2026 · 12:14 BST · 11:14 UTC",
      approved: "Aug 3, 2026 · 12:18 BST · 11:18 UTC",
      executing: "Aug 3, 2026 · 12:20 BST · 11:20 UTC",
      verified: "Aug 3, 2026 · 12:26 BST · 11:26 UTC · playback denied from affected scope; cached previews invalidated",
      correlation: "corr_ts1038_9a04",
      residual: "None known. Downstream ZoikoStream embeds checked.",
      note: "Executed through the authoritative delivery service. Verification observed the post-action state rather than trusting the request acknowledgement.",
    },
    communications: [
      {
        kind: "Organization decision notice",
        to: "Apex Systems · investor relations, duty desk",
        sent: "Aug 3, 2026 · 12:30 BST · 11:30 UTC",
        delivery: "Delivered",
        summary: "Case reference, affected scope, action, effective time, policy basis appropriate for disclosure, and the appeal path. Generated from the structured decision record.",
      },
      {
        kind: "Evidence request",
        to: "Apex Systems · investor relations",
        sent: "Aug 7, 2026 · 07:34 BST · 06:34 UTC",
        delivery: "Delivered",
        summary: "Exactly which documentation is missing, the secure submission method, the deadline, and the consequence of non-response.",
      },
    ],
    appeal: {
      state: "AVAILABLE",
      eligibility: "Eligible — an asset restriction carries an appeal right under the effective policy.",
      deadline: "Sep 2, 2026 · 12:30 BST · 11:30 UTC",
      reviewer: "Assigned on filing; will not be the sole original decision maker.",
      submission: "Not filed.",
      outcome: "—",
      effect: "The restriction remains active unless an appeal outcome changes it.",
    },
    verification: [
      { check: "Content restriction", expected: "Playback/access check from the affected scope", result: "Verified · playback denied for non-privileged grantees", at: "Aug 3, 2026 · 11:26 UTC" },
      { check: "Asset restriction", expected: "Asset availability + cache/CDN invalidation", result: "Verified · availability DEGRADED, previews invalidated", at: "Aug 3, 2026 · 11:26 UTC" },
      { check: "Preservation", expected: "Recording retained per the approved action", result: "Verified · retained under legal hold GOV-HOLD-0231", at: "Aug 3, 2026 · 11:27 UTC" },
      { check: "Notifications", expected: "Communication delivery status", result: "Verified · decision notice delivered", at: "Aug 3, 2026 · 11:31 UTC" },
      { check: "Residual exposure", expected: "Known downstream copies/embeds checked", result: "Verified · none found", at: "Aug 3, 2026 · 11:34 UTC" },
    ],
    repeat: {
      final_adverse: 1,
      overturned_excluded: 1,
      window: "24 months, per retention policy",
      note: "One final adverse outcome in a different policy family. One overturned decision is excluded from the adverse count and shown for fairness.",
      items: [
        { case_id: "TS-0704", at: "Jan 18, 2026", family: "Platform abuse", outcome: "WARNING", final: true, counts: true, note: "Final. Comparable scope: Organization-level warning." },
        { case_id: "TS-0512", at: "Nov 2, 2025", family: "Intellectual property", outcome: "ASSET_RESTRICTION", final: true, counts: false, note: "OVERTURNED on appeal — excluded from the adverse count." },
        { case_id: "TS-1038", at: "Aug 3, 2026", family: "Impersonation / deception", outcome: "ASSET_RESTRICTION", final: false, counts: false, note: "This case. Unresolved allegation — never counted as a final violation." },
      ],
    },
    history: [
      { at: "Aug 7, 2026 · 07:34 BST · 06:34 UTC", kind: "communication", actor: "J. Levine", text: "Evidence request sent; case moved to Evidence required." },
      { at: "Aug 7, 2026 · 07:30 BST · 06:30 UTC", kind: "evidence", actor: "identity-svc", text: "EV-87019 attached — challenges the report. Source disagreement recorded explicitly." },
      { at: "Aug 7, 2026 · 07:06 BST · 06:06 UTC", kind: "signal", actor: "K. Lindqvist (Organization)", text: "New report reopened review of the previously restricted asset." },
      { at: "Aug 3, 2026 · 12:26 BST · 11:26 UTC", kind: "enforcement", actor: "delivery-svc", text: "Enforcement VERIFIED — playback denied from the affected scope." },
      { at: "Aug 3, 2026 · 12:14 BST · 11:14 UTC", kind: "decision", actor: "J. Levine", text: "Decision ASSET_RESTRICTION recorded under clause TS-IMP-002 (ts-policy/2026.05.1)." },
    ],
  },
  {
    case_id: "TS-1034",
    title: "Privacy complaint — protected personal information disclosed on air",
    org: "Grace Network",
    tenant_id: "tnt_gracenet_09",
    tier: "Business",
    region: "us-east4",
    content_type: "live_event",
    content_ref: "EVT-2026-0812 · session ses_5c11",
    asset_ref: "AST-4B77C",
    live_context: "ENDED",
    unrepeatable: false,
    risk_classification: "High",
    viewers: "18,400 peak concurrent",
    reason_family: "Privacy",
    reason: "Unauthorized disclosure of protected personal information",
    signal_sources: ["organization_report"],
    confidence: "MEDIUM",
    case_state: "DECISION_PENDING",
    priority: "HIGH",
    mode: "LIVE",
    opened_local: "Aug 7, 2026 · 06:30 BST",
    opened_utc: "05:30 UTC",
    age: "1h 18m",
    due_local: "Aug 7, 2026 · 10:30 BST",
    due_utc: "09:30 UTC",
    sla_state: "WARNING",
    owner: "J. Levine",
    finding: "VIOLATION_CONFIRMED",
    enforcement_state: "PROPOSED",
    appeal_state: "NOT_APPLICABLE",
    content_availability: "AVAILABLE",
    legal_escalation: "Privacy escalation raised with Governance",
    policy_version: "ts-policy/2026.07.4",
    urgent_live: false,
    verification_pending: false,
    next_action: "A proposed asset restriction on the recorded segment is awaiting a second reviewer. The replay has not opened yet, so the narrower action is still available.",
    blockers: [
      { tone: "warning", text: "Enforcement is PROPOSED, not active. Nothing has been restricted yet." },
      { tone: "info", text: "Replay preparation is still running for this asset — restricting before it opens avoids any audience exposure." },
    ],
    content_context: [
      ["Event", "EVT-2026-0812 · Annual Worship Service"],
      ["Distribution scope", "Public · US N. Virginia"],
      ["Recording", "Finalizing · retention 1 year, plan entitlement"],
      ["Organization history", "No final adverse decision in the visible window"],
      ["Exposure", "18,400 peak concurrent; replay not yet available"],
      ["Platform health", "Preserve healthy; finalization 68% complete at last read"],
    ],
    evidence: [
      {
        evidence_id: "EV-86440",
        type: "Report",
        source: "Organization · Grace Network media desk",
        collector: "R. Nkemelu",
        created: "Aug 7, 2026 · 06:28 BST · 05:28 UTC",
        content_ref: "ses_5c11 · 00:31:10–00:31:55",
        integrity: "present",
        integrity_ref: "Submission receipt rcpt_2170",
        provenance: "Authenticated Organization submission",
        confidence: "MEDIUM",
        sensitivity: "Describes third-party PII · gated",
        access_rule: "Trust & Safety; PII fields gated",
        retention: "Case retention class C2 · 24 months",
        relation: "—",
      },
      {
        evidence_id: "EV-86447",
        type: "Transcript excerpt",
        source: "system · caption pipeline",
        collector: "J. Levine",
        created: "Aug 7, 2026 · 06:52 BST · 05:52 UTC",
        content_ref: "ses_5c11 · 00:31:00–00:32:10 · en-US",
        integrity: "verified",
        integrity_ref: "sha256:31cc…9a02",
        provenance: "Automated caption output — automated generation, not human-reviewed",
        confidence: "MEDIUM",
        sensitivity: "Contains third-party PII · gated",
        access_rule: "Trust & Safety with content-access scope",
        retention: "Case retention class C2 · 24 months",
        relation: "Supports EV-86440",
      },
      {
        evidence_id: "EV-86451",
        type: "Still",
        source: "system · media service",
        collector: "J. Levine",
        created: "Aug 7, 2026 · 07:01 BST · 06:01 UTC",
        content_ref: "ses_5c11 · frame at 00:31:32",
        integrity: "verified",
        integrity_ref: "sha256:88de…4410",
        provenance: "Derived from source essence; derived item linked to its source, original untouched",
        confidence: "—",
        sensitivity: "Contains legible PII · blurred by default for reviewers",
        access_rule: "Trust & Safety with content-access scope",
        retention: "Case retention class C2 · 24 months",
        relation: "Derived from EV-86447 window",
      },
    ],
    assessments: [
      {
        family: "Privacy",
        clause: "TS-PRV-001",
        clause_text: "Broadcasting protected personal information about an identifiable individual without a lawful basis or their consent is prohibited.",
        version_at_content: "ts-policy/2026.07.4",
        version_current: "ts-policy/2026.07.4",
        applicability: "A home address and a contact number for a named third party were read aloud and displayed on a slide within tenant-originated content.",
        supporting: ["EV-86440", "EV-86447", "EV-86451"],
        challenging: [],
        reviewer_confidence: "High — the disclosure is directly observable in the transcript and the still, and the Organization does not dispute it.",
        countervailing: "The disclosure appears accidental rather than malicious. That is relevant to proportionality and to the communication tone; it does not change whether the clause applies.",
        jurisdiction: "Produced in US · N. Virginia; affected individual is in the UK. Routing facts only — applicability of any statutory duty is a Legal and Governance determination.",
        finding: "VIOLATION_CONFIRMED",
        rationale: "The clause applies on directly observed evidence that the Organization does not dispute. The narrowest effective action is to restrict the affected segment before the replay opens, rather than restricting the whole event retrospectively.",
      },
    ],
    decision: {
      outcome: "ASSET_RESTRICTION",
      recorded_by: "J. Levine · Trust & Safety",
      recorded_at: "Aug 7, 2026 · 07:22 BST · 06:22 UTC",
      rationale: "Restrict the recorded asset so the replay cannot open with the disclosure in it, while the Organization removes the segment. Narrower than an event restriction and fully reversible.",
      approvers: "Awaiting second reviewer — requester excluded from approving their own decision.",
      scope: "Asset AST-4B77C · replay publication · US N. Virginia",
      reversibility: "Fully reversible once the Organization supplies an edited asset.",
    },
    enforcement: {
      state: "PROPOSED",
      requested: "Aug 7, 2026 · 07:22 BST · 06:22 UTC",
      approved: "—",
      executing: "—",
      verified: "—",
      correlation: "—",
      residual: "No audience exposure yet — replay has not opened.",
      note: "Proposed only. The UI will not describe this as restricted until the authoritative service reports and verification observes it.",
    },
    communications: [
      {
        kind: "Evidence request",
        to: "Grace Network media desk",
        sent: "Aug 7, 2026 · 06:58 BST · 05:58 UTC",
        delivery: "Delivered",
        summary: "Asked for the slide deck used in the identified window and confirmation of whether consent exists.",
      },
      {
        kind: "Internal handoff",
        to: "Governance · privacy review",
        sent: "Aug 7, 2026 · 07:24 BST · 06:24 UTC",
        delivery: "Delivered",
        summary: "Facts, evidence references, proposed action and pending verification passed to Governance for the privacy-obligation assessment.",
      },
    ],
    appeal: {
      state: "NOT_APPLICABLE",
      eligibility: "No appeal right until the decision is approved and executed.",
      deadline: "—",
      reviewer: "—",
      submission: "—",
      outcome: "—",
      effect: "—",
    },
    verification: [],
    repeat: {
      final_adverse: 0,
      overturned_excluded: 0,
      window: "24 months, per retention policy",
      note: "No final, comparable adverse decision in the visible window. This case is not counted while it remains unresolved.",
      items: [],
    },
    history: [
      { at: "Aug 7, 2026 · 07:24 BST · 06:24 UTC", kind: "communication", actor: "J. Levine", text: "Internal handoff to Governance privacy review." },
      { at: "Aug 7, 2026 · 07:22 BST · 06:22 UTC", kind: "decision", actor: "J. Levine", text: "Decision ASSET_RESTRICTION recorded; enforcement PROPOSED pending a second reviewer." },
      { at: "Aug 7, 2026 · 07:10 BST · 06:10 UTC", kind: "assessment", actor: "J. Levine", text: "Finding VIOLATION_CONFIRMED under TS-PRV-001 (ts-policy/2026.07.4)." },
      { at: "Aug 7, 2026 · 06:30 BST · 05:30 UTC", kind: "signal", actor: "R. Nkemelu (Organization)", text: "Organization report received; case created as an authenticated allegation." },
    ],
  },
  {
    case_id: "TS-1027",
    title: "Rights-holder claim over a musical performance in a replay asset",
    org: "Eastbridge University",
    tenant_id: "tnt_eastbridge_04",
    tier: "Enterprise",
    region: "europe-west2",
    content_type: "replay",
    content_ref: "EVT-2026-0701 · Summer Commencement",
    asset_ref: "AST-6C102",
    live_context: "ENDED",
    unrepeatable: false,
    risk_classification: "Medium",
    viewers: "9,880 replay sessions",
    reason_family: "Intellectual property",
    reason: "Copyright claim under the governed rights process",
    signal_sources: ["rights_holder_notice"],
    confidence: "LOW",
    case_state: "UNDER_REVIEW",
    priority: "MEDIUM",
    mode: "LIVE",
    opened_local: "Aug 7, 2026 · 04:36 BST",
    opened_utc: "03:36 UTC",
    age: "3h 11m",
    due_local: "Aug 9, 2026 · 04:36 BST",
    due_utc: "03:36 UTC",
    sla_state: "ON_TRACK",
    owner: "A. Costa",
    finding: "POTENTIAL_VIOLATION",
    enforcement_state: "NONE",
    appeal_state: "NOT_APPLICABLE",
    content_availability: "AVAILABLE",
    legal_escalation: "Rights validation in progress",
    policy_version: "ts-policy/2026.07.4",
    urgent_live: false,
    verification_pending: false,
    next_action: "Validate the claimant's rights basis before any action. A received notice is not automatically valid.",
    blockers: [
      { tone: "warning", text: "The claimant's rights basis has not been validated. No enforcement may follow from receipt alone." },
    ],
    content_context: [
      ["Asset", "AST-6C102 · University Commencement replay"],
      ["Distribution scope", "Public with registration · Europe London"],
      ["Recording", "Finalized · retention 3 years, plan entitlement"],
      ["Organization history", "No final adverse decision in the visible window"],
      ["Exposure", "9,880 replay sessions since Aug 1"],
      ["Platform health", "Deliver healthy"],
    ],
    evidence: [
      {
        evidence_id: "EV-84120",
        type: "Rights document",
        source: "authority · claimant (Harbourline Music Ltd)",
        collector: "rights-intake",
        created: "Aug 7, 2026 · 04:34 BST · 03:34 UTC",
        content_ref: "AST-6C102 · 01:12:40–01:16:05",
        integrity: "unverified",
        integrity_ref: "Submission receipt rcpt_2140",
        provenance: "Claimant assertion; rights basis not yet validated",
        confidence: "LOW",
        sensitivity: "Commercial-confidential · claimant identity gated",
        access_rule: "Trust & Safety; claimant detail gated",
        retention: "Case retention class C3 · 36 months",
        relation: "—",
      },
      {
        evidence_id: "EV-84131",
        type: "Metadata",
        source: "system · media service",
        collector: "A. Costa",
        created: "Aug 7, 2026 · 05:02 BST · 04:02 UTC",
        content_ref: "AST-6C102 · track and chapter metadata",
        integrity: "verified",
        integrity_ref: "sha256:0aa1…7712",
        provenance: "Authoritative service read",
        confidence: "—",
        sensitivity: "Operational metadata",
        access_rule: "Standing read in scope",
        retention: "Case retention class C3 · 36 months",
        relation: "Context — confirms a performance exists in the claimed window",
      },
    ],
    assessments: [
      {
        family: "Intellectual property",
        clause: "TS-IP-003",
        clause_text: "Broadcasting a work you do not hold the necessary rights to, where a valid claim is established through the governed process, is prohibited.",
        version_at_content: "ts-policy/2026.07.4",
        version_current: "ts-policy/2026.07.4",
        applicability: "A performance exists in the claimed window. Whether the claimant holds the asserted rights has not been established.",
        supporting: ["EV-84120"],
        challenging: [],
        reviewer_confidence: "Low — the claim is unvalidated and the Organization has not yet been asked to respond.",
        countervailing: "The Organization may hold a performance licence covering the work. That has not been checked.",
        jurisdiction: "Claim asserted under UK law; content produced in Europe · London. Routing facts only — not legal advice.",
        finding: "POTENTIAL_VIOLATION",
        rationale: "Recorded to keep the case open for validation. No action is proportionate on an unvalidated claim, and a received notice is never treated as automatically valid.",
      },
    ],
    decision: {
      outcome: "—",
      recorded_by: "—",
      recorded_at: "—",
      rationale: "No decision recorded. Rights validation is outstanding.",
      approvers: "—",
      scope: "—",
      reversibility: "Asset restriction would be reversible if it becomes necessary.",
    },
    enforcement: {
      state: "NONE",
      requested: "—",
      approved: "—",
      executing: "—",
      verified: "—",
      correlation: "—",
      residual: "—",
      note: "No enforcement. Receipt of a notice is not a basis for action.",
    },
    communications: [
      {
        kind: "Evidence request",
        to: "Eastbridge University · AV desk",
        sent: "Aug 7, 2026 · 05:20 BST · 04:20 UTC",
        delivery: "Delivered",
        summary: "Asked whether a performance licence covers the identified work, with the secure submission route and a deadline.",
      },
    ],
    appeal: {
      state: "NOT_APPLICABLE",
      eligibility: "No decision exists yet.",
      deadline: "—",
      reviewer: "—",
      submission: "—",
      outcome: "—",
      effect: "—",
    },
    verification: [],
    repeat: {
      final_adverse: 0,
      overturned_excluded: 0,
      window: "24 months, per retention policy",
      note: "No final, comparable adverse decision in the visible window.",
      items: [],
    },
    history: [
      { at: "Aug 7, 2026 · 05:20 BST · 04:20 UTC", kind: "communication", actor: "A. Costa", text: "Licence question sent to the Organization." },
      { at: "Aug 7, 2026 · 05:02 BST · 04:02 UTC", kind: "evidence", actor: "A. Costa", text: "Asset metadata attached as context." },
      { at: "Aug 7, 2026 · 04:36 BST · 03:36 UTC", kind: "signal", actor: "rights-intake", text: "Rights-holder notice received. Validation required — receipt is not validity." },
    ],
  },
  {
    case_id: "TS-1019",
    title: "Appeal filed against an audience restriction on a civic broadcast",
    org: "City of Northfield",
    tenant_id: "tnt_northfield_11",
    tier: "Business",
    region: "us-west2",
    content_type: "recorded_event",
    content_ref: "EVT-2026-0770 · July Town Hall",
    asset_ref: "AST-9A014",
    live_context: "ENDED",
    unrepeatable: false,
    risk_classification: "High",
    viewers: "No sessions — asset is unavailable",
    reason_family: "Harassment / abuse",
    reason: "Targeted harassment alleged during public comment",
    signal_sources: ["internal_referral"],
    confidence: "MEDIUM",
    case_state: "VERIFYING",
    priority: "MEDIUM",
    mode: "LIVE",
    opened_local: "Aug 6, 2026 · 05:40 BST",
    opened_utc: "04:40 UTC",
    age: "1d 2h",
    due_local: "Aug 8, 2026 · 05:40 BST",
    due_utc: "04:40 UTC",
    sla_state: "ON_TRACK",
    owner: "D. Mbeki",
    finding: "VIOLATION_CONFIRMED",
    enforcement_state: "REVERSED",
    appeal_state: "OVERTURNED",
    content_availability: "AVAILABLE",
    legal_escalation: "Not escalated",
    policy_version: "ts-policy/2026.07.4",
    urgent_live: false,
    verification_pending: true,
    next_action: "The appeal was overturned. Restoration has been initiated and the console stays in Verifying until the authoritative restoration is observed.",
    blockers: [
      { tone: "info", text: "Restoration is executing. The case stays open until verification confirms the restored state." },
      { tone: "info", text: "The overturned outcome is excluded from this Organization's adverse repeat-violation count." },
    ],
    content_context: [
      ["Asset", "AST-9A014 · Civic Town Hall recording"],
      ["Distribution scope", "Public · US Los Angeles"],
      ["Recording", "Finalized · retention 6 years, regulatory requirement"],
      ["Organization history", "1 prior final warning (Mar 2026), same policy family"],
      ["Exposure", "No sessions — a separate transcode failure has the asset unavailable"],
      ["Platform health", "Processing FAILED on this asset — unrelated to this case"],
    ],
    evidence: [
      {
        evidence_id: "EV-81002",
        type: "Report",
        source: "internal · Customer Operations referral",
        collector: "D. Mbeki",
        created: "Aug 6, 2026 · 05:38 BST · 04:38 UTC",
        content_ref: "AST-9A014 · 00:41:20–00:44:02",
        integrity: "present",
        integrity_ref: "Referral ref ref_1180",
        provenance: "Audited internal allegation",
        confidence: "MEDIUM",
        sensitivity: "Names third parties · PII gated",
        access_rule: "Trust & Safety",
        retention: "Case retention class C2 · 24 months",
        relation: "—",
      },
      {
        evidence_id: "EV-81044",
        type: "Other (controlled)",
        source: "Organization · City of Northfield (appeal submission)",
        collector: "City clerk's office",
        created: "Aug 6, 2026 · 16:10 BST · 15:10 UTC",
        content_ref: "Council standing orders and public-comment record",
        integrity: "present",
        integrity_ref: "Submission receipt rcpt_2155",
        provenance: "Authenticated Organization submission, appended to the original record",
        confidence: "—",
        sensitivity: "Public record",
        access_rule: "Trust & Safety; appeal reviewer",
        retention: "Case retention class C2 · 24 months",
        relation: "Challenges EV-81002 — establishes the exchange as protected public comment",
      },
    ],
    assessments: [
      {
        family: "Harassment / abuse",
        clause: "TS-HAR-002",
        clause_text: "Targeted harassment or intimidation of an identifiable person is prohibited where the policy covers the surface.",
        version_at_content: "ts-policy/2026.06.2",
        version_current: "ts-policy/2026.07.4",
        applicability: "Originally assessed as targeted abuse of a named official during public comment.",
        supporting: ["EV-81002"],
        challenging: ["EV-81044"],
        reviewer_confidence: "The appeal reviewer found the original factual basis did not survive the added context.",
        countervailing: "The exchange occurred within a formally minuted public-comment period governed by council standing orders, which the original assessment did not have in front of it.",
        jurisdiction: "Produced in US · Los Angeles. Routing fact only.",
        finding: "VIOLATION_CONFIRMED",
        rationale: "The original finding stands as the historical record — history is never overwritten. The appeal outcome is recorded separately and the enforcement has been reversed.",
      },
    ],
    decision: {
      outcome: "AUDIENCE_RESTRICTION",
      recorded_by: "D. Mbeki · Trust & Safety",
      recorded_at: "Aug 6, 2026 · 09:02 BST · 08:02 UTC",
      rationale: "Restricted the audience scope for the identified segment rather than removing the civic record.",
      approvers: "N. Rahman (second reviewer)",
      scope: "Asset AST-9A014 · audience scope · US Los Angeles",
      reversibility: "Reversible — reversal restores the original access scope.",
    },
    enforcement: {
      state: "REVERSED",
      requested: "Aug 6, 2026 · 09:02 BST · 08:02 UTC",
      approved: "Aug 6, 2026 · 09:11 BST · 08:11 UTC",
      executing: "Aug 7, 2026 · 07:20 BST · 06:20 UTC (reversal)",
      verified: "Pending — restoration not yet confirmed by the authoritative service",
      correlation: "corr_ts1019_4c02",
      residual: "Unknown until restoration verification returns. The console reports Pending rather than assuming success.",
      note: "Reversal follows the overturned appeal. Verification is outstanding, so nothing here claims the restriction is gone.",
    },
    communications: [
      {
        kind: "Organization decision notice",
        to: "City of Northfield · clerk's office",
        sent: "Aug 6, 2026 · 09:20 BST · 08:20 UTC",
        delivery: "Delivered",
        summary: "Case reference, scope, action, effective time, policy basis and the appeal path.",
      },
      {
        kind: "Appeal outcome",
        to: "City of Northfield · clerk's office",
        sent: "Aug 7, 2026 · 07:18 BST · 06:18 UTC",
        delivery: "Delivered",
        summary: "Outcome OVERTURNED, affected scope, the effective state, and the basis appropriate for disclosure.",
      },
    ],
    appeal: {
      state: "OVERTURNED",
      eligibility: "Eligible — audience restriction carries an appeal right.",
      deadline: "Sep 5, 2026 · 09:20 BST · 08:20 UTC",
      reviewer: "A. Costa — independent of the original decision maker",
      submission: "Filed Aug 6, 2026 · 16:10 BST · 15:10 UTC with new contested evidence (EV-81044).",
      outcome: "Overturned. The original factual basis did not survive the added public-record context.",
      effect: "Restriction reversed. Restoration is executing and awaiting verification.",
    },
    verification: [
      { check: "Rollback", expected: "Authoritative restoration verified", result: "Pending — reversal executing", at: "—" },
      { check: "Content restriction", expected: "Access check from the affected scope", result: "Pending", at: "—" },
      { check: "Notifications", expected: "Communication delivery status", result: "Verified · appeal outcome delivered", at: "Aug 7, 2026 · 06:19 UTC" },
      { check: "Residual exposure", expected: "Downstream copies/embeds checked", result: "Pending", at: "—" },
    ],
    repeat: {
      final_adverse: 1,
      overturned_excluded: 1,
      window: "24 months, per retention policy",
      note: "This case's outcome was overturned and is therefore excluded from the adverse count, even though the original decision remains in the history.",
      items: [
        { case_id: "TS-0881", at: "Mar 4, 2026", family: "Harassment / abuse", outcome: "WARNING", final: true, counts: true, note: "Final, comparable scope. Counted." },
        { case_id: "TS-1019", at: "Aug 6, 2026", family: "Harassment / abuse", outcome: "AUDIENCE_RESTRICTION", final: true, counts: false, note: "OVERTURNED on appeal — excluded from the adverse count." },
      ],
    },
    history: [
      { at: "Aug 7, 2026 · 07:20 BST · 06:20 UTC", kind: "enforcement", actor: "delivery-svc", text: "Reversal executing. Case moved to Verifying; restoration not yet verified." },
      { at: "Aug 7, 2026 · 07:14 BST · 06:14 UTC", kind: "appeal", actor: "A. Costa", text: "Appeal OVERTURNED by an independent reviewer. Adverse repeat count updated to exclude this outcome." },
      { at: "Aug 6, 2026 · 16:10 BST · 15:10 UTC", kind: "appeal", actor: "City clerk's office", text: "Appeal filed with new contested evidence EV-81044." },
      { at: "Aug 6, 2026 · 09:02 BST · 08:02 UTC", kind: "decision", actor: "D. Mbeki", text: "Decision AUDIENCE_RESTRICTION recorded under TS-HAR-002 (ts-policy/2026.06.2)." },
    ],
  },
  {
    case_id: "TS-1051",
    title: "Lawful request — production order concerning a stored broadcast",
    org: "Meridian Holdings",
    tenant_id: "tnt_meridian_07",
    tier: "Enterprise",
    region: "europe-west4",
    content_type: "uploaded_asset",
    content_ref: "EVT-2025-1122 · Annual Board Broadcast",
    asset_ref: "AST-1D983",
    live_context: "NOT_LIVE",
    unrepeatable: false,
    risk_classification: "Medium",
    viewers: "None — replay window ended",
    reason_family: "Other",
    reason: "Lawful request for stored content and related records",
    signal_sources: ["lawful_request"],
    confidence: "INDETERMINATE",
    case_state: "TRIAGED",
    priority: "HIGH",
    mode: "LIVE",
    opened_local: "Aug 7, 2026 · 07:12 BST",
    opened_utc: "06:12 UTC",
    age: "36m",
    due_local: "Aug 14, 2026 · 17:00 BST",
    due_utc: "16:00 UTC",
    sla_state: "ON_TRACK",
    owner: "A. Costa",
    finding: "LEGAL_ESCALATION",
    enforcement_state: "NONE",
    appeal_state: "NOT_APPLICABLE",
    content_availability: "UNAVAILABLE_FOR_OTHER_REASON",
    legal_escalation: "Routed to Legal/Compliance — authenticity validation in progress",
    policy_version: "ts-policy/2026.07.4",
    urgent_live: false,
    verification_pending: false,
    next_action: "Authenticity validation sits with Legal/Compliance. Nothing is produced and no action is taken until the request is validated and scoped.",
    blockers: [
      { tone: "danger", text: "The request is UNVALIDATED. No action, production or notice may follow from receipt. This interface does not determine legal validity." },
      { tone: "warning", text: "Two active legal holds already cover the requested scope. Conflict check is outstanding." },
    ],
    content_context: [
      ["Asset", "AST-1D983 · Board Broadcast (archived)"],
      ["Distribution scope", "Invite only · replay window ended Feb 13, 2026"],
      ["Recording", "Archived · indefinite retention while holds are active"],
      ["Organization history", "3 open cases in the last 24 months; none final and adverse"],
      ["Exposure", "None — replay expired"],
      ["Platform health", "Preserve healthy; a governed restore would be required for any access"],
    ],
    legal_request: {
      authority: "Requesting authority recorded · detail restricted to Legal/Compliance",
      jurisdiction: "Netherlands",
      reference: "LR-2026-0442",
      channel: "Authenticated legal intake portal",
      scope: "AST-1D983 essence plus session participation records for ses_1180",
      deadline: "Aug 14, 2026 · 17:00 BST · 16:00 UTC",
      authenticity: "UNVALIDATED — routed to Legal/Compliance workflow",
      scope_validation: "Resolved to one Organization, one asset, one session",
      conflicts: "Legal holds GOV-HOLD-0118 and GOV-HOLD-0204 active over the scope; privacy assessment outstanding",
      disposition: "Not recorded — awaiting authorized legal owner",
      notice: "Not sent. Organization/user notice follows applicable rules; the console does not assume notice is always permitted.",
    },
    evidence: [
      {
        evidence_id: "EV-89001",
        type: "Legal request",
        source: "authority · via legal intake",
        collector: "legal-intake",
        created: "Aug 7, 2026 · 07:10 BST · 06:10 UTC",
        content_ref: "LR-2026-0442 · scope AST-1D983, ses_1180",
        integrity: "present",
        integrity_ref: "Intake receipt rcpt_2210",
        provenance: "Received through the authenticated legal channel; authenticity not yet confirmed",
        confidence: "INDETERMINATE",
        sensitivity: "Legally sensitive · Legal/Compliance profile required",
        access_rule: "Authorized Legal/Compliance only",
        retention: "Legal retention class L1 · hold overrides",
        relation: "—",
      },
      {
        evidence_id: "EV-89006",
        type: "Metadata",
        source: "system · governance service",
        collector: "governance-svc",
        created: "Aug 7, 2026 · 07:14 BST · 06:14 UTC",
        content_ref: "Legal-hold conflict report over the requested scope",
        integrity: "verified",
        integrity_ref: "sha256:aa04…9911",
        provenance: "Authoritative service read",
        confidence: "—",
        sensitivity: "Hold references; sensitive legal detail gated",
        access_rule: "Profile-gated",
        retention: "Legal retention class L1",
        relation: "Context for the conflict check",
      },
    ],
    assessments: [
      {
        family: "Other",
        clause: "TS-LEG-001",
        clause_text: "Lawful requests are recorded, routed and validated through the governed legal workflow before any platform action is taken.",
        version_at_content: "ts-policy/2026.07.4",
        version_current: "ts-policy/2026.07.4",
        applicability: "A production order concerning stored tenant content has been received and scoped.",
        supporting: ["EV-89001", "EV-89006"],
        challenging: [],
        reviewer_confidence: "Not applicable — Trust & Safety records and routes; it does not assess legal validity.",
        countervailing: "Two active legal holds and an outstanding privacy assessment may constrain what can be produced.",
        jurisdiction: "Netherlands. Recorded as a routing fact. Applicability and validity are a Legal determination, not a UI conclusion.",
        finding: "LEGAL_ESCALATION",
        rationale: "Routed for specialized determination. No content-policy finding is appropriate and no enforcement follows from receipt.",
      },
    ],
    decision: {
      outcome: "ESCALATE_LEGAL_OR_SAFETY",
      recorded_by: "A. Costa · Trust & Safety",
      recorded_at: "Aug 7, 2026 · 07:16 BST · 06:16 UTC",
      rationale: "Route to the authorized legal owner. Trust & Safety records the request and its scope; the disposition and basis are recorded by Legal/Compliance.",
      approvers: "Legal/Compliance disposition required — separate legal authorization.",
      scope: "Recording and routing only. No content action.",
      reversibility: "Not applicable — nothing has been changed.",
    },
    enforcement: {
      state: "NONE",
      requested: "—",
      approved: "—",
      executing: "—",
      verified: "—",
      correlation: "—",
      residual: "—",
      note: "Blocked pending legal validation. An unvalidated request cannot produce enforcement.",
    },
    communications: [
      {
        kind: "Internal handoff",
        to: "Legal/Compliance · lawful request queue",
        sent: "Aug 7, 2026 · 07:16 BST · 06:16 UTC",
        delivery: "Delivered",
        summary: "Request record, resolved scope, hold conflicts and the deadline passed to the authorized legal owner.",
      },
    ],
    appeal: {
      state: "NOT_APPLICABLE",
      eligibility: "Not applicable to a lawful-request record.",
      deadline: "—",
      reviewer: "—",
      submission: "—",
      outcome: "—",
      effect: "—",
    },
    verification: [],
    repeat: {
      final_adverse: 0,
      overturned_excluded: 0,
      window: "24 months, per retention policy",
      note: "A lawful request is not an allegation against the Organization and never contributes to a repeat-violation count.",
      items: [],
    },
    history: [
      { at: "Aug 7, 2026 · 07:16 BST · 06:16 UTC", kind: "decision", actor: "A. Costa", text: "Routed to Legal/Compliance. Finding recorded as LEGAL_ESCALATION." },
      { at: "Aug 7, 2026 · 07:14 BST · 06:14 UTC", kind: "evidence", actor: "governance-svc", text: "Hold conflict report attached — two active holds over the requested scope." },
      { at: "Aug 7, 2026 · 07:12 BST · 06:12 UTC", kind: "signal", actor: "legal-intake", text: "Lawful request LR-2026-0442 received. Recorded as unvalidated." },
    ],
  },
  {
    case_id: "TS-1044",
    title: "Automated platform-abuse signal on a test-mode rehearsal clip",
    org: "Beacon Retail Group",
    tenant_id: "tnt_beacon_22",
    tier: "Business",
    region: "us-west2",
    content_type: "uploaded_asset",
    content_ref: "EVT-2026-0829 · rehearsal (test mode)",
    asset_ref: "AST-7C220",
    live_context: "NOT_LIVE",
    unrepeatable: false,
    risk_classification: "Low",
    viewers: "No production sessions — test mode",
    reason_family: "Platform abuse",
    reason: "Suspected circumvention of encoding limits",
    signal_sources: ["automated_signal"],
    confidence: "LOW",
    case_state: "CLOSED",
    priority: "INFORMATIONAL",
    mode: "TEST",
    opened_local: "Aug 6, 2026 · 17:02 BST",
    opened_utc: "16:02 UTC",
    age: "14h 46m",
    due_local: "Aug 13, 2026 · 17:02 BST",
    due_utc: "16:02 UTC",
    sla_state: "ON_TRACK",
    owner: "D. Mbeki",
    finding: "NO_FINDING",
    enforcement_state: "NONE",
    appeal_state: "NOT_APPLICABLE",
    content_availability: "AVAILABLE",
    legal_escalation: "Not escalated",
    policy_version: "ts-policy/2026.07.4",
    urgent_live: false,
    verification_pending: false,
    next_action: "Closed with no finding. Retained for detector-precision measurement.",
    blockers: [],
    content_context: [
      ["Asset", "AST-7C220 · Product Launch Rehearsal (test mode)"],
      ["Distribution scope", "Test mode · 4 Organization members"],
      ["Recording", "Finalized · deletion scheduled Aug 13, 2026 under the test retention policy"],
      ["Organization history", "No final adverse decision in the visible window"],
      ["Exposure", "None in production"],
      ["Platform health", "Healthy"],
    ],
    evidence: [
      {
        evidence_id: "EV-88801",
        type: "Automated signal",
        source: "system · detector zst.abuse.encode/2.0.4",
        collector: "abuse-detector-svc",
        created: "Aug 6, 2026 · 17:01 BST · 16:01 UTC",
        content_ref: "AST-7C220 · full duration",
        integrity: "verified",
        integrity_ref: "sha256:5f10…bb27",
        provenance: "Detector output; rule version retained",
        confidence: "LOW",
        sensitivity: "Operational metadata",
        access_rule: "Standing read in scope",
        retention: "Case retention class C4 · 12 months",
        relation: "—",
      },
    ],
    assessments: [
      {
        family: "Platform abuse",
        clause: "TS-ABU-001",
        clause_text: "Circumventing platform limits or protections is prohibited.",
        version_at_content: "ts-policy/2026.07.4",
        version_current: "ts-policy/2026.07.4",
        applicability: "The detector flagged an encoding pattern consistent with a bitrate-limit bypass.",
        supporting: ["EV-88801"],
        challenging: [],
        reviewer_confidence: "High that no violation occurred — the pattern is explained by a documented rehearsal preset in test mode.",
        countervailing: "The activity is test-mode rehearsal on a permitted preset. No production audience or entitlement was affected.",
        jurisdiction: "Produced in US · Los Angeles. Routing fact only.",
        finding: "NO_FINDING",
        rationale: "The signal is explained by legitimate test-mode configuration. Recorded as a detector false positive against rule version 2.0.4 for precision measurement.",
      },
    ],
    decision: {
      outcome: "NO_ACTION",
      recorded_by: "D. Mbeki · Trust & Safety",
      recorded_at: "Aug 6, 2026 · 18:04 BST · 17:04 UTC",
      rationale: "No adequate policy basis for action. The detector output is retained with its rule version so precision can be measured.",
      approvers: "Not required at this outcome.",
      scope: "None.",
      reversibility: "Not applicable — nothing was changed.",
    },
    enforcement: {
      state: "NONE",
      requested: "—",
      approved: "—",
      executing: "—",
      verified: "—",
      correlation: "—",
      residual: "—",
      note: "No enforcement. A low-confidence signal never becomes an action on its own.",
    },
    communications: [],
    appeal: {
      state: "NOT_APPLICABLE",
      eligibility: "No adverse decision was made.",
      deadline: "—",
      reviewer: "—",
      submission: "—",
      outcome: "—",
      effect: "—",
    },
    verification: [],
    repeat: {
      final_adverse: 0,
      overturned_excluded: 0,
      window: "24 months, per retention policy",
      note: "A no-finding outcome never contributes to an adverse count.",
      items: [],
    },
    history: [
      { at: "Aug 6, 2026 · 18:04 BST · 17:04 UTC", kind: "decision", actor: "D. Mbeki", text: "Closed NO_ACTION with finding NO_FINDING. Recorded against detector rule 2.0.4." },
      { at: "Aug 6, 2026 · 17:02 BST · 16:02 UTC", kind: "signal", actor: "zst.abuse.encode/2.0.4", text: "Automated signal created at LOW confidence on a test-mode asset." },
    ],
  },
  {
    case_id: "TS-1047",
    title: "Organization restriction proposed after repeated unauthorized recording",
    org: "Helix Manufacturing",
    tenant_id: "tnt_helix_15",
    tier: "Standard",
    region: "europe-west4",
    content_type: "tenant_media",
    content_ref: "Multiple events · see supporting cases",
    asset_ref: "AST-5E447 and 2 others",
    live_context: "NOT_LIVE",
    unrepeatable: false,
    risk_classification: "High",
    viewers: "Suspended while quarantined",
    reason_family: "Unauthorized recording",
    reason: "Repeated broadcast of captured material without authorization",
    signal_sources: ["internal_referral", "security_referral"],
    confidence: "HIGH",
    case_state: "ACTION_PENDING",
    priority: "HIGH",
    mode: "LIVE",
    opened_local: "Aug 7, 2026 · 06:02 BST",
    opened_utc: "05:02 UTC",
    age: "1h 46m",
    due_local: "Aug 8, 2026 · 06:02 BST",
    due_utc: "05:02 UTC",
    sla_state: "WARNING",
    owner: "N. Rahman",
    finding: "VIOLATION_CONFIRMED",
    enforcement_state: "PROPOSED",
    appeal_state: "AVAILABLE",
    content_availability: "QUARANTINED",
    legal_escalation: "Not escalated",
    policy_version: "ts-policy/2026.07.4",
    urgent_live: false,
    verification_pending: false,
    next_action: "A capability restriction is proposed — not a full suspension. It needs a separate authorized approver; the requester cannot self-approve.",
    blockers: [
      { tone: "warning", text: "Awaiting a second authorized approver. Full suspension is not the default and is not what has been proposed." },
      { tone: "info", text: "Two of the three supporting cases are final. The third is unresolved and does not count as a final violation." },
    ],
    content_context: [
      ["Scope", "Organization capabilities · Helix Manufacturing"],
      ["Distribution scope", "1 quarantined asset; no active live event"],
      ["Recording", "AST-5E447 isolated from delivery under decision TS-2026-0951"],
      ["Organization history", "2 final adverse outcomes in the visible window, same policy family"],
      ["Exposure", "Grantee access suspended for the quarantined asset"],
      ["Platform health", "Healthy"],
    ],
    proposal: {
      capabilities: [
        { name: "Create new live events", proposed: "Restricted", basis: "Prevents recurrence during review" },
        { name: "Publish new replays", proposed: "Restricted", basis: "Prevents further distribution of captured material" },
        { name: "Existing stored media", proposed: "Unchanged", basis: "Preservation and evidence obligations" },
        { name: "Grantee access to past events", proposed: "Unchanged", basis: "Legitimate audience access is not the harm" },
        { name: "API access", proposed: "Unchanged", basis: "Not implicated by the verified conduct" },
        { name: "Organization sign-in", proposed: "Unchanged", basis: "Full suspension is not proposed" },
      ],
      active_live_events: "None",
      scheduled_unrepeatable: "None scheduled inside 30 days",
      stored_media: "3 assets · 1 quarantined",
      grantee_access: "612 registered grantees across past events",
      api_dependencies: "1 integration · read-only usage in the last 30 days",
      legal_holds: "None active for this Organization",
      supporting_cases: [
        { case_id: "TS-0994", outcome: "WARNING", final: true, counts: true, at: "May 12, 2026" },
        { case_id: "TS-1021", outcome: "ASSET_RESTRICTION", final: true, counts: true, at: "Jul 2, 2026" },
        { case_id: "TS-1047", outcome: "Proposed", final: false, counts: false, at: "Aug 7, 2026" },
      ],
      effective_time: "On approval, at the next authoritative service evaluation",
      recovery_criteria: "Two consecutive events with verified authorization evidence, plus an accepted remediation commitment.",
      communication_plan: "Organization decision notice with scope, effective time, disclosable basis and the appeal path; account contact called before the effective time.",
      approval: "Dual authorization. Requester excluded. Full suspension would additionally require Governance review.",
      governance_review: "Created automatically for material Organization-level enforcement.",
    },
    evidence: [
      {
        evidence_id: "EV-88600",
        type: "Report",
        source: "internal · Customer Operations referral",
        collector: "N. Rahman",
        created: "Aug 7, 2026 · 06:00 BST · 05:00 UTC",
        content_ref: "AST-5E447 · full duration",
        integrity: "present",
        integrity_ref: "Referral ref ref_1199",
        provenance: "Audited internal allegation",
        confidence: "HIGH",
        sensitivity: "Names third parties · PII gated",
        access_rule: "Trust & Safety",
        retention: "Case retention class C2 · 24 months",
        relation: "—",
      },
      {
        evidence_id: "EV-88604",
        type: "Provenance",
        source: "system · provenance verifier",
        collector: "provenance-svc",
        created: "Aug 7, 2026 · 06:20 BST · 05:20 UTC",
        content_ref: "AST-5E447 · manifest check",
        integrity: "absent",
        integrity_ref: "—",
        provenance: "No Content Credential manifest present. Absence is not evidence of wrongdoing.",
        confidence: "—",
        sensitivity: "Operational metadata",
        access_rule: "Standing read in scope",
        retention: "Case retention class C2 · 24 months",
        relation: "Neutral — recorded so its absence is not read as a finding",
      },
      {
        evidence_id: "EV-88611",
        type: "Metadata",
        source: "system · security referral",
        collector: "security-svc",
        created: "Aug 7, 2026 · 06:34 BST · 05:34 UTC",
        content_ref: "Upload provenance and source-device records",
        integrity: "verified",
        integrity_ref: "sha256:c410…8802",
        provenance: "High-integrity security referral",
        confidence: "HIGH",
        sensitivity: "Operational metadata",
        access_rule: "Trust & Safety; Security",
        retention: "Case retention class C2 · 24 months",
        relation: "Supports EV-88600",
      },
    ],
    assessments: [
      {
        family: "Unauthorized recording",
        clause: "TS-URC-002",
        clause_text: "Broadcasting material captured without the authorization the policy or contract requires is prohibited.",
        version_at_content: "ts-policy/2026.07.4",
        version_current: "ts-policy/2026.07.4",
        applicability: "Upload provenance places the source outside the authorized capture path for the third consecutive occurrence.",
        supporting: ["EV-88600", "EV-88611"],
        challenging: [],
        reviewer_confidence: "High — corroborated by an independent security referral with verified integrity.",
        countervailing: "The Organization has an open remediation commitment from TS-1021 that has not yet reached its review date.",
        jurisdiction: "Produced in Europe · Netherlands. Routing fact only.",
        finding: "VIOLATION_CONFIRMED",
        rationale: "Two final comparable prior outcomes plus verified provenance for a third occurrence support a capability restriction. A full suspension is not proportionate to the verified harm and is not proposed.",
      },
    ],
    decision: {
      outcome: "ORGANIZATION_RESTRICTION",
      recorded_by: "N. Rahman · Trust & Safety",
      recorded_at: "Aug 7, 2026 · 07:30 BST · 06:30 UTC",
      rationale: "Restrict only the two capabilities implicated by the verified conduct. Existing media, grantee access and sign-in are untouched because they are not the harm.",
      approvers: "Awaiting a separate authorized approver. Requester excluded.",
      scope: "Organization capabilities: create live events, publish replays",
      reversibility: "Reversible on the stated recovery criteria.",
    },
    enforcement: {
      state: "PROPOSED",
      requested: "Aug 7, 2026 · 07:30 BST · 06:30 UTC",
      approved: "—",
      executing: "—",
      verified: "—",
      correlation: "—",
      residual: "—",
      note: "Proposed. Execution goes through the authoritative entitlement and access services, then verification checks the capability matrix.",
    },
    communications: [
      {
        kind: "Internal handoff",
        to: "Trust & Safety lead · approval queue",
        sent: "Aug 7, 2026 · 07:31 BST · 06:31 UTC",
        delivery: "Delivered",
        summary: "Structured impact package for the second approver: capabilities, supporting final cases, exposure, recovery criteria.",
      },
    ],
    appeal: {
      state: "AVAILABLE",
      eligibility: "Will be eligible once the restriction is executed.",
      deadline: "Set on execution — 30 days from the effective time.",
      reviewer: "Independent of the original decision maker for severe actions.",
      submission: "Not filed.",
      outcome: "—",
      effect: "—",
    },
    verification: [
      { check: "Organization restriction", expected: "Capability matrix after enforcement", result: "Not started — enforcement is proposed", at: "—" },
      { check: "Residual exposure", expected: "New sessions and event scheduling blocked per scope", result: "Not started", at: "—" },
      { check: "Notifications", expected: "Decision notice delivery status", result: "Not started", at: "—" },
    ],
    repeat: {
      final_adverse: 2,
      overturned_excluded: 0,
      window: "24 months, per retention policy",
      note: "Two final, comparable adverse outcomes in the same policy family. The current case is unresolved and is not counted. A pattern may recommend review; it never auto-suspends.",
      items: [
        { case_id: "TS-0994", at: "May 12, 2026", family: "Unauthorized recording", outcome: "WARNING", final: true, counts: true, note: "Final, comparable scope. Counted." },
        { case_id: "TS-1021", at: "Jul 2, 2026", family: "Unauthorized recording", outcome: "ASSET_RESTRICTION", final: true, counts: true, note: "Final, comparable scope. Counted. Remediation commitment open." },
        { case_id: "TS-1047", at: "Aug 7, 2026", family: "Unauthorized recording", outcome: "ORGANIZATION_RESTRICTION (proposed)", final: false, counts: false, note: "Unresolved allegation — excluded from the final count." },
      ],
    },
    history: [
      { at: "Aug 7, 2026 · 07:31 BST · 06:31 UTC", kind: "communication", actor: "N. Rahman", text: "Impact package sent to the approval queue." },
      { at: "Aug 7, 2026 · 07:30 BST · 06:30 UTC", kind: "decision", actor: "N. Rahman", text: "ORGANIZATION_RESTRICTION proposed over two capabilities. Full suspension not proposed." },
      { at: "Aug 7, 2026 · 06:34 BST · 05:34 UTC", kind: "evidence", actor: "security-svc", text: "Security referral EV-88611 attached with verified integrity." },
      { at: "Aug 7, 2026 · 06:02 BST · 05:02 UTC", kind: "signal", actor: "N. Rahman", text: "Internal referral created as an audited allegation." },
    ],
  },
];

export const ORGANIZATIONS = [...new Set(CASES.map((c) => c.org))].sort();
